/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ametjavagui.AQAdvancedForms;

import ametjavagui.AirQualityForm;

/**
 *
 * @author MMORTO01
 */
public class AdvancedSpeciesSettings extends javax.swing.JFrame {

    /**
     * Creates new form AdvancedSpeciesSettings
     */
    
    AirQualityForm form;
    
    public AdvancedSpeciesSettings(AirQualityForm form) {
        this.form = form;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        AdvancedSpeciesSettingsLabel = new javax.swing.JLabel();
        ManualSpeciesEntryInfoLabel = new javax.swing.JTextArea();
        ManualSpeciesEntryTextField = new javax.swing.JTextField();
        ManualSQLQueryInfoLabel = new javax.swing.JTextArea();
        ManualSQLQueryTextField = new javax.swing.JTextField();
        CustomSpeciesNameLabel = new javax.swing.JTextArea();
        CustomSpeciesNameTextField = new javax.swing.JTextField();
        CustomSpeciesUnitLabel = new javax.swing.JTextArea();
        CustomSpeciesUnitTextField = new javax.swing.JTextField();
        SaveButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Advanced Species Settings");
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(441, 475));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(441, 475));
        jPanel1.setMinimumSize(new java.awt.Dimension(441, 475));
        jPanel1.setPreferredSize(new java.awt.Dimension(441, 475));

        AdvancedSpeciesSettingsLabel.setBackground(new java.awt.Color(255, 255, 255));
        AdvancedSpeciesSettingsLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        AdvancedSpeciesSettingsLabel.setForeground(new java.awt.Color(0, 112, 185));
        AdvancedSpeciesSettingsLabel.setText("Advanced Species Settings");

        ManualSpeciesEntryInfoLabel.setEditable(false);
        ManualSpeciesEntryInfoLabel.setBackground(new java.awt.Color(255, 255, 255));
        ManualSpeciesEntryInfoLabel.setColumns(20);
        ManualSpeciesEntryInfoLabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        ManualSpeciesEntryInfoLabel.setForeground(new java.awt.Color(0, 112, 185));
        ManualSpeciesEntryInfoLabel.setLineWrap(true);
        ManualSpeciesEntryInfoLabel.setRows(5);
        ManualSpeciesEntryInfoLabel.setText("Enter a species or multiple species manually. The species names must match the names used in the AMET database.  When entering multiple species, the names should be formatted in a comma separated list (i.e. SO4,NO3,NH4).");
        ManualSpeciesEntryInfoLabel.setWrapStyleWord(true);
        ManualSpeciesEntryInfoLabel.setMaximumSize(new java.awt.Dimension(401, 79));
        ManualSpeciesEntryInfoLabel.setMinimumSize(new java.awt.Dimension(401, 79));
        ManualSpeciesEntryInfoLabel.setPreferredSize(new java.awt.Dimension(401, 79));

        ManualSpeciesEntryTextField.setBackground(new java.awt.Color(191, 182, 172));
        ManualSpeciesEntryTextField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ManualSpeciesEntryTextField.setForeground(new java.awt.Color(0, 63, 105));
        ManualSpeciesEntryTextField.setToolTipText("");
        ManualSpeciesEntryTextField.setCaretColor(new java.awt.Color(0, 63, 105));
        ManualSpeciesEntryTextField.setPreferredSize(new java.awt.Dimension(401, 22));

        ManualSQLQueryInfoLabel.setEditable(false);
        ManualSQLQueryInfoLabel.setBackground(new java.awt.Color(255, 255, 255));
        ManualSQLQueryInfoLabel.setColumns(20);
        ManualSQLQueryInfoLabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        ManualSQLQueryInfoLabel.setForeground(new java.awt.Color(0, 112, 185));
        ManualSQLQueryInfoLabel.setLineWrap(true);
        ManualSQLQueryInfoLabel.setRows(5);
        ManualSQLQueryInfoLabel.setText("Enter a custom species query. The query must be a properly formatted MySQL query string. The following is an example of a custom query: (2*d.Ca_ob+d.K_ob+2*d.Mg_ob+d.NA_ob) as NVC_ob, (2*d.Ca_mod+d.K_mod+2*d.Mg_mod+d.Na_mod) as NVC_mod.  ");
        ManualSQLQueryInfoLabel.setWrapStyleWord(true);
        ManualSQLQueryInfoLabel.setMaximumSize(new java.awt.Dimension(401, 94));
        ManualSQLQueryInfoLabel.setMinimumSize(new java.awt.Dimension(401, 94));
        ManualSQLQueryInfoLabel.setPreferredSize(new java.awt.Dimension(401, 94));

        ManualSQLQueryTextField.setBackground(new java.awt.Color(191, 182, 172));
        ManualSQLQueryTextField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ManualSQLQueryTextField.setForeground(new java.awt.Color(0, 63, 105));
        ManualSQLQueryTextField.setToolTipText("");
        ManualSQLQueryTextField.setCaretColor(new java.awt.Color(0, 63, 105));
        ManualSQLQueryTextField.setPreferredSize(new java.awt.Dimension(401, 22));

        CustomSpeciesNameLabel.setEditable(false);
        CustomSpeciesNameLabel.setBackground(new java.awt.Color(255, 255, 255));
        CustomSpeciesNameLabel.setColumns(20);
        CustomSpeciesNameLabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        CustomSpeciesNameLabel.setForeground(new java.awt.Color(0, 112, 185));
        CustomSpeciesNameLabel.setLineWrap(true);
        CustomSpeciesNameLabel.setRows(5);
        CustomSpeciesNameLabel.setText("Enter a name for the custom species.");
        CustomSpeciesNameLabel.setWrapStyleWord(true);
        CustomSpeciesNameLabel.setMaximumSize(new java.awt.Dimension(401, 22));
        CustomSpeciesNameLabel.setMinimumSize(new java.awt.Dimension(401, 22));
        CustomSpeciesNameLabel.setPreferredSize(new java.awt.Dimension(401, 22));

        CustomSpeciesNameTextField.setBackground(new java.awt.Color(191, 182, 172));
        CustomSpeciesNameTextField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        CustomSpeciesNameTextField.setForeground(new java.awt.Color(0, 63, 105));
        CustomSpeciesNameTextField.setToolTipText("");
        CustomSpeciesNameTextField.setCaretColor(new java.awt.Color(0, 63, 105));
        CustomSpeciesNameTextField.setPreferredSize(new java.awt.Dimension(401, 22));

        CustomSpeciesUnitLabel.setEditable(false);
        CustomSpeciesUnitLabel.setBackground(new java.awt.Color(255, 255, 255));
        CustomSpeciesUnitLabel.setColumns(20);
        CustomSpeciesUnitLabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        CustomSpeciesUnitLabel.setForeground(new java.awt.Color(0, 112, 185));
        CustomSpeciesUnitLabel.setLineWrap(true);
        CustomSpeciesUnitLabel.setRows(5);
        CustomSpeciesUnitLabel.setText("Enter units for the custom species.");
        CustomSpeciesUnitLabel.setWrapStyleWord(true);
        CustomSpeciesUnitLabel.setMaximumSize(new java.awt.Dimension(401, 22));
        CustomSpeciesUnitLabel.setMinimumSize(new java.awt.Dimension(401, 22));
        CustomSpeciesUnitLabel.setPreferredSize(new java.awt.Dimension(401, 22));

        CustomSpeciesUnitTextField.setBackground(new java.awt.Color(191, 182, 172));
        CustomSpeciesUnitTextField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        CustomSpeciesUnitTextField.setForeground(new java.awt.Color(0, 63, 105));
        CustomSpeciesUnitTextField.setToolTipText("");
        CustomSpeciesUnitTextField.setCaretColor(new java.awt.Color(0, 63, 105));
        CustomSpeciesUnitTextField.setPreferredSize(new java.awt.Dimension(401, 22));

        SaveButton.setBackground(new java.awt.Color(0, 63, 105));
        SaveButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        SaveButton.setForeground(new java.awt.Color(191, 182, 172));
        SaveButton.setText("Save");
        SaveButton.setMaximumSize(new java.awt.Dimension(100, 26));
        SaveButton.setMinimumSize(new java.awt.Dimension(100, 26));
        SaveButton.setPreferredSize(new java.awt.Dimension(100, 26));
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        CancelButton.setBackground(new java.awt.Color(0, 63, 105));
        CancelButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        CancelButton.setForeground(new java.awt.Color(191, 182, 172));
        CancelButton.setText("Cancel");
        CancelButton.setMaximumSize(new java.awt.Dimension(100, 26));
        CancelButton.setMinimumSize(new java.awt.Dimension(100, 26));
        CancelButton.setPreferredSize(new java.awt.Dimension(100, 26));
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ManualSQLQueryTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CustomSpeciesNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CustomSpeciesNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CustomSpeciesUnitTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CustomSpeciesUnitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(SaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(CancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(AdvancedSpeciesSettingsLabel)
                    .addComponent(ManualSpeciesEntryTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ManualSQLQueryInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ManualSpeciesEntryInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AdvancedSpeciesSettingsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ManualSpeciesEntryInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ManualSpeciesEntryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ManualSQLQueryInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ManualSQLQueryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CustomSpeciesNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CustomSpeciesNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CustomSpeciesUnitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CustomSpeciesUnitTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        form.custom_species = form.textFormat(ManualSpeciesEntryTextField.getText());
        form.custom_species_name = form.textFormat(CustomSpeciesNameTextField.getText());
        form.custom_units = form.textFormat(CustomSpeciesUnitTextField.getText());
        form.custom_species_query = form.textFormat(ManualSQLQueryTextField.getText());
        
        System.out.println("Advanced Species Settings Saved");
        setVisible(false);
        dispose();
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_CancelButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdvancedSpeciesSettingsLabel;
    private javax.swing.JButton CancelButton;
    private javax.swing.JTextArea CustomSpeciesNameLabel;
    private javax.swing.JTextField CustomSpeciesNameTextField;
    private javax.swing.JTextArea CustomSpeciesUnitLabel;
    private javax.swing.JTextField CustomSpeciesUnitTextField;
    private javax.swing.JTextArea ManualSQLQueryInfoLabel;
    private javax.swing.JTextField ManualSQLQueryTextField;
    private javax.swing.JTextArea ManualSpeciesEntryInfoLabel;
    private javax.swing.JTextField ManualSpeciesEntryTextField;
    private javax.swing.JButton SaveButton;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
