/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ametjavagui.AQAdvancedForms;

import ametjavagui.AirQualityForm;

/**
 *
 * @author MMORTO01
 */
public class SpatialPlotOptions extends javax.swing.JFrame {

    /**
     * Creates new form SpatialPlotOptions
     */
    
    AirQualityForm form;
    
    public SpatialPlotOptions(AirQualityForm form) {
        this.form = form;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        SymbolSizeFactorLabel = new javax.swing.JLabel();
        SymbolSizeFactorTextField = new javax.swing.JTextField();
        SymbolSizeInteractiveLabel = new javax.swing.JLabel();
        SymbolSizeInteractiveTextField = new javax.swing.JTextField();
        OutlierSizeInteractiveLabel = new javax.swing.JLabel();
        OutlierSizeInteractiveTextField = new javax.swing.JTextField();
        FillOapcityInteractiveLabel = new javax.swing.JLabel();
        FillOpacityInteractiveTextField = new javax.swing.JTextField();
        SpatailPlotSettingsLabel = new javax.swing.JLabel();
        NumberIntervalsLabel = new javax.swing.JLabel();
        NumberIntervalsTextField = new javax.swing.JTextField();
        PercentErrorLabel = new javax.swing.JLabel();
        PercentErrorTextField = new javax.swing.JTextField();
        AbsoluteErrorLabel = new javax.swing.JLabel();
        AbsoluteErrorTextField = new javax.swing.JTextField();
        PercentMinLabel = new javax.swing.JLabel();
        PercentMinTextField = new javax.swing.JTextField();
        PercentMaxLabel = new javax.swing.JLabel();
        PercentMaxTextField = new javax.swing.JTextField();
        AbsoluteMinLabel = new javax.swing.JLabel();
        AbsoluteMinTextField = new javax.swing.JTextField();
        AbsoluteMaxLabel = new javax.swing.JLabel();
        AbsoluteMaxTextField = new javax.swing.JTextField();
        DiffMinLabel = new javax.swing.JLabel();
        DiffMinTextField = new javax.swing.JTextField();
        DiffMaxLabel = new javax.swing.JLabel();
        DiffMaxTextField = new javax.swing.JTextField();
        HistogramMaxLabel = new javax.swing.JLabel();
        HistogramMaxTextField = new javax.swing.JTextField();
        RMSERangeMaxLabel = new javax.swing.JLabel();
        RMSERangeMaxTextField = new javax.swing.JTextField();
        SpatialPlotSettingsInfoLabel = new javax.swing.JTextArea();
        QuantileMinLabel = new javax.swing.JLabel();
        QuantileMinTextField = new javax.swing.JTextField();
        QuantileMaxLabel = new javax.swing.JLabel();
        QuantileMaxTextField = new javax.swing.JTextField();
        SpatialPlotOptionsLabel = new javax.swing.JLabel();
        SpatialPlotOptionsComboBox = new javax.swing.JComboBox<>();
        SaveButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        SpatialOptionsLabel = new javax.swing.JTextArea();
        GreyscaleCheckBox = new javax.swing.JCheckBox();
        CountiesCheckBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Spatial Plot Settings");
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(1070, 500));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(0, 112, 185));
        jPanel1.setMaximumSize(new java.awt.Dimension(1070, 500));
        jPanel1.setMinimumSize(new java.awt.Dimension(1070, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(1070, 500));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        SymbolSizeFactorLabel.setBackground(new java.awt.Color(255, 255, 255));
        SymbolSizeFactorLabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        SymbolSizeFactorLabel.setForeground(new java.awt.Color(0, 112, 185));
        SymbolSizeFactorLabel.setText("Symbol Size Factor (Default is 1)");

        SymbolSizeFactorTextField.setBackground(new java.awt.Color(191, 182, 172));
        SymbolSizeFactorTextField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        SymbolSizeFactorTextField.setForeground(new java.awt.Color(0, 63, 105));
        SymbolSizeFactorTextField.setText("1");
        SymbolSizeFactorTextField.setMinimumSize(new java.awt.Dimension(60, 23));
        SymbolSizeFactorTextField.setPreferredSize(new java.awt.Dimension(60, 23));

        SymbolSizeInteractiveLabel.setBackground(new java.awt.Color(255, 255, 255));
        SymbolSizeInteractiveLabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        SymbolSizeInteractiveLabel.setForeground(new java.awt.Color(0, 112, 185));
        SymbolSizeInteractiveLabel.setText("Symbol Size on Interactive Spatial Plots (0 = Variable Radius)  ");

        SymbolSizeInteractiveTextField.setBackground(new java.awt.Color(191, 182, 172));
        SymbolSizeInteractiveTextField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        SymbolSizeInteractiveTextField.setForeground(new java.awt.Color(0, 63, 105));
        SymbolSizeInteractiveTextField.setText("0");
        SymbolSizeInteractiveTextField.setMinimumSize(new java.awt.Dimension(60, 23));
        SymbolSizeInteractiveTextField.setPreferredSize(new java.awt.Dimension(60, 23));

        OutlierSizeInteractiveLabel.setBackground(new java.awt.Color(255, 255, 255));
        OutlierSizeInteractiveLabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        OutlierSizeInteractiveLabel.setForeground(new java.awt.Color(0, 112, 185));
        OutlierSizeInteractiveLabel.setText("Symbol Size of Outliers on Interactive Spatial Plots  ");

        OutlierSizeInteractiveTextField.setBackground(new java.awt.Color(191, 182, 172));
        OutlierSizeInteractiveTextField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        OutlierSizeInteractiveTextField.setForeground(new java.awt.Color(0, 63, 105));
        OutlierSizeInteractiveTextField.setText("40");
        OutlierSizeInteractiveTextField.setMinimumSize(new java.awt.Dimension(60, 23));
        OutlierSizeInteractiveTextField.setPreferredSize(new java.awt.Dimension(60, 23));

        FillOapcityInteractiveLabel.setBackground(new java.awt.Color(255, 255, 255));
        FillOapcityInteractiveLabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        FillOapcityInteractiveLabel.setForeground(new java.awt.Color(0, 112, 185));
        FillOapcityInteractiveLabel.setText("Fill Opacity on Interactive Spatial Plots  ");

        FillOpacityInteractiveTextField.setBackground(new java.awt.Color(191, 182, 172));
        FillOpacityInteractiveTextField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        FillOpacityInteractiveTextField.setForeground(new java.awt.Color(0, 63, 105));
        FillOpacityInteractiveTextField.setText("0.8");
        FillOpacityInteractiveTextField.setMinimumSize(new java.awt.Dimension(60, 23));
        FillOpacityInteractiveTextField.setPreferredSize(new java.awt.Dimension(60, 23));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SymbolSizeFactorLabel)
                    .addComponent(SymbolSizeInteractiveLabel)
                    .addComponent(OutlierSizeInteractiveLabel)
                    .addComponent(FillOapcityInteractiveLabel)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SymbolSizeFactorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SymbolSizeInteractiveTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(OutlierSizeInteractiveTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FillOpacityInteractiveTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, 0))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SymbolSizeFactorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SymbolSizeFactorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SymbolSizeInteractiveLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SymbolSizeInteractiveTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(OutlierSizeInteractiveLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OutlierSizeInteractiveTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(FillOapcityInteractiveLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FillOpacityInteractiveTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        SpatailPlotSettingsLabel.setBackground(new java.awt.Color(255, 255, 255));
        SpatailPlotSettingsLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        SpatailPlotSettingsLabel.setForeground(new java.awt.Color(0, 112, 185));
        SpatailPlotSettingsLabel.setText("Spatial Plot Settings");

        NumberIntervalsLabel.setBackground(new java.awt.Color(255, 255, 255));
        NumberIntervalsLabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        NumberIntervalsLabel.setForeground(new java.awt.Color(0, 112, 185));
        NumberIntervalsLabel.setText("Number of Intervals:");

        NumberIntervalsTextField.setBackground(new java.awt.Color(191, 182, 172));
        NumberIntervalsTextField.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        NumberIntervalsTextField.setForeground(new java.awt.Color(0, 63, 105));
        NumberIntervalsTextField.setMinimumSize(new java.awt.Dimension(60, 22));
        NumberIntervalsTextField.setPreferredSize(new java.awt.Dimension(60, 22));

        PercentErrorLabel.setBackground(new java.awt.Color(255, 255, 255));
        PercentErrorLabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        PercentErrorLabel.setForeground(new java.awt.Color(0, 112, 185));
        PercentErrorLabel.setText("Percent Error Range Max:");

        PercentErrorTextField.setBackground(new java.awt.Color(191, 182, 172));
        PercentErrorTextField.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        PercentErrorTextField.setForeground(new java.awt.Color(0, 63, 105));
        PercentErrorTextField.setMinimumSize(new java.awt.Dimension(60, 22));
        PercentErrorTextField.setPreferredSize(new java.awt.Dimension(60, 22));

        AbsoluteErrorLabel.setBackground(new java.awt.Color(255, 255, 255));
        AbsoluteErrorLabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        AbsoluteErrorLabel.setForeground(new java.awt.Color(0, 112, 185));
        AbsoluteErrorLabel.setText("Absolute Error Range Max:");

        AbsoluteErrorTextField.setBackground(new java.awt.Color(191, 182, 172));
        AbsoluteErrorTextField.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        AbsoluteErrorTextField.setForeground(new java.awt.Color(0, 63, 105));
        AbsoluteErrorTextField.setMinimumSize(new java.awt.Dimension(60, 22));
        AbsoluteErrorTextField.setPreferredSize(new java.awt.Dimension(60, 22));

        PercentMinLabel.setBackground(new java.awt.Color(255, 255, 255));
        PercentMinLabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        PercentMinLabel.setForeground(new java.awt.Color(0, 112, 185));
        PercentMinLabel.setText("Percent Range Min:");

        PercentMinTextField.setBackground(new java.awt.Color(191, 182, 172));
        PercentMinTextField.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        PercentMinTextField.setForeground(new java.awt.Color(0, 63, 105));
        PercentMinTextField.setMinimumSize(new java.awt.Dimension(60, 22));
        PercentMinTextField.setPreferredSize(new java.awt.Dimension(60, 22));

        PercentMaxLabel.setBackground(new java.awt.Color(255, 255, 255));
        PercentMaxLabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        PercentMaxLabel.setForeground(new java.awt.Color(0, 112, 185));
        PercentMaxLabel.setText("Percent Range Max:");

        PercentMaxTextField.setBackground(new java.awt.Color(191, 182, 172));
        PercentMaxTextField.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        PercentMaxTextField.setForeground(new java.awt.Color(0, 63, 105));
        PercentMaxTextField.setMinimumSize(new java.awt.Dimension(60, 22));
        PercentMaxTextField.setPreferredSize(new java.awt.Dimension(60, 22));

        AbsoluteMinLabel.setBackground(new java.awt.Color(255, 255, 255));
        AbsoluteMinLabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        AbsoluteMinLabel.setForeground(new java.awt.Color(0, 112, 185));
        AbsoluteMinLabel.setText("Absolute Range Min:");

        AbsoluteMinTextField.setBackground(new java.awt.Color(191, 182, 172));
        AbsoluteMinTextField.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        AbsoluteMinTextField.setForeground(new java.awt.Color(0, 63, 105));
        AbsoluteMinTextField.setMinimumSize(new java.awt.Dimension(60, 22));
        AbsoluteMinTextField.setPreferredSize(new java.awt.Dimension(60, 22));

        AbsoluteMaxLabel.setBackground(new java.awt.Color(255, 255, 255));
        AbsoluteMaxLabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        AbsoluteMaxLabel.setForeground(new java.awt.Color(0, 112, 185));
        AbsoluteMaxLabel.setText("Absolute Range Max:");

        AbsoluteMaxTextField.setBackground(new java.awt.Color(191, 182, 172));
        AbsoluteMaxTextField.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        AbsoluteMaxTextField.setForeground(new java.awt.Color(0, 63, 105));
        AbsoluteMaxTextField.setMinimumSize(new java.awt.Dimension(60, 22));
        AbsoluteMaxTextField.setPreferredSize(new java.awt.Dimension(60, 22));

        DiffMinLabel.setBackground(new java.awt.Color(255, 255, 255));
        DiffMinLabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        DiffMinLabel.setForeground(new java.awt.Color(0, 112, 185));
        DiffMinLabel.setText("Difference Min:");

        DiffMinTextField.setBackground(new java.awt.Color(191, 182, 172));
        DiffMinTextField.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        DiffMinTextField.setForeground(new java.awt.Color(0, 63, 105));
        DiffMinTextField.setMinimumSize(new java.awt.Dimension(60, 22));
        DiffMinTextField.setPreferredSize(new java.awt.Dimension(60, 22));

        DiffMaxLabel.setBackground(new java.awt.Color(255, 255, 255));
        DiffMaxLabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        DiffMaxLabel.setForeground(new java.awt.Color(0, 112, 185));
        DiffMaxLabel.setText("Difference Max:");

        DiffMaxTextField.setBackground(new java.awt.Color(191, 182, 172));
        DiffMaxTextField.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        DiffMaxTextField.setForeground(new java.awt.Color(0, 63, 105));
        DiffMaxTextField.setMinimumSize(new java.awt.Dimension(60, 22));
        DiffMaxTextField.setPreferredSize(new java.awt.Dimension(60, 22));

        HistogramMaxLabel.setBackground(new java.awt.Color(255, 255, 255));
        HistogramMaxLabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        HistogramMaxLabel.setForeground(new java.awt.Color(0, 112, 185));
        HistogramMaxLabel.setText("Histogram Max:");

        HistogramMaxTextField.setBackground(new java.awt.Color(191, 182, 172));
        HistogramMaxTextField.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        HistogramMaxTextField.setForeground(new java.awt.Color(0, 63, 105));
        HistogramMaxTextField.setMinimumSize(new java.awt.Dimension(60, 22));
        HistogramMaxTextField.setPreferredSize(new java.awt.Dimension(60, 22));

        RMSERangeMaxLabel.setBackground(new java.awt.Color(255, 255, 255));
        RMSERangeMaxLabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        RMSERangeMaxLabel.setForeground(new java.awt.Color(0, 112, 185));
        RMSERangeMaxLabel.setText("RMSE Range Max:");

        RMSERangeMaxTextField.setBackground(new java.awt.Color(191, 182, 172));
        RMSERangeMaxTextField.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        RMSERangeMaxTextField.setForeground(new java.awt.Color(0, 63, 105));
        RMSERangeMaxTextField.setMinimumSize(new java.awt.Dimension(60, 22));
        RMSERangeMaxTextField.setPreferredSize(new java.awt.Dimension(60, 22));

        SpatialPlotSettingsInfoLabel.setEditable(false);
        SpatialPlotSettingsInfoLabel.setBackground(new java.awt.Color(255, 255, 255));
        SpatialPlotSettingsInfoLabel.setColumns(20);
        SpatialPlotSettingsInfoLabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        SpatialPlotSettingsInfoLabel.setForeground(new java.awt.Color(0, 112, 185));
        SpatialPlotSettingsInfoLabel.setLineWrap(true);
        SpatialPlotSettingsInfoLabel.setRows(5);
        SpatialPlotSettingsInfoLabel.setText("Adjust plot ranges based on quantile to avoid extreme ranges due to outliers. Values that fall outside the plotting range will show up as grey. Currently does not affect the actual data values included, only the plot range.");
        SpatialPlotSettingsInfoLabel.setWrapStyleWord(true);

        QuantileMinLabel.setBackground(new java.awt.Color(255, 255, 255));
        QuantileMinLabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        QuantileMinLabel.setForeground(new java.awt.Color(0, 112, 185));
        QuantileMinLabel.setText("Quantile Min:");

        QuantileMinTextField.setBackground(new java.awt.Color(191, 182, 172));
        QuantileMinTextField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        QuantileMinTextField.setForeground(new java.awt.Color(0, 63, 105));
        QuantileMinTextField.setText("0.001");
        QuantileMinTextField.setMinimumSize(new java.awt.Dimension(60, 22));
        QuantileMinTextField.setPreferredSize(new java.awt.Dimension(60, 22));

        QuantileMaxLabel.setBackground(new java.awt.Color(255, 255, 255));
        QuantileMaxLabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        QuantileMaxLabel.setForeground(new java.awt.Color(0, 112, 185));
        QuantileMaxLabel.setText("Quantile Max:");

        QuantileMaxTextField.setBackground(new java.awt.Color(191, 182, 172));
        QuantileMaxTextField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        QuantileMaxTextField.setForeground(new java.awt.Color(0, 63, 105));
        QuantileMaxTextField.setText("0.999");
        QuantileMaxTextField.setMinimumSize(new java.awt.Dimension(60, 22));
        QuantileMaxTextField.setPreferredSize(new java.awt.Dimension(60, 22));

        SpatialPlotOptionsLabel.setBackground(new java.awt.Color(255, 255, 255));
        SpatialPlotOptionsLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        SpatialPlotOptionsLabel.setForeground(new java.awt.Color(0, 112, 185));
        SpatialPlotOptionsLabel.setText("Spatial Plot Options");

        SpatialPlotOptionsComboBox.setBackground(new java.awt.Color(191, 182, 172));
        SpatialPlotOptionsComboBox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        SpatialPlotOptionsComboBox.setForeground(new java.awt.Color(0, 63, 105));
        SpatialPlotOptionsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Open Street Map: Default", "Open Street Map: Black and White", "Open TOPO Map", "ESRI World Imagery", "HERE Hybrid Data" }));

        SaveButton.setBackground(new java.awt.Color(0, 63, 105));
        SaveButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        SaveButton.setForeground(new java.awt.Color(191, 182, 172));
        SaveButton.setText("Save");
        SaveButton.setMaximumSize(new java.awt.Dimension(100, 26));
        SaveButton.setMinimumSize(new java.awt.Dimension(100, 26));
        SaveButton.setPreferredSize(new java.awt.Dimension(100, 26));
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        CancelButton.setBackground(new java.awt.Color(0, 63, 105));
        CancelButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        CancelButton.setForeground(new java.awt.Color(191, 182, 172));
        CancelButton.setText("Cancel");
        CancelButton.setMaximumSize(new java.awt.Dimension(100, 26));
        CancelButton.setMinimumSize(new java.awt.Dimension(100, 26));
        CancelButton.setPreferredSize(new java.awt.Dimension(100, 26));
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        SpatialOptionsLabel.setEditable(false);
        SpatialOptionsLabel.setBackground(new java.awt.Color(255, 255, 255));
        SpatialOptionsLabel.setColumns(20);
        SpatialOptionsLabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        SpatialOptionsLabel.setForeground(new java.awt.Color(0, 112, 185));
        SpatialOptionsLabel.setLineWrap(true);
        SpatialOptionsLabel.setRows(5);
        SpatialOptionsLabel.setText("These options apply to either the stats and plots program, in which a percent range would be entered, or the spatial plot program, in which case a concentrations range would be entered.");
        SpatialOptionsLabel.setWrapStyleWord(true);
        SpatialOptionsLabel.setMaximumSize(new java.awt.Dimension(440, 71));
        SpatialOptionsLabel.setMinimumSize(new java.awt.Dimension(440, 71));
        SpatialOptionsLabel.setPreferredSize(new java.awt.Dimension(440, 71));

        GreyscaleCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        GreyscaleCheckBox.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        GreyscaleCheckBox.setForeground(new java.awt.Color(0, 112, 185));
        GreyscaleCheckBox.setText("Plot Using Greyscale");

        CountiesCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        CountiesCheckBox.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        CountiesCheckBox.setForeground(new java.awt.Color(0, 112, 185));
        CountiesCheckBox.setSelected(true);
        CountiesCheckBox.setText("Include Counties on Map");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(SpatailPlotSettingsLabel)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(PercentErrorLabel)
                                .addComponent(NumberIntervalsLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(PercentMinLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(AbsoluteMinLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(DiffMinLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(HistogramMaxLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGap(12, 12, 12)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(HistogramMaxTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(PercentMinTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(PercentMaxLabel))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(AbsoluteMinTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(AbsoluteMaxLabel))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(DiffMinTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(DiffMaxLabel))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(PercentErrorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(AbsoluteErrorLabel))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(NumberIntervalsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(RMSERangeMaxLabel)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(RMSERangeMaxTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(DiffMaxTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(AbsoluteMaxTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(PercentMaxTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(AbsoluteErrorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addComponent(SpatialPlotOptionsLabel)
                        .addComponent(SpatialPlotSettingsInfoLabel)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(SaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(SpatialPlotOptionsComboBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(QuantileMinLabel)
                            .addComponent(QuantileMaxLabel))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(QuantileMaxTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(QuantileMinTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(GreyscaleCheckBox)
                    .addComponent(CountiesCheckBox)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SpatialOptionsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SpatailPlotSettingsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(NumberIntervalsLabel)
                                    .addComponent(NumberIntervalsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(PercentErrorLabel)
                                    .addComponent(PercentErrorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AbsoluteErrorLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(PercentMinLabel)
                                    .addComponent(PercentMinTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(AbsoluteMinLabel)
                                    .addComponent(AbsoluteMinTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(DiffMinLabel)
                                    .addComponent(DiffMinTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(RMSERangeMaxTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RMSERangeMaxLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(AbsoluteErrorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(PercentMaxTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PercentMaxLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(AbsoluteMaxTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AbsoluteMaxLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(DiffMaxTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DiffMaxLabel))))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HistogramMaxLabel)
                            .addComponent(HistogramMaxTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SpatialPlotSettingsInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(QuantileMinLabel)
                            .addComponent(QuantileMinTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(QuantileMaxLabel)
                            .addComponent(QuantileMaxTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addComponent(SpatialPlotOptionsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SpatialPlotOptionsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(SpatialOptionsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(GreyscaleCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CountiesCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        form.num_ints = form.numNullFormat(NumberIntervalsTextField.getText());
        form.rmse_range_max = form.numNullFormat(RMSERangeMaxTextField.getText());
        form.perc_error_max = form.numNullFormat(PercentErrorTextField.getText());
        form.abs_error_max = form.numNullFormat(AbsoluteErrorTextField.getText());
        form.perc_range_min = form.numNullFormat(PercentMinTextField.getText());
        form.perc_range_max = form.numNullFormat(PercentMaxTextField.getText());
        form.abs_range_min = form.numNullFormat(AbsoluteMinTextField.getText());
        form.abs_range_max = form.numNullFormat(AbsoluteMaxTextField.getText());
        form.diff_range_min = form.numNullFormat(DiffMinTextField.getText());
        form.diff_range_max = form.numNullFormat(DiffMaxTextField.getText());
        form.hist_max = form.numNullFormat(HistogramMaxTextField.getText());
        form.quantile_min = form.numNullFormat(QuantileMinTextField.getText());
        form.quantile_max = form.numNullFormat(QuantileMaxTextField.getText());
        form.greyscale = form.checkBoxFormat(GreyscaleCheckBox);
        form.inc_counties = form.checkBoxFormat(CountiesCheckBox);
        form.symbol_size_fac = form.numNullFormat(SymbolSizeFactorTextField.getText());
        form.plot_radius = form.numNullFormat(SymbolSizeInteractiveTextField.getText());
        form.outlier_radius = form.numNullFormat(OutlierSizeInteractiveTextField.getText());
        form.fill_opacity = form.numNullFormat(FillOpacityInteractiveTextField.getText());
        form.map_type = mapTypeFormat(SpatialPlotOptionsComboBox.getSelectedItem().toString());
        System.out.println("Spatial Plot Options Saved");
        setVisible(false);
        dispose();
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_CancelButtonActionPerformed

    private String mapTypeFormat(String str) {
        switch(str) {
            case "Open Street Map: Default":
                return "1";
            case "Open Street Map: Black and White":
                return "2";
            case "Open TOPO Map":
                return "3";
            case "ESRI World Imagery":
                return "4";
            case "HERE Hybrid Data":
                return "5";
            default:
                return "";
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AbsoluteErrorLabel;
    private javax.swing.JTextField AbsoluteErrorTextField;
    private javax.swing.JLabel AbsoluteMaxLabel;
    private javax.swing.JTextField AbsoluteMaxTextField;
    private javax.swing.JLabel AbsoluteMinLabel;
    private javax.swing.JTextField AbsoluteMinTextField;
    private javax.swing.JButton CancelButton;
    private javax.swing.JCheckBox CountiesCheckBox;
    private javax.swing.JLabel DiffMaxLabel;
    private javax.swing.JTextField DiffMaxTextField;
    private javax.swing.JLabel DiffMinLabel;
    private javax.swing.JTextField DiffMinTextField;
    private javax.swing.JLabel FillOapcityInteractiveLabel;
    private javax.swing.JTextField FillOpacityInteractiveTextField;
    private javax.swing.JCheckBox GreyscaleCheckBox;
    private javax.swing.JLabel HistogramMaxLabel;
    private javax.swing.JTextField HistogramMaxTextField;
    private javax.swing.JLabel NumberIntervalsLabel;
    private javax.swing.JTextField NumberIntervalsTextField;
    private javax.swing.JLabel OutlierSizeInteractiveLabel;
    private javax.swing.JTextField OutlierSizeInteractiveTextField;
    private javax.swing.JLabel PercentErrorLabel;
    private javax.swing.JTextField PercentErrorTextField;
    private javax.swing.JLabel PercentMaxLabel;
    private javax.swing.JTextField PercentMaxTextField;
    private javax.swing.JLabel PercentMinLabel;
    private javax.swing.JTextField PercentMinTextField;
    private javax.swing.JLabel QuantileMaxLabel;
    private javax.swing.JTextField QuantileMaxTextField;
    private javax.swing.JLabel QuantileMinLabel;
    private javax.swing.JTextField QuantileMinTextField;
    private javax.swing.JLabel RMSERangeMaxLabel;
    private javax.swing.JTextField RMSERangeMaxTextField;
    private javax.swing.JButton SaveButton;
    private javax.swing.JLabel SpatailPlotSettingsLabel;
    private javax.swing.JTextArea SpatialOptionsLabel;
    private javax.swing.JComboBox<String> SpatialPlotOptionsComboBox;
    private javax.swing.JLabel SpatialPlotOptionsLabel;
    private javax.swing.JTextArea SpatialPlotSettingsInfoLabel;
    private javax.swing.JLabel SymbolSizeFactorLabel;
    private javax.swing.JTextField SymbolSizeFactorTextField;
    private javax.swing.JLabel SymbolSizeInteractiveLabel;
    private javax.swing.JTextField SymbolSizeInteractiveTextField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
