/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ametjavagui.METAdvancedForms;

import ametjavagui.MeteorologyForm;

/**
 *
 * @author Michael Morton
 */
public class RadiationPlotOptions extends javax.swing.JFrame {

    /**
     * Creates new form RadiationPlotOptions
     */
    
    MeteorologyForm form;
    
    public RadiationPlotOptions(MeteorologyForm form) {
        this.form = form;
        initComponents();

        DiurnalPlotCheckBox.setSelected(form.diurnal_rad);
        HistogramPlotCheckBox.setSelected(form.histogram_rad);
        SpatialPlotCheckBox.setSelected(form.spatial_rad);
        TimeSeriesPlotCheckBox.setSelected(form.time_series_rad);
        LatSouthTextField.setText(form.lat_south);
        LatNorthTextField.setText(form.lat_north);
        LonWestTextField.setText(form.lon_west);
        LonEastTextField.setText(form.lon_east);
        BiasLevelsTextField1.setText(form.bias_level1);
        BiasLevelsTextField2.setText(form.bias_level2);
        BiasLevelsTextField3.setText(form.bias_level3);
        BiasLevelsTextField4.setText(form.bias_level4);
        BiasLevelsTextField5.setText(form.bias_level5);
        BiasLevelsTextField6.setText(form.bias_level6);
        BiasLevelsTextField7.setText(form.bias_level7);
        BiasLevelsTextField8.setText(form.bias_level8);
        BiasLevelsTextField9.setText(form.bias_level9);
        BiasLevelsTextField10.setText(form.bias_level10);
        BiasLevelsTextField11.setText(form.bias_level11);
        BiasLevelsTextField12.setText(form.bias_level12);
        BiasLevelsTextField13.setText(form.bias_level13);
        BiasLevelsTextField14.setText(form.bias_level14);
        BiasLevelsTextField15.setText(form.bias_level15);
        RMSELevelsTextField1.setText(form.rmse_level1);
        RMSELevelsTextField2.setText(form.rmse_level2);
        RMSELevelsTextField3.setText(form.rmse_level3);
        RMSELevelsTextField4.setText(form.rmse_level4);
        RMSELevelsTextField5.setText(form.rmse_level5);
        RMSELevelsTextField6.setText(form.rmse_level6);
        RMSELevelsTextField7.setText(form.rmse_level7);
        RMSELevelsTextField8.setText(form.rmse_level8);
        RMSELevelsTextField9.setText(form.rmse_level9);
        RMSELevelsTextField10.setText(form.rmse_level10);
        RMSELevelsTextField11.setText(form.rmse_level11);
        RMSELevelsTextField12.setText(form.rmse_level12);
        RMSELevelsTextField13.setText(form.rmse_level13);
        MAELevelsTextField1.setText(form.mae_level1);
        MAELevelsTextField2.setText(form.mae_level2);
        MAELevelsTextField3.setText(form.mae_level3);
        MAELevelsTextField4.setText(form.mae_level4);
        MAELevelsTextField5.setText(form.mae_level5);
        MAELevelsTextField6.setText(form.mae_level6);
        MAELevelsTextField7.setText(form.mae_level7);
        MAELevelsTextField8.setText(form.mae_level8);
        MAELevelsTextField9.setText(form.mae_level9);
        MAELevelsTextField10.setText(form.mae_level10);
        MAELevelsTextField11.setText(form.mae_level11);
        SDevLevelsTextField1.setText(form.sdev_level1);
        SDevLevelsTextField2.setText(form.sdev_level2);
        SDevLevelsTextField3.setText(form.sdev_level3);
        SDevLevelsTextField4.setText(form.sdev_level4);
        SDevLevelsTextField5.setText(form.sdev_level5);
        SDevLevelsTextField6.setText(form.sdev_level6);
        SDevLevelsTextField7.setText(form.sdev_level7);
        SDevLevelsTextField8.setText(form.sdev_level8);
        SDevLevelsTextField9.setText(form.sdev_level9);
        SDevLevelsTextField10.setText(form.sdev_level10);
        SDevLevelsTextField11.setText(form.sdev_level11);
        SDevLevelsTextField12.setText(form.sdev_level12);
        SDevLevelsTextField13.setText(form.sdev_level13);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        RadiationPlotOptionsLabel = new javax.swing.JLabel();
        DiurnalPlotCheckBox = new javax.swing.JCheckBox();
        HistogramPlotCheckBox = new javax.swing.JCheckBox();
        SpatialPlotCheckBox = new javax.swing.JCheckBox();
        TimeSeriesPlotCheckBox = new javax.swing.JCheckBox();
        SpatialPlotOptionsLabel = new javax.swing.JLabel();
        SpatialPlotInfoLabel1 = new javax.swing.JLabel();
        SpatialPlotInfoLabel2 = new javax.swing.JLabel();
        LatSouthLabel = new javax.swing.JLabel();
        LatSouthTextField = new javax.swing.JTextField();
        LatNorthLabel = new javax.swing.JLabel();
        LatNorthTextField = new javax.swing.JTextField();
        LonWestLabel = new javax.swing.JLabel();
        LonWestTextField = new javax.swing.JTextField();
        LonEastLabel = new javax.swing.JLabel();
        LonEastTextField = new javax.swing.JTextField();
        LevelsLabel = new javax.swing.JLabel();
        LevelsTextArea = new javax.swing.JTextArea();
        BiasLevelsLabel = new javax.swing.JLabel();
        BiasLevelsTextField1 = new javax.swing.JTextField();
        BiasLevelsTextField2 = new javax.swing.JTextField();
        BiasLevelsTextField3 = new javax.swing.JTextField();
        BiasLevelsTextField4 = new javax.swing.JTextField();
        BiasLevelsTextField5 = new javax.swing.JTextField();
        BiasLevelsTextField6 = new javax.swing.JTextField();
        BiasLevelsTextField7 = new javax.swing.JTextField();
        BiasLevelsTextField8 = new javax.swing.JTextField();
        BiasLevelsTextField9 = new javax.swing.JTextField();
        BiasLevelsTextField10 = new javax.swing.JTextField();
        BiasLevelsTextField11 = new javax.swing.JTextField();
        BiasLevelsTextField12 = new javax.swing.JTextField();
        BiasLevelsTextField13 = new javax.swing.JTextField();
        BiasLevelsTextField14 = new javax.swing.JTextField();
        BiasLevelsTextField15 = new javax.swing.JTextField();
        RMSELevelsLabel = new javax.swing.JLabel();
        RMSELevelsTextField1 = new javax.swing.JTextField();
        RMSELevelsTextField2 = new javax.swing.JTextField();
        RMSELevelsTextField3 = new javax.swing.JTextField();
        RMSELevelsTextField4 = new javax.swing.JTextField();
        RMSELevelsTextField5 = new javax.swing.JTextField();
        RMSELevelsTextField6 = new javax.swing.JTextField();
        RMSELevelsTextField7 = new javax.swing.JTextField();
        RMSELevelsTextField8 = new javax.swing.JTextField();
        RMSELevelsTextField9 = new javax.swing.JTextField();
        RMSELevelsTextField10 = new javax.swing.JTextField();
        RMSELevelsTextField11 = new javax.swing.JTextField();
        RMSELevelsTextField12 = new javax.swing.JTextField();
        RMSELevelsTextField13 = new javax.swing.JTextField();
        MAELevelsLabel = new javax.swing.JLabel();
        MAELevelsTextField1 = new javax.swing.JTextField();
        MAELevelsTextField2 = new javax.swing.JTextField();
        MAELevelsTextField3 = new javax.swing.JTextField();
        MAELevelsTextField4 = new javax.swing.JTextField();
        MAELevelsTextField5 = new javax.swing.JTextField();
        MAELevelsTextField6 = new javax.swing.JTextField();
        MAELevelsTextField7 = new javax.swing.JTextField();
        MAELevelsTextField8 = new javax.swing.JTextField();
        MAELevelsTextField9 = new javax.swing.JTextField();
        MAELevelsTextField10 = new javax.swing.JTextField();
        MAELevelsTextField11 = new javax.swing.JTextField();
        SDevLevelsLabel = new javax.swing.JLabel();
        SDevLevelsTextField1 = new javax.swing.JTextField();
        SDevLevelsTextField2 = new javax.swing.JTextField();
        SDevLevelsTextField3 = new javax.swing.JTextField();
        SDevLevelsTextField4 = new javax.swing.JTextField();
        SDevLevelsTextField5 = new javax.swing.JTextField();
        SDevLevelsTextField6 = new javax.swing.JTextField();
        SDevLevelsTextField7 = new javax.swing.JTextField();
        SDevLevelsTextField8 = new javax.swing.JTextField();
        SDevLevelsTextField9 = new javax.swing.JTextField();
        SDevLevelsTextField10 = new javax.swing.JTextField();
        SDevLevelsTextField11 = new javax.swing.JTextField();
        SDevLevelsTextField12 = new javax.swing.JTextField();
        SDevLevelsTextField13 = new javax.swing.JTextField();
        SaveButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        ResetButton = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Shortwave Radiation Evaluation Plot Options");
        setAlwaysOnTop(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(495, 555));

        RadiationPlotOptionsLabel.setBackground(new java.awt.Color(255, 255, 255));
        RadiationPlotOptionsLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        RadiationPlotOptionsLabel.setForeground(new java.awt.Color(0, 63, 105));
        RadiationPlotOptionsLabel.setText("Shortwave Radiation Evaluation Plot Options");

        DiurnalPlotCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        DiurnalPlotCheckBox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        DiurnalPlotCheckBox.setForeground(new java.awt.Color(0, 112, 185));
        DiurnalPlotCheckBox.setSelected(true);
        DiurnalPlotCheckBox.setText("Diurnal Statistics");

        HistogramPlotCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        HistogramPlotCheckBox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        HistogramPlotCheckBox.setForeground(new java.awt.Color(0, 112, 185));
        HistogramPlotCheckBox.setSelected(true);
        HistogramPlotCheckBox.setText("Histograms (Model, Observation, and Difference)");

        SpatialPlotCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        SpatialPlotCheckBox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        SpatialPlotCheckBox.setForeground(new java.awt.Color(0, 112, 185));
        SpatialPlotCheckBox.setSelected(true);
        SpatialPlotCheckBox.setText("Spatial Statistics");

        TimeSeriesPlotCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        TimeSeriesPlotCheckBox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TimeSeriesPlotCheckBox.setForeground(new java.awt.Color(0, 112, 185));
        TimeSeriesPlotCheckBox.setSelected(true);
        TimeSeriesPlotCheckBox.setText("Time Series");

        SpatialPlotOptionsLabel.setBackground(new java.awt.Color(255, 255, 255));
        SpatialPlotOptionsLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        SpatialPlotOptionsLabel.setForeground(new java.awt.Color(0, 63, 105));
        SpatialPlotOptionsLabel.setText("Spatial Statistical Plot Options");

        SpatialPlotInfoLabel1.setBackground(new java.awt.Color(255, 255, 255));
        SpatialPlotInfoLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        SpatialPlotInfoLabel1.setForeground(new java.awt.Color(0, 112, 185));
        SpatialPlotInfoLabel1.setText("Enter custom latitude and longitude boundaries ");

        SpatialPlotInfoLabel2.setBackground(new java.awt.Color(255, 255, 255));
        SpatialPlotInfoLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        SpatialPlotInfoLabel2.setForeground(new java.awt.Color(0, 112, 185));
        SpatialPlotInfoLabel2.setText("or leave NA to use observation site range.");

        LatSouthLabel.setBackground(new java.awt.Color(255, 255, 255));
        LatSouthLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        LatSouthLabel.setForeground(new java.awt.Color(0, 112, 185));
        LatSouthLabel.setText("Southern Latitude Boundary:");

        LatSouthTextField.setBackground(new java.awt.Color(191, 182, 172));
        LatSouthTextField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        LatSouthTextField.setForeground(new java.awt.Color(0, 63, 105));
        LatSouthTextField.setText("NA");
        LatSouthTextField.setMaximumSize(new java.awt.Dimension(80, 23));
        LatSouthTextField.setMinimumSize(new java.awt.Dimension(80, 23));
        LatSouthTextField.setPreferredSize(new java.awt.Dimension(80, 23));

        LatNorthLabel.setBackground(new java.awt.Color(255, 255, 255));
        LatNorthLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        LatNorthLabel.setForeground(new java.awt.Color(0, 112, 185));
        LatNorthLabel.setText("Northern Latitude Boundary:");

        LatNorthTextField.setBackground(new java.awt.Color(191, 182, 172));
        LatNorthTextField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        LatNorthTextField.setForeground(new java.awt.Color(0, 63, 105));
        LatNorthTextField.setText("NA");
        LatNorthTextField.setMaximumSize(new java.awt.Dimension(178, 23));
        LatNorthTextField.setMinimumSize(new java.awt.Dimension(178, 23));
        LatNorthTextField.setPreferredSize(new java.awt.Dimension(178, 23));

        LonWestLabel.setBackground(new java.awt.Color(255, 255, 255));
        LonWestLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        LonWestLabel.setForeground(new java.awt.Color(0, 112, 185));
        LonWestLabel.setText("Western Longitude Boundary:");

        LonWestTextField.setBackground(new java.awt.Color(191, 182, 172));
        LonWestTextField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        LonWestTextField.setForeground(new java.awt.Color(0, 63, 105));
        LonWestTextField.setText("NA");
        LonWestTextField.setMaximumSize(new java.awt.Dimension(178, 23));
        LonWestTextField.setMinimumSize(new java.awt.Dimension(178, 23));
        LonWestTextField.setPreferredSize(new java.awt.Dimension(178, 23));

        LonEastLabel.setBackground(new java.awt.Color(255, 255, 255));
        LonEastLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        LonEastLabel.setForeground(new java.awt.Color(0, 112, 185));
        LonEastLabel.setText("Eastern Longitude Boundary:");

        LonEastTextField.setBackground(new java.awt.Color(191, 182, 172));
        LonEastTextField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        LonEastTextField.setForeground(new java.awt.Color(0, 63, 105));
        LonEastTextField.setText("NA");
        LonEastTextField.setMaximumSize(new java.awt.Dimension(178, 23));
        LonEastTextField.setMinimumSize(new java.awt.Dimension(178, 23));
        LonEastTextField.setPreferredSize(new java.awt.Dimension(178, 23));

        LevelsLabel.setBackground(new java.awt.Color(255, 255, 255));
        LevelsLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        LevelsLabel.setForeground(new java.awt.Color(0, 63, 105));
        LevelsLabel.setText("Intervals for Shortwave Radiation Statistics");

        LevelsTextArea.setEditable(false);
        LevelsTextArea.setBackground(new java.awt.Color(255, 255, 255));
        LevelsTextArea.setColumns(20);
        LevelsTextArea.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        LevelsTextArea.setForeground(new java.awt.Color(0, 112, 185));
        LevelsTextArea.setLineWrap(true);
        LevelsTextArea.setRows(5);
        LevelsTextArea.setText("Default intervals for statistics can be customized below.");
        LevelsTextArea.setWrapStyleWord(true);
        LevelsTextArea.setAlignmentX(0.0F);
        LevelsTextArea.setAlignmentY(0.0F);
        LevelsTextArea.setMargin(new java.awt.Insets(0, 0, 0, 0));

        BiasLevelsLabel.setBackground(new java.awt.Color(255, 255, 255));
        BiasLevelsLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BiasLevelsLabel.setForeground(new java.awt.Color(0, 112, 185));
        BiasLevelsLabel.setText("<html>Bias (W/m<sup>2</sup>):</html>");

        BiasLevelsTextField1.setBackground(new java.awt.Color(191, 182, 172));
        BiasLevelsTextField1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BiasLevelsTextField1.setForeground(new java.awt.Color(0, 63, 105));
        BiasLevelsTextField1.setText("-300");
        BiasLevelsTextField1.setMaximumSize(new java.awt.Dimension(178, 23));
        BiasLevelsTextField1.setMinimumSize(new java.awt.Dimension(178, 23));
        BiasLevelsTextField1.setPreferredSize(new java.awt.Dimension(178, 23));

        BiasLevelsTextField2.setBackground(new java.awt.Color(191, 182, 172));
        BiasLevelsTextField2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BiasLevelsTextField2.setForeground(new java.awt.Color(0, 63, 105));
        BiasLevelsTextField2.setText("-150");
        BiasLevelsTextField2.setMaximumSize(new java.awt.Dimension(178, 23));
        BiasLevelsTextField2.setMinimumSize(new java.awt.Dimension(178, 23));
        BiasLevelsTextField2.setPreferredSize(new java.awt.Dimension(178, 23));

        BiasLevelsTextField3.setBackground(new java.awt.Color(191, 182, 172));
        BiasLevelsTextField3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BiasLevelsTextField3.setForeground(new java.awt.Color(0, 63, 105));
        BiasLevelsTextField3.setText("-100");
        BiasLevelsTextField3.setMaximumSize(new java.awt.Dimension(178, 23));
        BiasLevelsTextField3.setMinimumSize(new java.awt.Dimension(178, 23));
        BiasLevelsTextField3.setPreferredSize(new java.awt.Dimension(178, 23));

        BiasLevelsTextField4.setBackground(new java.awt.Color(191, 182, 172));
        BiasLevelsTextField4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BiasLevelsTextField4.setForeground(new java.awt.Color(0, 63, 105));
        BiasLevelsTextField4.setText("-75");
        BiasLevelsTextField4.setMaximumSize(new java.awt.Dimension(178, 23));
        BiasLevelsTextField4.setMinimumSize(new java.awt.Dimension(178, 23));
        BiasLevelsTextField4.setPreferredSize(new java.awt.Dimension(178, 23));

        BiasLevelsTextField5.setBackground(new java.awt.Color(191, 182, 172));
        BiasLevelsTextField5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BiasLevelsTextField5.setForeground(new java.awt.Color(0, 63, 105));
        BiasLevelsTextField5.setText("-40");
        BiasLevelsTextField5.setMaximumSize(new java.awt.Dimension(178, 23));
        BiasLevelsTextField5.setMinimumSize(new java.awt.Dimension(178, 23));
        BiasLevelsTextField5.setPreferredSize(new java.awt.Dimension(178, 23));

        BiasLevelsTextField6.setBackground(new java.awt.Color(191, 182, 172));
        BiasLevelsTextField6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BiasLevelsTextField6.setForeground(new java.awt.Color(0, 63, 105));
        BiasLevelsTextField6.setText("-20");
        BiasLevelsTextField6.setMaximumSize(new java.awt.Dimension(178, 23));
        BiasLevelsTextField6.setMinimumSize(new java.awt.Dimension(178, 23));
        BiasLevelsTextField6.setPreferredSize(new java.awt.Dimension(178, 23));

        BiasLevelsTextField7.setBackground(new java.awt.Color(191, 182, 172));
        BiasLevelsTextField7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BiasLevelsTextField7.setForeground(new java.awt.Color(0, 63, 105));
        BiasLevelsTextField7.setText("-10");
        BiasLevelsTextField7.setMaximumSize(new java.awt.Dimension(178, 23));
        BiasLevelsTextField7.setMinimumSize(new java.awt.Dimension(178, 23));
        BiasLevelsTextField7.setPreferredSize(new java.awt.Dimension(178, 23));

        BiasLevelsTextField8.setBackground(new java.awt.Color(191, 182, 172));
        BiasLevelsTextField8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BiasLevelsTextField8.setForeground(new java.awt.Color(0, 63, 105));
        BiasLevelsTextField8.setText("0");
        BiasLevelsTextField8.setMaximumSize(new java.awt.Dimension(178, 23));
        BiasLevelsTextField8.setMinimumSize(new java.awt.Dimension(178, 23));
        BiasLevelsTextField8.setPreferredSize(new java.awt.Dimension(178, 23));

        BiasLevelsTextField9.setBackground(new java.awt.Color(191, 182, 172));
        BiasLevelsTextField9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BiasLevelsTextField9.setForeground(new java.awt.Color(0, 63, 105));
        BiasLevelsTextField9.setText("10");
        BiasLevelsTextField9.setMaximumSize(new java.awt.Dimension(178, 23));
        BiasLevelsTextField9.setMinimumSize(new java.awt.Dimension(178, 23));
        BiasLevelsTextField9.setPreferredSize(new java.awt.Dimension(178, 23));

        BiasLevelsTextField10.setBackground(new java.awt.Color(191, 182, 172));
        BiasLevelsTextField10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BiasLevelsTextField10.setForeground(new java.awt.Color(0, 63, 105));
        BiasLevelsTextField10.setText("20");
        BiasLevelsTextField10.setMaximumSize(new java.awt.Dimension(178, 23));
        BiasLevelsTextField10.setMinimumSize(new java.awt.Dimension(178, 23));
        BiasLevelsTextField10.setPreferredSize(new java.awt.Dimension(178, 23));

        BiasLevelsTextField11.setBackground(new java.awt.Color(191, 182, 172));
        BiasLevelsTextField11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BiasLevelsTextField11.setForeground(new java.awt.Color(0, 63, 105));
        BiasLevelsTextField11.setText("40");
        BiasLevelsTextField11.setMaximumSize(new java.awt.Dimension(178, 23));
        BiasLevelsTextField11.setMinimumSize(new java.awt.Dimension(178, 23));
        BiasLevelsTextField11.setPreferredSize(new java.awt.Dimension(178, 23));

        BiasLevelsTextField12.setBackground(new java.awt.Color(191, 182, 172));
        BiasLevelsTextField12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BiasLevelsTextField12.setForeground(new java.awt.Color(0, 63, 105));
        BiasLevelsTextField12.setText("75");
        BiasLevelsTextField12.setMaximumSize(new java.awt.Dimension(178, 23));
        BiasLevelsTextField12.setMinimumSize(new java.awt.Dimension(178, 23));
        BiasLevelsTextField12.setPreferredSize(new java.awt.Dimension(178, 23));

        BiasLevelsTextField13.setBackground(new java.awt.Color(191, 182, 172));
        BiasLevelsTextField13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BiasLevelsTextField13.setForeground(new java.awt.Color(0, 63, 105));
        BiasLevelsTextField13.setText("100");
        BiasLevelsTextField13.setMaximumSize(new java.awt.Dimension(178, 23));
        BiasLevelsTextField13.setMinimumSize(new java.awt.Dimension(178, 23));
        BiasLevelsTextField13.setPreferredSize(new java.awt.Dimension(178, 23));

        BiasLevelsTextField14.setBackground(new java.awt.Color(191, 182, 172));
        BiasLevelsTextField14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BiasLevelsTextField14.setForeground(new java.awt.Color(0, 63, 105));
        BiasLevelsTextField14.setText("150");
        BiasLevelsTextField14.setMaximumSize(new java.awt.Dimension(178, 23));
        BiasLevelsTextField14.setMinimumSize(new java.awt.Dimension(178, 23));
        BiasLevelsTextField14.setPreferredSize(new java.awt.Dimension(178, 23));

        BiasLevelsTextField15.setBackground(new java.awt.Color(191, 182, 172));
        BiasLevelsTextField15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BiasLevelsTextField15.setForeground(new java.awt.Color(0, 63, 105));
        BiasLevelsTextField15.setText("300");
        BiasLevelsTextField15.setMaximumSize(new java.awt.Dimension(178, 23));
        BiasLevelsTextField15.setMinimumSize(new java.awt.Dimension(178, 23));
        BiasLevelsTextField15.setPreferredSize(new java.awt.Dimension(178, 23));

        RMSELevelsLabel.setBackground(new java.awt.Color(255, 255, 255));
        RMSELevelsLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        RMSELevelsLabel.setForeground(new java.awt.Color(0, 112, 185));
        RMSELevelsLabel.setText("<html>RMSE (W/m<sup>2</sup>):</html>");

        RMSELevelsTextField1.setBackground(new java.awt.Color(191, 182, 172));
        RMSELevelsTextField1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        RMSELevelsTextField1.setForeground(new java.awt.Color(0, 63, 105));
        RMSELevelsTextField1.setText("0");
        RMSELevelsTextField1.setMaximumSize(new java.awt.Dimension(178, 23));
        RMSELevelsTextField1.setMinimumSize(new java.awt.Dimension(178, 23));
        RMSELevelsTextField1.setPreferredSize(new java.awt.Dimension(178, 23));

        RMSELevelsTextField2.setBackground(new java.awt.Color(191, 182, 172));
        RMSELevelsTextField2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        RMSELevelsTextField2.setForeground(new java.awt.Color(0, 63, 105));
        RMSELevelsTextField2.setText("25");
        RMSELevelsTextField2.setMaximumSize(new java.awt.Dimension(178, 23));
        RMSELevelsTextField2.setMinimumSize(new java.awt.Dimension(178, 23));
        RMSELevelsTextField2.setPreferredSize(new java.awt.Dimension(178, 23));

        RMSELevelsTextField3.setBackground(new java.awt.Color(191, 182, 172));
        RMSELevelsTextField3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        RMSELevelsTextField3.setForeground(new java.awt.Color(0, 63, 105));
        RMSELevelsTextField3.setText("50");
        RMSELevelsTextField3.setMaximumSize(new java.awt.Dimension(178, 23));
        RMSELevelsTextField3.setMinimumSize(new java.awt.Dimension(178, 23));
        RMSELevelsTextField3.setPreferredSize(new java.awt.Dimension(178, 23));

        RMSELevelsTextField4.setBackground(new java.awt.Color(191, 182, 172));
        RMSELevelsTextField4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        RMSELevelsTextField4.setForeground(new java.awt.Color(0, 63, 105));
        RMSELevelsTextField4.setText("75");
        RMSELevelsTextField4.setMaximumSize(new java.awt.Dimension(178, 23));
        RMSELevelsTextField4.setMinimumSize(new java.awt.Dimension(178, 23));
        RMSELevelsTextField4.setPreferredSize(new java.awt.Dimension(178, 23));

        RMSELevelsTextField5.setBackground(new java.awt.Color(191, 182, 172));
        RMSELevelsTextField5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        RMSELevelsTextField5.setForeground(new java.awt.Color(0, 63, 105));
        RMSELevelsTextField5.setText("100");
        RMSELevelsTextField5.setMaximumSize(new java.awt.Dimension(178, 23));
        RMSELevelsTextField5.setMinimumSize(new java.awt.Dimension(178, 23));
        RMSELevelsTextField5.setPreferredSize(new java.awt.Dimension(178, 23));

        RMSELevelsTextField6.setBackground(new java.awt.Color(191, 182, 172));
        RMSELevelsTextField6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        RMSELevelsTextField6.setForeground(new java.awt.Color(0, 63, 105));
        RMSELevelsTextField6.setText("125");
        RMSELevelsTextField6.setMaximumSize(new java.awt.Dimension(178, 23));
        RMSELevelsTextField6.setMinimumSize(new java.awt.Dimension(178, 23));
        RMSELevelsTextField6.setPreferredSize(new java.awt.Dimension(178, 23));

        RMSELevelsTextField7.setBackground(new java.awt.Color(191, 182, 172));
        RMSELevelsTextField7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        RMSELevelsTextField7.setForeground(new java.awt.Color(0, 63, 105));
        RMSELevelsTextField7.setText("150");
        RMSELevelsTextField7.setMaximumSize(new java.awt.Dimension(178, 23));
        RMSELevelsTextField7.setMinimumSize(new java.awt.Dimension(178, 23));
        RMSELevelsTextField7.setPreferredSize(new java.awt.Dimension(178, 23));

        RMSELevelsTextField8.setBackground(new java.awt.Color(191, 182, 172));
        RMSELevelsTextField8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        RMSELevelsTextField8.setForeground(new java.awt.Color(0, 63, 105));
        RMSELevelsTextField8.setText("175");
        RMSELevelsTextField8.setMaximumSize(new java.awt.Dimension(178, 23));
        RMSELevelsTextField8.setMinimumSize(new java.awt.Dimension(178, 23));
        RMSELevelsTextField8.setPreferredSize(new java.awt.Dimension(178, 23));

        RMSELevelsTextField9.setBackground(new java.awt.Color(191, 182, 172));
        RMSELevelsTextField9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        RMSELevelsTextField9.setForeground(new java.awt.Color(0, 63, 105));
        RMSELevelsTextField9.setText("200");
        RMSELevelsTextField9.setMaximumSize(new java.awt.Dimension(178, 23));
        RMSELevelsTextField9.setMinimumSize(new java.awt.Dimension(178, 23));
        RMSELevelsTextField9.setPreferredSize(new java.awt.Dimension(178, 23));

        RMSELevelsTextField10.setBackground(new java.awt.Color(191, 182, 172));
        RMSELevelsTextField10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        RMSELevelsTextField10.setForeground(new java.awt.Color(0, 63, 105));
        RMSELevelsTextField10.setText("250");
        RMSELevelsTextField10.setMaximumSize(new java.awt.Dimension(178, 23));
        RMSELevelsTextField10.setMinimumSize(new java.awt.Dimension(178, 23));
        RMSELevelsTextField10.setPreferredSize(new java.awt.Dimension(178, 23));

        RMSELevelsTextField11.setBackground(new java.awt.Color(191, 182, 172));
        RMSELevelsTextField11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        RMSELevelsTextField11.setForeground(new java.awt.Color(0, 63, 105));
        RMSELevelsTextField11.setText("300");
        RMSELevelsTextField11.setMaximumSize(new java.awt.Dimension(178, 23));
        RMSELevelsTextField11.setMinimumSize(new java.awt.Dimension(178, 23));
        RMSELevelsTextField11.setPreferredSize(new java.awt.Dimension(178, 23));

        RMSELevelsTextField12.setBackground(new java.awt.Color(191, 182, 172));
        RMSELevelsTextField12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        RMSELevelsTextField12.setForeground(new java.awt.Color(0, 63, 105));
        RMSELevelsTextField12.setText("400");
        RMSELevelsTextField12.setMaximumSize(new java.awt.Dimension(178, 23));
        RMSELevelsTextField12.setMinimumSize(new java.awt.Dimension(178, 23));
        RMSELevelsTextField12.setPreferredSize(new java.awt.Dimension(178, 23));

        RMSELevelsTextField13.setBackground(new java.awt.Color(191, 182, 172));
        RMSELevelsTextField13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        RMSELevelsTextField13.setForeground(new java.awt.Color(0, 63, 105));
        RMSELevelsTextField13.setText("500");
        RMSELevelsTextField13.setMaximumSize(new java.awt.Dimension(178, 23));
        RMSELevelsTextField13.setMinimumSize(new java.awt.Dimension(178, 23));
        RMSELevelsTextField13.setPreferredSize(new java.awt.Dimension(178, 23));

        MAELevelsLabel.setBackground(new java.awt.Color(255, 255, 255));
        MAELevelsLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        MAELevelsLabel.setForeground(new java.awt.Color(0, 112, 185));
        MAELevelsLabel.setText("<html>Mean Absolute Error (W/m<sup>2</sup>):</html>");
        MAELevelsLabel.setToolTipText("");

        MAELevelsTextField1.setBackground(new java.awt.Color(191, 182, 172));
        MAELevelsTextField1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        MAELevelsTextField1.setForeground(new java.awt.Color(0, 63, 105));
        MAELevelsTextField1.setText("0");
        MAELevelsTextField1.setMaximumSize(new java.awt.Dimension(178, 23));
        MAELevelsTextField1.setMinimumSize(new java.awt.Dimension(178, 23));
        MAELevelsTextField1.setPreferredSize(new java.awt.Dimension(178, 23));

        MAELevelsTextField2.setBackground(new java.awt.Color(191, 182, 172));
        MAELevelsTextField2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        MAELevelsTextField2.setForeground(new java.awt.Color(0, 63, 105));
        MAELevelsTextField2.setText("25");
        MAELevelsTextField2.setMaximumSize(new java.awt.Dimension(178, 23));
        MAELevelsTextField2.setMinimumSize(new java.awt.Dimension(178, 23));
        MAELevelsTextField2.setPreferredSize(new java.awt.Dimension(178, 23));

        MAELevelsTextField3.setBackground(new java.awt.Color(191, 182, 172));
        MAELevelsTextField3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        MAELevelsTextField3.setForeground(new java.awt.Color(0, 63, 105));
        MAELevelsTextField3.setText("50");
        MAELevelsTextField3.setMaximumSize(new java.awt.Dimension(178, 23));
        MAELevelsTextField3.setMinimumSize(new java.awt.Dimension(178, 23));
        MAELevelsTextField3.setPreferredSize(new java.awt.Dimension(178, 23));

        MAELevelsTextField4.setBackground(new java.awt.Color(191, 182, 172));
        MAELevelsTextField4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        MAELevelsTextField4.setForeground(new java.awt.Color(0, 63, 105));
        MAELevelsTextField4.setText("75");
        MAELevelsTextField4.setMaximumSize(new java.awt.Dimension(178, 23));
        MAELevelsTextField4.setMinimumSize(new java.awt.Dimension(178, 23));
        MAELevelsTextField4.setPreferredSize(new java.awt.Dimension(178, 23));

        MAELevelsTextField5.setBackground(new java.awt.Color(191, 182, 172));
        MAELevelsTextField5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        MAELevelsTextField5.setForeground(new java.awt.Color(0, 63, 105));
        MAELevelsTextField5.setText("100");
        MAELevelsTextField5.setMaximumSize(new java.awt.Dimension(178, 23));
        MAELevelsTextField5.setMinimumSize(new java.awt.Dimension(178, 23));
        MAELevelsTextField5.setPreferredSize(new java.awt.Dimension(178, 23));

        MAELevelsTextField6.setBackground(new java.awt.Color(191, 182, 172));
        MAELevelsTextField6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        MAELevelsTextField6.setForeground(new java.awt.Color(0, 63, 105));
        MAELevelsTextField6.setText("125");
        MAELevelsTextField6.setMaximumSize(new java.awt.Dimension(178, 23));
        MAELevelsTextField6.setMinimumSize(new java.awt.Dimension(178, 23));
        MAELevelsTextField6.setPreferredSize(new java.awt.Dimension(178, 23));

        MAELevelsTextField7.setBackground(new java.awt.Color(191, 182, 172));
        MAELevelsTextField7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        MAELevelsTextField7.setForeground(new java.awt.Color(0, 63, 105));
        MAELevelsTextField7.setText("150");
        MAELevelsTextField7.setMaximumSize(new java.awt.Dimension(178, 23));
        MAELevelsTextField7.setMinimumSize(new java.awt.Dimension(178, 23));
        MAELevelsTextField7.setPreferredSize(new java.awt.Dimension(178, 23));

        MAELevelsTextField8.setBackground(new java.awt.Color(191, 182, 172));
        MAELevelsTextField8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        MAELevelsTextField8.setForeground(new java.awt.Color(0, 63, 105));
        MAELevelsTextField8.setText("175");
        MAELevelsTextField8.setMaximumSize(new java.awt.Dimension(178, 23));
        MAELevelsTextField8.setMinimumSize(new java.awt.Dimension(178, 23));
        MAELevelsTextField8.setPreferredSize(new java.awt.Dimension(178, 23));

        MAELevelsTextField9.setBackground(new java.awt.Color(191, 182, 172));
        MAELevelsTextField9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        MAELevelsTextField9.setForeground(new java.awt.Color(0, 63, 105));
        MAELevelsTextField9.setText("200");
        MAELevelsTextField9.setMaximumSize(new java.awt.Dimension(178, 23));
        MAELevelsTextField9.setMinimumSize(new java.awt.Dimension(178, 23));
        MAELevelsTextField9.setPreferredSize(new java.awt.Dimension(178, 23));

        MAELevelsTextField10.setBackground(new java.awt.Color(191, 182, 172));
        MAELevelsTextField10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        MAELevelsTextField10.setForeground(new java.awt.Color(0, 63, 105));
        MAELevelsTextField10.setText("250");
        MAELevelsTextField10.setMaximumSize(new java.awt.Dimension(178, 23));
        MAELevelsTextField10.setMinimumSize(new java.awt.Dimension(178, 23));
        MAELevelsTextField10.setPreferredSize(new java.awt.Dimension(178, 23));

        MAELevelsTextField11.setBackground(new java.awt.Color(191, 182, 172));
        MAELevelsTextField11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        MAELevelsTextField11.setForeground(new java.awt.Color(0, 63, 105));
        MAELevelsTextField11.setText("300");
        MAELevelsTextField11.setMaximumSize(new java.awt.Dimension(178, 23));
        MAELevelsTextField11.setMinimumSize(new java.awt.Dimension(178, 23));
        MAELevelsTextField11.setPreferredSize(new java.awt.Dimension(178, 23));

        SDevLevelsLabel.setBackground(new java.awt.Color(255, 255, 255));
        SDevLevelsLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        SDevLevelsLabel.setForeground(new java.awt.Color(0, 112, 185));
        SDevLevelsLabel.setText("<html>Standard Deviation Difference (W/m<sup>2</sup>):</html>");

        SDevLevelsTextField1.setBackground(new java.awt.Color(191, 182, 172));
        SDevLevelsTextField1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        SDevLevelsTextField1.setForeground(new java.awt.Color(0, 63, 105));
        SDevLevelsTextField1.setText("-150");
        SDevLevelsTextField1.setMaximumSize(new java.awt.Dimension(178, 23));
        SDevLevelsTextField1.setMinimumSize(new java.awt.Dimension(178, 23));
        SDevLevelsTextField1.setPreferredSize(new java.awt.Dimension(178, 23));

        SDevLevelsTextField2.setBackground(new java.awt.Color(191, 182, 172));
        SDevLevelsTextField2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        SDevLevelsTextField2.setForeground(new java.awt.Color(0, 63, 105));
        SDevLevelsTextField2.setText("-100");
        SDevLevelsTextField2.setMaximumSize(new java.awt.Dimension(178, 23));
        SDevLevelsTextField2.setMinimumSize(new java.awt.Dimension(178, 23));
        SDevLevelsTextField2.setPreferredSize(new java.awt.Dimension(178, 23));

        SDevLevelsTextField3.setBackground(new java.awt.Color(191, 182, 172));
        SDevLevelsTextField3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        SDevLevelsTextField3.setForeground(new java.awt.Color(0, 63, 105));
        SDevLevelsTextField3.setText("-75");
        SDevLevelsTextField3.setMaximumSize(new java.awt.Dimension(178, 23));
        SDevLevelsTextField3.setMinimumSize(new java.awt.Dimension(178, 23));
        SDevLevelsTextField3.setPreferredSize(new java.awt.Dimension(178, 23));

        SDevLevelsTextField4.setBackground(new java.awt.Color(191, 182, 172));
        SDevLevelsTextField4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        SDevLevelsTextField4.setForeground(new java.awt.Color(0, 63, 105));
        SDevLevelsTextField4.setText("-40");
        SDevLevelsTextField4.setMaximumSize(new java.awt.Dimension(178, 23));
        SDevLevelsTextField4.setMinimumSize(new java.awt.Dimension(178, 23));
        SDevLevelsTextField4.setPreferredSize(new java.awt.Dimension(178, 23));

        SDevLevelsTextField5.setBackground(new java.awt.Color(191, 182, 172));
        SDevLevelsTextField5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        SDevLevelsTextField5.setForeground(new java.awt.Color(0, 63, 105));
        SDevLevelsTextField5.setText("-20");
        SDevLevelsTextField5.setMaximumSize(new java.awt.Dimension(178, 23));
        SDevLevelsTextField5.setMinimumSize(new java.awt.Dimension(178, 23));
        SDevLevelsTextField5.setPreferredSize(new java.awt.Dimension(178, 23));

        SDevLevelsTextField6.setBackground(new java.awt.Color(191, 182, 172));
        SDevLevelsTextField6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        SDevLevelsTextField6.setForeground(new java.awt.Color(0, 63, 105));
        SDevLevelsTextField6.setText("-10");
        SDevLevelsTextField6.setMaximumSize(new java.awt.Dimension(178, 23));
        SDevLevelsTextField6.setMinimumSize(new java.awt.Dimension(178, 23));
        SDevLevelsTextField6.setPreferredSize(new java.awt.Dimension(178, 23));

        SDevLevelsTextField7.setBackground(new java.awt.Color(191, 182, 172));
        SDevLevelsTextField7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        SDevLevelsTextField7.setForeground(new java.awt.Color(0, 63, 105));
        SDevLevelsTextField7.setText("0");
        SDevLevelsTextField7.setMaximumSize(new java.awt.Dimension(178, 23));
        SDevLevelsTextField7.setMinimumSize(new java.awt.Dimension(178, 23));
        SDevLevelsTextField7.setPreferredSize(new java.awt.Dimension(178, 23));

        SDevLevelsTextField8.setBackground(new java.awt.Color(191, 182, 172));
        SDevLevelsTextField8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        SDevLevelsTextField8.setForeground(new java.awt.Color(0, 63, 105));
        SDevLevelsTextField8.setText("10");
        SDevLevelsTextField8.setMaximumSize(new java.awt.Dimension(178, 23));
        SDevLevelsTextField8.setMinimumSize(new java.awt.Dimension(178, 23));
        SDevLevelsTextField8.setPreferredSize(new java.awt.Dimension(178, 23));

        SDevLevelsTextField9.setBackground(new java.awt.Color(191, 182, 172));
        SDevLevelsTextField9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        SDevLevelsTextField9.setForeground(new java.awt.Color(0, 63, 105));
        SDevLevelsTextField9.setText("20");
        SDevLevelsTextField9.setMaximumSize(new java.awt.Dimension(178, 23));
        SDevLevelsTextField9.setMinimumSize(new java.awt.Dimension(178, 23));
        SDevLevelsTextField9.setPreferredSize(new java.awt.Dimension(178, 23));

        SDevLevelsTextField10.setBackground(new java.awt.Color(191, 182, 172));
        SDevLevelsTextField10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        SDevLevelsTextField10.setForeground(new java.awt.Color(0, 63, 105));
        SDevLevelsTextField10.setText("40");
        SDevLevelsTextField10.setMaximumSize(new java.awt.Dimension(178, 23));
        SDevLevelsTextField10.setMinimumSize(new java.awt.Dimension(178, 23));
        SDevLevelsTextField10.setPreferredSize(new java.awt.Dimension(178, 23));

        SDevLevelsTextField11.setBackground(new java.awt.Color(191, 182, 172));
        SDevLevelsTextField11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        SDevLevelsTextField11.setForeground(new java.awt.Color(0, 63, 105));
        SDevLevelsTextField11.setText("75");
        SDevLevelsTextField11.setMaximumSize(new java.awt.Dimension(178, 23));
        SDevLevelsTextField11.setMinimumSize(new java.awt.Dimension(178, 23));
        SDevLevelsTextField11.setPreferredSize(new java.awt.Dimension(178, 23));

        SDevLevelsTextField12.setBackground(new java.awt.Color(191, 182, 172));
        SDevLevelsTextField12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        SDevLevelsTextField12.setForeground(new java.awt.Color(0, 63, 105));
        SDevLevelsTextField12.setText("100");
        SDevLevelsTextField12.setMaximumSize(new java.awt.Dimension(178, 23));
        SDevLevelsTextField12.setMinimumSize(new java.awt.Dimension(178, 23));
        SDevLevelsTextField12.setPreferredSize(new java.awt.Dimension(178, 23));

        SDevLevelsTextField13.setBackground(new java.awt.Color(191, 182, 172));
        SDevLevelsTextField13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        SDevLevelsTextField13.setForeground(new java.awt.Color(0, 63, 105));
        SDevLevelsTextField13.setText("150");
        SDevLevelsTextField13.setMaximumSize(new java.awt.Dimension(178, 23));
        SDevLevelsTextField13.setMinimumSize(new java.awt.Dimension(178, 23));
        SDevLevelsTextField13.setPreferredSize(new java.awt.Dimension(178, 23));

        SaveButton.setBackground(new java.awt.Color(0, 63, 105));
        SaveButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        SaveButton.setForeground(new java.awt.Color(191, 182, 172));
        SaveButton.setText("Save");
        SaveButton.setMaximumSize(new java.awt.Dimension(100, 26));
        SaveButton.setMinimumSize(new java.awt.Dimension(75, 26));
        SaveButton.setPreferredSize(new java.awt.Dimension(75, 26));
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        CancelButton.setBackground(new java.awt.Color(0, 63, 105));
        CancelButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        CancelButton.setForeground(new java.awt.Color(191, 182, 172));
        CancelButton.setText("Cancel");
        CancelButton.setMaximumSize(new java.awt.Dimension(100, 26));
        CancelButton.setMinimumSize(new java.awt.Dimension(90, 26));
        CancelButton.setPreferredSize(new java.awt.Dimension(90, 26));
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        ResetButton.setBackground(new java.awt.Color(0, 63, 105));
        ResetButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ResetButton.setForeground(new java.awt.Color(191, 182, 172));
        ResetButton.setText("Reset");
        ResetButton.setMaximumSize(new java.awt.Dimension(100, 26));
        ResetButton.setMinimumSize(new java.awt.Dimension(100, 26));
        ResetButton.setPreferredSize(new java.awt.Dimension(80, 26));
        ResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BiasLevelsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(LevelsTextArea)
                        .addComponent(LevelsLabel)
                        .addComponent(SpatialPlotOptionsLabel)
                        .addComponent(DiurnalPlotCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(RadiationPlotOptionsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(HistogramPlotCheckBox)
                        .addComponent(SpatialPlotCheckBox)
                        .addComponent(TimeSeriesPlotCheckBox)
                        .addComponent(SpatialPlotInfoLabel2)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(LonWestLabel)
                                .addComponent(LatNorthLabel)
                                .addComponent(LatSouthLabel)
                                .addComponent(LonEastLabel))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(LatNorthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(LonWestTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(LonEastTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(LatSouthTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(SpatialPlotInfoLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BiasLevelsTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BiasLevelsTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BiasLevelsTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BiasLevelsTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BiasLevelsTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BiasLevelsTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BiasLevelsTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(RMSELevelsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(RMSELevelsTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RMSELevelsTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RMSELevelsTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RMSELevelsTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RMSELevelsTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RMSELevelsTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RMSELevelsTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(RMSELevelsTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RMSELevelsTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RMSELevelsTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RMSELevelsTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RMSELevelsTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RMSELevelsTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(MAELevelsTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MAELevelsTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MAELevelsTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MAELevelsTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MAELevelsTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(MAELevelsTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MAELevelsTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MAELevelsTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MAELevelsTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MAELevelsTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MAELevelsTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(MAELevelsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(SDevLevelsTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SDevLevelsTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SDevLevelsTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SDevLevelsTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SDevLevelsTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SDevLevelsTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SDevLevelsTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(SDevLevelsTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SDevLevelsTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SDevLevelsTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SDevLevelsTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SDevLevelsTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SDevLevelsTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(SDevLevelsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(ResetButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(40, 40, 40)
                            .addComponent(CancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(BiasLevelsTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(BiasLevelsTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(BiasLevelsTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(BiasLevelsTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(BiasLevelsTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(BiasLevelsTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(BiasLevelsTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(BiasLevelsTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RadiationPlotOptionsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DiurnalPlotCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(HistogramPlotCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SpatialPlotCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TimeSeriesPlotCheckBox)
                .addGap(18, 18, 18)
                .addComponent(SpatialPlotOptionsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SpatialPlotInfoLabel1)
                .addGap(0, 0, 0)
                .addComponent(SpatialPlotInfoLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LatSouthLabel)
                    .addComponent(LatSouthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LatNorthLabel)
                    .addComponent(LatNorthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LonWestLabel)
                    .addComponent(LonWestTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LonEastLabel)
                    .addComponent(LonEastTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(LevelsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LevelsTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BiasLevelsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BiasLevelsTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BiasLevelsTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BiasLevelsTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BiasLevelsTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BiasLevelsTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BiasLevelsTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BiasLevelsTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BiasLevelsTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BiasLevelsTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BiasLevelsTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BiasLevelsTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BiasLevelsTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BiasLevelsTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BiasLevelsTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BiasLevelsTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RMSELevelsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RMSELevelsTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RMSELevelsTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RMSELevelsTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RMSELevelsTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RMSELevelsTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RMSELevelsTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RMSELevelsTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RMSELevelsTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RMSELevelsTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RMSELevelsTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RMSELevelsTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RMSELevelsTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RMSELevelsTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MAELevelsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MAELevelsTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MAELevelsTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MAELevelsTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MAELevelsTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MAELevelsTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MAELevelsTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MAELevelsTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MAELevelsTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MAELevelsTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MAELevelsTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MAELevelsTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SDevLevelsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SDevLevelsTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SDevLevelsTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SDevLevelsTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SDevLevelsTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SDevLevelsTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SDevLevelsTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SDevLevelsTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SDevLevelsTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SDevLevelsTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SDevLevelsTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SDevLevelsTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SDevLevelsTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SDevLevelsTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ResetButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 910, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed

        form.diurnal = form.checkBoxFormat(DiurnalPlotCheckBox);
        form.diurnal_rad = DiurnalPlotCheckBox.isSelected();
        form.histogram = form.checkBoxFormat(HistogramPlotCheckBox);
        form.histogram_rad = HistogramPlotCheckBox.isSelected();
        form.spatial = form.checkBoxFormat(SpatialPlotCheckBox);
        form.spatial_rad = SpatialPlotCheckBox.isSelected();
        form.time_series = form.checkBoxFormat(TimeSeriesPlotCheckBox);
        form.time_series_rad = TimeSeriesPlotCheckBox.isSelected();
        form.lat_south = LatSouthTextField.getText();
        form.lat_north = LatNorthTextField.getText();
        form.lon_west = LonWestTextField.getText();
        form.lon_east = LonEastTextField.getText();
        form.bias_level1 = form.numNullFormat(BiasLevelsTextField1.getText());
        form.bias_level2 = form.numNullFormat(BiasLevelsTextField2.getText());
        form.bias_level3 = form.numNullFormat(BiasLevelsTextField3.getText());
        form.bias_level4 = form.numNullFormat(BiasLevelsTextField4.getText());
        form.bias_level5 = form.numNullFormat(BiasLevelsTextField5.getText());
        form.bias_level6 = form.numNullFormat(BiasLevelsTextField6.getText());
        form.bias_level7 = form.numNullFormat(BiasLevelsTextField7.getText());
        form.bias_level8 = form.numNullFormat(BiasLevelsTextField8.getText());
        form.bias_level9 = form.numNullFormat(BiasLevelsTextField9.getText());
        form.bias_level10 = form.numNullFormat(BiasLevelsTextField10.getText());
        form.bias_level11 = form.numNullFormat(BiasLevelsTextField11.getText());
        form.bias_level12 = form.numNullFormat(BiasLevelsTextField12.getText());
        form.bias_level13 = form.numNullFormat(BiasLevelsTextField13.getText());
        form.bias_level14 = form.numNullFormat(BiasLevelsTextField14.getText());
        form.bias_level15 = form.numNullFormat(BiasLevelsTextField15.getText());
        form.rmse_level1 = form.numNullFormat(RMSELevelsTextField1.getText());
        form.rmse_level2 = form.numNullFormat(RMSELevelsTextField2.getText());
        form.rmse_level3 = form.numNullFormat(RMSELevelsTextField3.getText());
        form.rmse_level4 = form.numNullFormat(RMSELevelsTextField4.getText());
        form.rmse_level5 = form.numNullFormat(RMSELevelsTextField5.getText());
        form.rmse_level6 = form.numNullFormat(RMSELevelsTextField6.getText());
        form.rmse_level7 = form.numNullFormat(RMSELevelsTextField7.getText());
        form.rmse_level8 = form.numNullFormat(RMSELevelsTextField8.getText());
        form.rmse_level9 = form.numNullFormat(RMSELevelsTextField9.getText());
        form.rmse_level10 = form.numNullFormat(RMSELevelsTextField10.getText());
        form.rmse_level11 = form.numNullFormat(RMSELevelsTextField11.getText());
        form.rmse_level12 = form.numNullFormat(RMSELevelsTextField12.getText());
        form.rmse_level13 = form.numNullFormat(RMSELevelsTextField13.getText());
        form.mae_level1 = form.numNullFormat(MAELevelsTextField1.getText());
        form.mae_level2 = form.numNullFormat(MAELevelsTextField2.getText());
        form.mae_level3 = form.numNullFormat(MAELevelsTextField3.getText());
        form.mae_level4 = form.numNullFormat(MAELevelsTextField4.getText());
        form.mae_level5 = form.numNullFormat(MAELevelsTextField5.getText());
        form.mae_level6 = form.numNullFormat(MAELevelsTextField6.getText());
        form.mae_level7 = form.numNullFormat(MAELevelsTextField7.getText());
        form.mae_level8 = form.numNullFormat(MAELevelsTextField8.getText());
        form.mae_level9 = form.numNullFormat(MAELevelsTextField9.getText());
        form.mae_level10 = form.numNullFormat(MAELevelsTextField10.getText());
        form.mae_level11 = form.numNullFormat(MAELevelsTextField11.getText());
        form.sdev_level1 = form.numNullFormat(SDevLevelsTextField1.getText());
        form.sdev_level2 = form.numNullFormat(SDevLevelsTextField2.getText());
        form.sdev_level3 = form.numNullFormat(SDevLevelsTextField3.getText());
        form.sdev_level4 = form.numNullFormat(SDevLevelsTextField4.getText());
        form.sdev_level5 = form.numNullFormat(SDevLevelsTextField5.getText());
        form.sdev_level6 = form.numNullFormat(SDevLevelsTextField6.getText());
        form.sdev_level7 = form.numNullFormat(SDevLevelsTextField7.getText());
        form.sdev_level8 = form.numNullFormat(SDevLevelsTextField8.getText());
        form.sdev_level9 = form.numNullFormat(SDevLevelsTextField9.getText());
        form.sdev_level10 = form.numNullFormat(SDevLevelsTextField10.getText());
        form.sdev_level11 = form.numNullFormat(SDevLevelsTextField11.getText());
        form.sdev_level12 = form.numNullFormat(SDevLevelsTextField12.getText());
        form.sdev_level13 = form.numNullFormat(SDevLevelsTextField13.getText());
        System.out.println("Shortwave Radiation Analysis Options Saved");
        setVisible(false);
        dispose();
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void ResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetButtonActionPerformed
        DiurnalPlotCheckBox.setSelected(form.diurnal_rad_reset);
        HistogramPlotCheckBox.setSelected(form.histogram_rad_reset);
        SpatialPlotCheckBox.setSelected(form.spatial_rad_reset);
        TimeSeriesPlotCheckBox.setSelected(form.time_series_rad_reset);
        LatSouthTextField.setText(form.lat_south_reset);
        LatNorthTextField.setText(form.lat_north_reset);
        LonWestTextField.setText(form.lon_west_reset);
        LonEastTextField.setText(form.lon_east_reset);
        BiasLevelsTextField1.setText(form.bias_level1_reset);
        BiasLevelsTextField2.setText(form.bias_level2_reset);
        BiasLevelsTextField3.setText(form.bias_level3_reset);
        BiasLevelsTextField4.setText(form.bias_level4_reset);
        BiasLevelsTextField5.setText(form.bias_level5_reset);
        BiasLevelsTextField6.setText(form.bias_level6_reset);
        BiasLevelsTextField7.setText(form.bias_level7_reset);
        BiasLevelsTextField8.setText(form.bias_level8_reset);
        BiasLevelsTextField9.setText(form.bias_level9_reset);
        BiasLevelsTextField10.setText(form.bias_level10_reset);
        BiasLevelsTextField11.setText(form.bias_level11_reset);
        BiasLevelsTextField12.setText(form.bias_level12_reset);
        BiasLevelsTextField13.setText(form.bias_level13_reset);
        BiasLevelsTextField14.setText(form.bias_level14_reset);
        BiasLevelsTextField15.setText(form.bias_level15_reset);
        RMSELevelsTextField1.setText(form.rmse_level1_reset);
        RMSELevelsTextField2.setText(form.rmse_level2_reset);
        RMSELevelsTextField3.setText(form.rmse_level3_reset);
        RMSELevelsTextField4.setText(form.rmse_level4_reset);
        RMSELevelsTextField5.setText(form.rmse_level5_reset);
        RMSELevelsTextField6.setText(form.rmse_level6_reset);
        RMSELevelsTextField7.setText(form.rmse_level7_reset);
        RMSELevelsTextField8.setText(form.rmse_level8_reset);
        RMSELevelsTextField9.setText(form.rmse_level9_reset);
        RMSELevelsTextField10.setText(form.rmse_level10_reset);
        RMSELevelsTextField11.setText(form.rmse_level11_reset);
        RMSELevelsTextField12.setText(form.rmse_level12_reset);
        RMSELevelsTextField13.setText(form.rmse_level13_reset);
        MAELevelsTextField1.setText(form.mae_level1_reset);
        MAELevelsTextField2.setText(form.mae_level2_reset);
        MAELevelsTextField3.setText(form.mae_level3_reset);
        MAELevelsTextField4.setText(form.mae_level4_reset);
        MAELevelsTextField5.setText(form.mae_level5_reset);
        MAELevelsTextField6.setText(form.mae_level6_reset);
        MAELevelsTextField7.setText(form.mae_level7_reset);
        MAELevelsTextField8.setText(form.mae_level8_reset);
        MAELevelsTextField9.setText(form.mae_level9_reset);
        MAELevelsTextField10.setText(form.mae_level10_reset);
        MAELevelsTextField11.setText(form.mae_level11_reset);
        SDevLevelsTextField1.setText(form.sdev_level1_reset);
        SDevLevelsTextField2.setText(form.sdev_level2_reset);
        SDevLevelsTextField3.setText(form.sdev_level3_reset);
        SDevLevelsTextField4.setText(form.sdev_level4_reset);
        SDevLevelsTextField5.setText(form.sdev_level5_reset);
        SDevLevelsTextField6.setText(form.sdev_level6_reset);
        SDevLevelsTextField7.setText(form.sdev_level7_reset);
        SDevLevelsTextField8.setText(form.sdev_level8_reset);
        SDevLevelsTextField9.setText(form.sdev_level9_reset);
        SDevLevelsTextField10.setText(form.sdev_level10_reset);
        SDevLevelsTextField11.setText(form.sdev_level11_reset);
        SDevLevelsTextField12.setText(form.sdev_level12_reset);
        SDevLevelsTextField13.setText(form.sdev_level13_reset);
        System.out.println("Shortwave Radiation Analysis Options Reset to Default Values");
    }//GEN-LAST:event_ResetButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BiasLevelsLabel;
    private javax.swing.JTextField BiasLevelsTextField1;
    private javax.swing.JTextField BiasLevelsTextField10;
    private javax.swing.JTextField BiasLevelsTextField11;
    private javax.swing.JTextField BiasLevelsTextField12;
    private javax.swing.JTextField BiasLevelsTextField13;
    private javax.swing.JTextField BiasLevelsTextField14;
    private javax.swing.JTextField BiasLevelsTextField15;
    private javax.swing.JTextField BiasLevelsTextField2;
    private javax.swing.JTextField BiasLevelsTextField3;
    private javax.swing.JTextField BiasLevelsTextField4;
    private javax.swing.JTextField BiasLevelsTextField5;
    private javax.swing.JTextField BiasLevelsTextField6;
    private javax.swing.JTextField BiasLevelsTextField7;
    private javax.swing.JTextField BiasLevelsTextField8;
    private javax.swing.JTextField BiasLevelsTextField9;
    private javax.swing.JButton CancelButton;
    private javax.swing.JCheckBox DiurnalPlotCheckBox;
    private javax.swing.JCheckBox HistogramPlotCheckBox;
    private javax.swing.JLabel LatNorthLabel;
    private javax.swing.JTextField LatNorthTextField;
    private javax.swing.JLabel LatSouthLabel;
    private javax.swing.JTextField LatSouthTextField;
    private javax.swing.JLabel LevelsLabel;
    private javax.swing.JTextArea LevelsTextArea;
    private javax.swing.JLabel LonEastLabel;
    private javax.swing.JTextField LonEastTextField;
    private javax.swing.JLabel LonWestLabel;
    private javax.swing.JTextField LonWestTextField;
    private javax.swing.JLabel MAELevelsLabel;
    private javax.swing.JTextField MAELevelsTextField1;
    private javax.swing.JTextField MAELevelsTextField10;
    private javax.swing.JTextField MAELevelsTextField11;
    private javax.swing.JTextField MAELevelsTextField2;
    private javax.swing.JTextField MAELevelsTextField3;
    private javax.swing.JTextField MAELevelsTextField4;
    private javax.swing.JTextField MAELevelsTextField5;
    private javax.swing.JTextField MAELevelsTextField6;
    private javax.swing.JTextField MAELevelsTextField7;
    private javax.swing.JTextField MAELevelsTextField8;
    private javax.swing.JTextField MAELevelsTextField9;
    private javax.swing.JLabel RMSELevelsLabel;
    private javax.swing.JTextField RMSELevelsTextField1;
    private javax.swing.JTextField RMSELevelsTextField10;
    private javax.swing.JTextField RMSELevelsTextField11;
    private javax.swing.JTextField RMSELevelsTextField12;
    private javax.swing.JTextField RMSELevelsTextField13;
    private javax.swing.JTextField RMSELevelsTextField2;
    private javax.swing.JTextField RMSELevelsTextField3;
    private javax.swing.JTextField RMSELevelsTextField4;
    private javax.swing.JTextField RMSELevelsTextField5;
    private javax.swing.JTextField RMSELevelsTextField6;
    private javax.swing.JTextField RMSELevelsTextField7;
    private javax.swing.JTextField RMSELevelsTextField8;
    private javax.swing.JTextField RMSELevelsTextField9;
    private javax.swing.JLabel RadiationPlotOptionsLabel;
    private javax.swing.JButton ResetButton;
    private javax.swing.JLabel SDevLevelsLabel;
    private javax.swing.JTextField SDevLevelsTextField1;
    private javax.swing.JTextField SDevLevelsTextField10;
    private javax.swing.JTextField SDevLevelsTextField11;
    private javax.swing.JTextField SDevLevelsTextField12;
    private javax.swing.JTextField SDevLevelsTextField13;
    private javax.swing.JTextField SDevLevelsTextField2;
    private javax.swing.JTextField SDevLevelsTextField3;
    private javax.swing.JTextField SDevLevelsTextField4;
    private javax.swing.JTextField SDevLevelsTextField5;
    private javax.swing.JTextField SDevLevelsTextField6;
    private javax.swing.JTextField SDevLevelsTextField7;
    private javax.swing.JTextField SDevLevelsTextField8;
    private javax.swing.JTextField SDevLevelsTextField9;
    private javax.swing.JButton SaveButton;
    private javax.swing.JCheckBox SpatialPlotCheckBox;
    private javax.swing.JLabel SpatialPlotInfoLabel1;
    private javax.swing.JLabel SpatialPlotInfoLabel2;
    private javax.swing.JLabel SpatialPlotOptionsLabel;
    private javax.swing.JCheckBox TimeSeriesPlotCheckBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
