/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ametjavagui.METAdvancedForms;

import ametjavagui.MeteorologyForm;

/**
 *
 * @author Michael Morton
 */
public class TimeSeriesPlotOptions extends javax.swing.JFrame {

    /**
     * Creates new form TimeSeriesPlotOptions
     */
    
    MeteorologyForm form;
    
    public TimeSeriesPlotOptions(MeteorologyForm form) {
        this.form = form;
        initComponents();
        if (!form.dbase2.equals("\"\"")){
            CompareCheckBox.setSelected(true);
        }
        WdWeightWsCheckBox.setSelected(form.weight);
        GroupStatCheckBox.setSelected(form.groupstat);
        //CompareCheckBox.setSelected(form.compare);
        ExtraTextField.setText(form.extra);
        TemperatureLimitLowerTextField.setText(form.qc_temp_limit_lower);
        TemperatureLimitUpperTextField.setText(form.qc_temp_limit_upper);
        MoistureLimitLowerTextField.setText(form.qc_moisture_limit_lower);
        MoistureLimitUpperTextField.setText(form.qc_moisture_limit_upper);
        WindSpeedLimitLowerTextField.setText(form.qc_wind_limit_lower);
        WindSpeedLimitUpperTextField.setText(form.qc_wind_limit_upper);
        HumidityLimitLowerTextField.setText(form.qc_humidity_limit_lower);
        HumidityLimitUpperTextField.setText(form.qc_humidity_limit_upper);
        PressureLimitLowerTextField.setText(form.qc_pressure_kPa_lower);
        PressureLimitUpperTextField.setText(form.qc_pressure_kPa_upper);
        ErrorTempTextField.setText(form.qc_error_temp);
        ErrorWindSpeedTextField.setText(form.qc_error_wind);
        ErrorMoistureTextField.setText(form.qc_error_moisture);
        ErrorRelativeHumidityTextField.setText(form.qc_error_humidity);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        ExtraLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        TimeSeriesPlotOptionsLabel = new javax.swing.JLabel();
        WdWeightWsCheckBox = new javax.swing.JCheckBox();
        WdWeightWsLabel = new javax.swing.JLabel();
        GroupStatCheckBox = new javax.swing.JCheckBox();
        CompareCheckBox = new javax.swing.JCheckBox();
        ExtraLabel = new javax.swing.JLabel();
        ExtraLabel2 = new javax.swing.JLabel();
        ExtraLabel3 = new javax.swing.JLabel();
        ExtraLabel4 = new javax.swing.JLabel();
        ExtraTextField = new javax.swing.JTextField();
        QCLimitSettingsLabel = new javax.swing.JLabel();
        TemperatureLimitLowerLabel = new javax.swing.JLabel();
        TemperatureLimitLowerTextField = new javax.swing.JTextField();
        TemperaureLimitLowerUnitLabel = new javax.swing.JLabel();
        TemperatureLimitUpperLabel = new javax.swing.JLabel();
        TemperatureLimitUpperTextField = new javax.swing.JTextField();
        TemperaureLimitUpperUnitLabel = new javax.swing.JLabel();
        MoistureLimitLowerLabel = new javax.swing.JLabel();
        MoistureLimitLowerTextField = new javax.swing.JTextField();
        MoistureLimitLowerUnitLabel = new javax.swing.JLabel();
        MoistureLimitUpperLabel = new javax.swing.JLabel();
        MoistureLimitUpperTextField = new javax.swing.JTextField();
        MoistureLimitUpperUnitLabel = new javax.swing.JLabel();
        WindSpeedLimitLowerLabel = new javax.swing.JLabel();
        WindSpeedLimitLowerTextField = new javax.swing.JTextField();
        WindSpeedLimitLowerUnitLabel = new javax.swing.JLabel();
        WindSpeedLimitUpperLabel = new javax.swing.JLabel();
        WindSpeedLimitUpperTextField = new javax.swing.JTextField();
        WindSpeedLimitUpperUnitLabel = new javax.swing.JLabel();
        HumidityLimitLowerLabel = new javax.swing.JLabel();
        HumidityLimitLowerTextField = new javax.swing.JTextField();
        HumidityLimitLowerUnitLabel = new javax.swing.JLabel();
        HumidityLimitUpperLabel = new javax.swing.JLabel();
        HumidityLimitUpperTextField = new javax.swing.JTextField();
        HumidityLimitUpperUnitLabel = new javax.swing.JLabel();
        PressureLimitLowerLabel = new javax.swing.JLabel();
        PressureLimitLowerTextField = new javax.swing.JTextField();
        PressureLimitLowerUnitLabel = new javax.swing.JLabel();
        PressureLimitUpperLabel = new javax.swing.JLabel();
        PressureLimitUpperTextField = new javax.swing.JTextField();
        PressureLimitUpperUnitLabel = new javax.swing.JLabel();
        ErrorTempLabel = new javax.swing.JLabel();
        ErrorTempTextField = new javax.swing.JTextField();
        ErrorTempUnitLabel = new javax.swing.JLabel();
        ErrorWindSpeedLabel = new javax.swing.JLabel();
        ErrorWindSpeedTextField = new javax.swing.JTextField();
        ErrorWindSpeedUnitLabel = new javax.swing.JLabel();
        ErrorMoistureLabel = new javax.swing.JLabel();
        ErrorMoistureTextField = new javax.swing.JTextField();
        ErrorMoistureUnitLabel = new javax.swing.JLabel();
        ErrorRelativeHumidityLabel = new javax.swing.JLabel();
        ErrorRelativeHumidityTextField = new javax.swing.JTextField();
        ErrorRelativeHumidityUnitLabel = new javax.swing.JLabel();
        SaveButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        ExtraLabel5 = new javax.swing.JLabel();
        ExtraLabel6 = new javax.swing.JLabel();
        ExtraLabel7 = new javax.swing.JLabel();
        ResetButton = new javax.swing.JButton();

        jLabel3.setText("jLabel3");

        ExtraLabel1.setBackground(new java.awt.Color(255, 255, 255));
        ExtraLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ExtraLabel1.setForeground(new java.awt.Color(0, 112, 185));
        ExtraLabel1.setText("Enter a custom MySQL query below. The query must begin with AND.");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Time Series Plot Options");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(668, 915));

        TimeSeriesPlotOptionsLabel.setBackground(new java.awt.Color(255, 255, 255));
        TimeSeriesPlotOptionsLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        TimeSeriesPlotOptionsLabel.setForeground(new java.awt.Color(0, 63, 105));
        TimeSeriesPlotOptionsLabel.setText("Time Series Analysis Options");

        WdWeightWsCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        WdWeightWsCheckBox.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        WdWeightWsCheckBox.setForeground(new java.awt.Color(0, 112, 185));
        WdWeightWsCheckBox.setText("Weigh wind direction error by wind speed");

        WdWeightWsLabel.setBackground(new java.awt.Color(255, 255, 255));
        WdWeightWsLabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        WdWeightWsLabel.setForeground(new java.awt.Color(0, 112, 185));
        WdWeightWsLabel.setText("(WS less than 5 m/s have less weight on WD error)");

        GroupStatCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        GroupStatCheckBox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        GroupStatCheckBox.setForeground(new java.awt.Color(0, 112, 185));
        GroupStatCheckBox.setText("Combine all sites in an average model-observation time series");

        CompareCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        CompareCheckBox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        CompareCheckBox.setForeground(new java.awt.Color(0, 112, 185));
        CompareCheckBox.setText("Add second Project 2 to time series (specify in Project Tab)");

        ExtraLabel.setBackground(new java.awt.Color(255, 255, 255));
        ExtraLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ExtraLabel.setForeground(new java.awt.Color(0, 112, 185));
        ExtraLabel.setText("Enter a custom MySQL query below. The query must begin with AND.");

        ExtraLabel2.setBackground(new java.awt.Color(255, 255, 255));
        ExtraLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ExtraLabel2.setForeground(new java.awt.Color(0, 112, 185));
        ExtraLabel2.setText("- For Example: AND fcast_hr=0");

        ExtraLabel3.setBackground(new java.awt.Color(255, 255, 255));
        ExtraLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ExtraLabel3.setForeground(new java.awt.Color(0, 112, 185));
        ExtraLabel3.setText("AND fcast_hr BETWEEN 0 and 24");

        ExtraLabel4.setBackground(new java.awt.Color(255, 255, 255));
        ExtraLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ExtraLabel4.setForeground(new java.awt.Color(0, 112, 185));
        ExtraLabel4.setText("AND T_ob < 273.14");

        ExtraTextField.setBackground(new java.awt.Color(191, 182, 172));
        ExtraTextField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ExtraTextField.setForeground(new java.awt.Color(0, 63, 105));

        QCLimitSettingsLabel.setBackground(new java.awt.Color(255, 255, 255));
        QCLimitSettingsLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        QCLimitSettingsLabel.setForeground(new java.awt.Color(0, 63, 105));
        QCLimitSettingsLabel.setText("Quality Control Settings");

        TemperatureLimitLowerLabel.setBackground(new java.awt.Color(255, 255, 255));
        TemperatureLimitLowerLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TemperatureLimitLowerLabel.setForeground(new java.awt.Color(0, 112, 185));
        TemperatureLimitLowerLabel.setText("Temperature Lower Limit:");

        TemperatureLimitLowerTextField.setBackground(new java.awt.Color(191, 182, 172));
        TemperatureLimitLowerTextField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TemperatureLimitLowerTextField.setForeground(new java.awt.Color(0, 63, 105));
        TemperatureLimitLowerTextField.setText("240");
        TemperatureLimitLowerTextField.setMaximumSize(new java.awt.Dimension(65, 23));
        TemperatureLimitLowerTextField.setMinimumSize(new java.awt.Dimension(65, 23));
        TemperatureLimitLowerTextField.setPreferredSize(new java.awt.Dimension(65, 23));

        TemperaureLimitLowerUnitLabel.setBackground(new java.awt.Color(255, 255, 255));
        TemperaureLimitLowerUnitLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TemperaureLimitLowerUnitLabel.setForeground(new java.awt.Color(0, 112, 185));
        TemperaureLimitLowerUnitLabel.setText("K");

        TemperatureLimitUpperLabel.setBackground(new java.awt.Color(255, 255, 255));
        TemperatureLimitUpperLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TemperatureLimitUpperLabel.setForeground(new java.awt.Color(0, 112, 185));
        TemperatureLimitUpperLabel.setText("Temperature Upper Limit:");

        TemperatureLimitUpperTextField.setBackground(new java.awt.Color(191, 182, 172));
        TemperatureLimitUpperTextField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TemperatureLimitUpperTextField.setForeground(new java.awt.Color(0, 63, 105));
        TemperatureLimitUpperTextField.setText("315");
        TemperatureLimitUpperTextField.setMaximumSize(new java.awt.Dimension(65, 23));
        TemperatureLimitUpperTextField.setMinimumSize(new java.awt.Dimension(65, 23));
        TemperatureLimitUpperTextField.setPreferredSize(new java.awt.Dimension(65, 23));

        TemperaureLimitUpperUnitLabel.setBackground(new java.awt.Color(255, 255, 255));
        TemperaureLimitUpperUnitLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TemperaureLimitUpperUnitLabel.setForeground(new java.awt.Color(0, 112, 185));
        TemperaureLimitUpperUnitLabel.setText("K");

        MoistureLimitLowerLabel.setBackground(new java.awt.Color(255, 255, 255));
        MoistureLimitLowerLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        MoistureLimitLowerLabel.setForeground(new java.awt.Color(0, 112, 185));
        MoistureLimitLowerLabel.setText("Moisture Lower Limit:");

        MoistureLimitLowerTextField.setBackground(new java.awt.Color(191, 182, 172));
        MoistureLimitLowerTextField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        MoistureLimitLowerTextField.setForeground(new java.awt.Color(0, 63, 105));
        MoistureLimitLowerTextField.setText("0");
        MoistureLimitLowerTextField.setMaximumSize(new java.awt.Dimension(65, 23));
        MoistureLimitLowerTextField.setMinimumSize(new java.awt.Dimension(65, 23));
        MoistureLimitLowerTextField.setPreferredSize(new java.awt.Dimension(65, 23));

        MoistureLimitLowerUnitLabel.setBackground(new java.awt.Color(255, 255, 255));
        MoistureLimitLowerUnitLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        MoistureLimitLowerUnitLabel.setForeground(new java.awt.Color(0, 112, 185));
        MoistureLimitLowerUnitLabel.setText("g/kg");

        MoistureLimitUpperLabel.setBackground(new java.awt.Color(255, 255, 255));
        MoistureLimitUpperLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        MoistureLimitUpperLabel.setForeground(new java.awt.Color(0, 112, 185));
        MoistureLimitUpperLabel.setText("Moisture Upper Limit:");

        MoistureLimitUpperTextField.setBackground(new java.awt.Color(191, 182, 172));
        MoistureLimitUpperTextField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        MoistureLimitUpperTextField.setForeground(new java.awt.Color(0, 63, 105));
        MoistureLimitUpperTextField.setText("30");
        MoistureLimitUpperTextField.setMaximumSize(new java.awt.Dimension(65, 23));
        MoistureLimitUpperTextField.setMinimumSize(new java.awt.Dimension(65, 23));
        MoistureLimitUpperTextField.setPreferredSize(new java.awt.Dimension(65, 23));

        MoistureLimitUpperUnitLabel.setBackground(new java.awt.Color(255, 255, 255));
        MoistureLimitUpperUnitLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        MoistureLimitUpperUnitLabel.setForeground(new java.awt.Color(0, 112, 185));
        MoistureLimitUpperUnitLabel.setText("g/kg");

        WindSpeedLimitLowerLabel.setBackground(new java.awt.Color(255, 255, 255));
        WindSpeedLimitLowerLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        WindSpeedLimitLowerLabel.setForeground(new java.awt.Color(0, 112, 185));
        WindSpeedLimitLowerLabel.setText("Wind Speed Lower Limit:");

        WindSpeedLimitLowerTextField.setBackground(new java.awt.Color(191, 182, 172));
        WindSpeedLimitLowerTextField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        WindSpeedLimitLowerTextField.setForeground(new java.awt.Color(0, 63, 105));
        WindSpeedLimitLowerTextField.setText("1.5");
        WindSpeedLimitLowerTextField.setMaximumSize(new java.awt.Dimension(65, 23));
        WindSpeedLimitLowerTextField.setMinimumSize(new java.awt.Dimension(65, 23));
        WindSpeedLimitLowerTextField.setPreferredSize(new java.awt.Dimension(65, 23));

        WindSpeedLimitLowerUnitLabel.setBackground(new java.awt.Color(255, 255, 255));
        WindSpeedLimitLowerUnitLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        WindSpeedLimitLowerUnitLabel.setForeground(new java.awt.Color(0, 112, 185));
        WindSpeedLimitLowerUnitLabel.setText("m/s");

        WindSpeedLimitUpperLabel.setBackground(new java.awt.Color(255, 255, 255));
        WindSpeedLimitUpperLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        WindSpeedLimitUpperLabel.setForeground(new java.awt.Color(0, 112, 185));
        WindSpeedLimitUpperLabel.setText("Wind Speed Upper Limit:");

        WindSpeedLimitUpperTextField.setBackground(new java.awt.Color(191, 182, 172));
        WindSpeedLimitUpperTextField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        WindSpeedLimitUpperTextField.setForeground(new java.awt.Color(0, 63, 105));
        WindSpeedLimitUpperTextField.setText("25");
        WindSpeedLimitUpperTextField.setMaximumSize(new java.awt.Dimension(65, 23));
        WindSpeedLimitUpperTextField.setMinimumSize(new java.awt.Dimension(65, 23));
        WindSpeedLimitUpperTextField.setPreferredSize(new java.awt.Dimension(65, 23));

        WindSpeedLimitUpperUnitLabel.setBackground(new java.awt.Color(255, 255, 255));
        WindSpeedLimitUpperUnitLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        WindSpeedLimitUpperUnitLabel.setForeground(new java.awt.Color(0, 112, 185));
        WindSpeedLimitUpperUnitLabel.setText("m/s");

        HumidityLimitLowerLabel.setBackground(new java.awt.Color(255, 255, 255));
        HumidityLimitLowerLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        HumidityLimitLowerLabel.setForeground(new java.awt.Color(0, 112, 185));
        HumidityLimitLowerLabel.setText("Relative Humidity Lower Limit:");

        HumidityLimitLowerTextField.setBackground(new java.awt.Color(191, 182, 172));
        HumidityLimitLowerTextField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        HumidityLimitLowerTextField.setForeground(new java.awt.Color(0, 63, 105));
        HumidityLimitLowerTextField.setText("0");
        HumidityLimitLowerTextField.setMaximumSize(new java.awt.Dimension(65, 23));
        HumidityLimitLowerTextField.setMinimumSize(new java.awt.Dimension(65, 23));
        HumidityLimitLowerTextField.setPreferredSize(new java.awt.Dimension(65, 23));

        HumidityLimitLowerUnitLabel.setBackground(new java.awt.Color(255, 255, 255));
        HumidityLimitLowerUnitLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        HumidityLimitLowerUnitLabel.setForeground(new java.awt.Color(0, 112, 185));
        HumidityLimitLowerUnitLabel.setText("%");

        HumidityLimitUpperLabel.setBackground(new java.awt.Color(255, 255, 255));
        HumidityLimitUpperLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        HumidityLimitUpperLabel.setForeground(new java.awt.Color(0, 112, 185));
        HumidityLimitUpperLabel.setText("Relative Humidity Upper Limit:");

        HumidityLimitUpperTextField.setBackground(new java.awt.Color(191, 182, 172));
        HumidityLimitUpperTextField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        HumidityLimitUpperTextField.setForeground(new java.awt.Color(0, 63, 105));
        HumidityLimitUpperTextField.setText("102");
        HumidityLimitUpperTextField.setMaximumSize(new java.awt.Dimension(65, 23));
        HumidityLimitUpperTextField.setMinimumSize(new java.awt.Dimension(65, 23));
        HumidityLimitUpperTextField.setPreferredSize(new java.awt.Dimension(65, 23));

        HumidityLimitUpperUnitLabel.setBackground(new java.awt.Color(255, 255, 255));
        HumidityLimitUpperUnitLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        HumidityLimitUpperUnitLabel.setForeground(new java.awt.Color(0, 112, 185));
        HumidityLimitUpperUnitLabel.setText("%");

        PressureLimitLowerLabel.setBackground(new java.awt.Color(255, 255, 255));
        PressureLimitLowerLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        PressureLimitLowerLabel.setForeground(new java.awt.Color(0, 112, 185));
        PressureLimitLowerLabel.setText("Surface Pressure Lower Limit:");

        PressureLimitLowerTextField.setBackground(new java.awt.Color(191, 182, 172));
        PressureLimitLowerTextField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        PressureLimitLowerTextField.setForeground(new java.awt.Color(0, 63, 105));
        PressureLimitLowerTextField.setText("500");
        PressureLimitLowerTextField.setMaximumSize(new java.awt.Dimension(65, 23));
        PressureLimitLowerTextField.setMinimumSize(new java.awt.Dimension(65, 23));
        PressureLimitLowerTextField.setPreferredSize(new java.awt.Dimension(65, 23));

        PressureLimitLowerUnitLabel.setBackground(new java.awt.Color(255, 255, 255));
        PressureLimitLowerUnitLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        PressureLimitLowerUnitLabel.setForeground(new java.awt.Color(0, 112, 185));
        PressureLimitLowerUnitLabel.setText("mb");

        PressureLimitUpperLabel.setBackground(new java.awt.Color(255, 255, 255));
        PressureLimitUpperLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        PressureLimitUpperLabel.setForeground(new java.awt.Color(0, 112, 185));
        PressureLimitUpperLabel.setText("Surface Pressure Upper Limit:");

        PressureLimitUpperTextField.setBackground(new java.awt.Color(191, 182, 172));
        PressureLimitUpperTextField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        PressureLimitUpperTextField.setForeground(new java.awt.Color(0, 63, 105));
        PressureLimitUpperTextField.setText("1070");
        PressureLimitUpperTextField.setMaximumSize(new java.awt.Dimension(65, 23));
        PressureLimitUpperTextField.setMinimumSize(new java.awt.Dimension(65, 23));
        PressureLimitUpperTextField.setPreferredSize(new java.awt.Dimension(65, 23));

        PressureLimitUpperUnitLabel.setBackground(new java.awt.Color(255, 255, 255));
        PressureLimitUpperUnitLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        PressureLimitUpperUnitLabel.setForeground(new java.awt.Color(0, 112, 185));
        PressureLimitUpperUnitLabel.setText("mb");

        ErrorTempLabel.setBackground(new java.awt.Color(255, 255, 255));
        ErrorTempLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ErrorTempLabel.setForeground(new java.awt.Color(0, 112, 185));
        ErrorTempLabel.setText("Error Limit for Temperature:");

        ErrorTempTextField.setBackground(new java.awt.Color(191, 182, 172));
        ErrorTempTextField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ErrorTempTextField.setForeground(new java.awt.Color(0, 63, 105));
        ErrorTempTextField.setText("15");
        ErrorTempTextField.setMaximumSize(new java.awt.Dimension(65, 23));
        ErrorTempTextField.setMinimumSize(new java.awt.Dimension(65, 23));
        ErrorTempTextField.setPreferredSize(new java.awt.Dimension(65, 23));

        ErrorTempUnitLabel.setBackground(new java.awt.Color(255, 255, 255));
        ErrorTempUnitLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ErrorTempUnitLabel.setForeground(new java.awt.Color(0, 112, 185));
        ErrorTempUnitLabel.setText("K");

        ErrorWindSpeedLabel.setBackground(new java.awt.Color(255, 255, 255));
        ErrorWindSpeedLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ErrorWindSpeedLabel.setForeground(new java.awt.Color(0, 112, 185));
        ErrorWindSpeedLabel.setText("Error Limit for Wind Speed:");

        ErrorWindSpeedTextField.setBackground(new java.awt.Color(191, 182, 172));
        ErrorWindSpeedTextField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ErrorWindSpeedTextField.setForeground(new java.awt.Color(0, 63, 105));
        ErrorWindSpeedTextField.setText("20");
        ErrorWindSpeedTextField.setMaximumSize(new java.awt.Dimension(65, 23));
        ErrorWindSpeedTextField.setMinimumSize(new java.awt.Dimension(65, 23));
        ErrorWindSpeedTextField.setPreferredSize(new java.awt.Dimension(65, 23));

        ErrorWindSpeedUnitLabel.setBackground(new java.awt.Color(255, 255, 255));
        ErrorWindSpeedUnitLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ErrorWindSpeedUnitLabel.setForeground(new java.awt.Color(0, 112, 185));
        ErrorWindSpeedUnitLabel.setText("m/s");

        ErrorMoistureLabel.setBackground(new java.awt.Color(255, 255, 255));
        ErrorMoistureLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ErrorMoistureLabel.setForeground(new java.awt.Color(0, 112, 185));
        ErrorMoistureLabel.setText("Error Limit for Moisture:");

        ErrorMoistureTextField.setBackground(new java.awt.Color(191, 182, 172));
        ErrorMoistureTextField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ErrorMoistureTextField.setForeground(new java.awt.Color(0, 63, 105));
        ErrorMoistureTextField.setText("10");
        ErrorMoistureTextField.setMaximumSize(new java.awt.Dimension(65, 23));
        ErrorMoistureTextField.setMinimumSize(new java.awt.Dimension(65, 23));
        ErrorMoistureTextField.setPreferredSize(new java.awt.Dimension(65, 23));

        ErrorMoistureUnitLabel.setBackground(new java.awt.Color(255, 255, 255));
        ErrorMoistureUnitLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ErrorMoistureUnitLabel.setForeground(new java.awt.Color(0, 112, 185));
        ErrorMoistureUnitLabel.setText("g/kg");

        ErrorRelativeHumidityLabel.setBackground(new java.awt.Color(255, 255, 255));
        ErrorRelativeHumidityLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ErrorRelativeHumidityLabel.setForeground(new java.awt.Color(0, 112, 185));
        ErrorRelativeHumidityLabel.setText("Error Limit for Relative Humidity:");

        ErrorRelativeHumidityTextField.setBackground(new java.awt.Color(191, 182, 172));
        ErrorRelativeHumidityTextField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ErrorRelativeHumidityTextField.setForeground(new java.awt.Color(0, 63, 105));
        ErrorRelativeHumidityTextField.setText("50");
        ErrorRelativeHumidityTextField.setMaximumSize(new java.awt.Dimension(65, 23));
        ErrorRelativeHumidityTextField.setMinimumSize(new java.awt.Dimension(65, 23));
        ErrorRelativeHumidityTextField.setPreferredSize(new java.awt.Dimension(65, 23));

        ErrorRelativeHumidityUnitLabel.setBackground(new java.awt.Color(255, 255, 255));
        ErrorRelativeHumidityUnitLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ErrorRelativeHumidityUnitLabel.setForeground(new java.awt.Color(0, 112, 185));
        ErrorRelativeHumidityUnitLabel.setText("%");

        SaveButton.setBackground(new java.awt.Color(0, 63, 105));
        SaveButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        SaveButton.setForeground(new java.awt.Color(191, 182, 172));
        SaveButton.setText("Save");
        SaveButton.setMaximumSize(new java.awt.Dimension(100, 26));
        SaveButton.setMinimumSize(new java.awt.Dimension(75, 26));
        SaveButton.setPreferredSize(new java.awt.Dimension(75, 26));
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        CancelButton.setBackground(new java.awt.Color(0, 63, 105));
        CancelButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        CancelButton.setForeground(new java.awt.Color(191, 182, 172));
        CancelButton.setText("Cancel");
        CancelButton.setMaximumSize(new java.awt.Dimension(100, 26));
        CancelButton.setMinimumSize(new java.awt.Dimension(90, 26));
        CancelButton.setPreferredSize(new java.awt.Dimension(90, 26));
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        ExtraLabel5.setBackground(new java.awt.Color(255, 255, 255));
        ExtraLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ExtraLabel5.setForeground(new java.awt.Color(0, 112, 185));
        ExtraLabel5.setText("Used to remove extreme differences between the model and observations ");

        ExtraLabel6.setBackground(new java.awt.Color(255, 255, 255));
        ExtraLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ExtraLabel6.setForeground(new java.awt.Color(0, 112, 185));
        ExtraLabel6.setText("and/or apply an upper and lower limit criteria on data used in the  ");

        ExtraLabel7.setBackground(new java.awt.Color(255, 255, 255));
        ExtraLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ExtraLabel7.setForeground(new java.awt.Color(0, 112, 185));
        ExtraLabel7.setText("statistical analyses.");

        ResetButton.setBackground(new java.awt.Color(0, 63, 105));
        ResetButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ResetButton.setForeground(new java.awt.Color(191, 182, 172));
        ResetButton.setText("Reset");
        ResetButton.setMaximumSize(new java.awt.Dimension(100, 26));
        ResetButton.setMinimumSize(new java.awt.Dimension(80, 26));
        ResetButton.setPreferredSize(new java.awt.Dimension(80, 26));
        ResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ExtraLabel3)
                    .addComponent(ExtraLabel4))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GroupStatCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ExtraLabel)
                            .addComponent(CompareCheckBox)
                            .addComponent(QCLimitSettingsLabel)
                            .addComponent(TimeSeriesPlotOptionsLabel)
                            .addComponent(ExtraLabel2))
                        .addContainerGap(101, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ExtraLabel5)
                            .addComponent(WdWeightWsCheckBox)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(WdWeightWsLabel))
                            .addComponent(ExtraLabel6)
                            .addComponent(ExtraLabel7))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(PressureLimitLowerLabel)
                                        .addGap(12, 12, 12)
                                        .addComponent(PressureLimitLowerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(PressureLimitUpperLabel)
                                        .addGap(14, 14, 14)
                                        .addComponent(PressureLimitUpperTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(MoistureLimitLowerLabel)
                                        .addGap(46, 46, 46)
                                        .addComponent(MoistureLimitLowerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(HumidityLimitUpperLabel)
                                        .addGap(16, 16, 16)
                                        .addComponent(HumidityLimitUpperTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(ErrorTempLabel)
                                        .addGap(44, 44, 44)
                                        .addComponent(ErrorTempTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(HumidityLimitLowerLabel)
                                        .addGap(14, 14, 14)
                                        .addComponent(HumidityLimitLowerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(WindSpeedLimitUpperLabel)
                                            .addGap(23, 23, 23)
                                            .addComponent(WindSpeedLimitUpperTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(WindSpeedLimitLowerLabel)
                                                .addGap(21, 21, 21)
                                                .addComponent(WindSpeedLimitLowerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(MoistureLimitUpperLabel)
                                                .addGap(48, 48, 48)
                                                .addComponent(MoistureLimitUpperTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(TemperatureLimitLowerLabel)
                                            .addGap(12, 12, 12)
                                            .addComponent(TemperatureLimitLowerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(TemperatureLimitUpperLabel)
                                            .addGap(14, 14, 14)
                                            .addComponent(TemperatureLimitUpperTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(ErrorMoistureLabel)
                                            .addGap(78, 78, 78)
                                            .addComponent(ErrorMoistureTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(ErrorWindSpeedLabel)
                                            .addGap(53, 53, 53)
                                            .addComponent(ErrorWindSpeedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(ErrorRelativeHumidityLabel)
                                            .addGap(12, 12, 12)
                                            .addComponent(ErrorRelativeHumidityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(ResetButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TemperaureLimitUpperUnitLabel)
                                            .addComponent(MoistureLimitLowerUnitLabel)
                                            .addComponent(MoistureLimitUpperUnitLabel)
                                            .addComponent(WindSpeedLimitLowerUnitLabel)
                                            .addComponent(WindSpeedLimitUpperUnitLabel)
                                            .addComponent(ErrorTempUnitLabel)
                                            .addComponent(ErrorWindSpeedUnitLabel)
                                            .addComponent(ErrorMoistureUnitLabel)
                                            .addComponent(TemperaureLimitLowerUnitLabel)
                                            .addComponent(HumidityLimitLowerUnitLabel)
                                            .addComponent(HumidityLimitUpperUnitLabel)
                                            .addComponent(PressureLimitLowerUnitLabel)
                                            .addComponent(PressureLimitUpperUnitLabel)
                                            .addComponent(ErrorRelativeHumidityUnitLabel)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(SaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(40, 40, 40)
                                        .addComponent(CancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(ExtraTextField))
                        .addGap(20, 20, 20))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TimeSeriesPlotOptionsLabel)
                .addGap(20, 20, 20)
                .addComponent(WdWeightWsCheckBox)
                .addGap(0, 0, 0)
                .addComponent(WdWeightWsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(GroupStatCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CompareCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ExtraLabel)
                .addGap(0, 0, 0)
                .addComponent(ExtraLabel2)
                .addGap(1, 1, 1)
                .addComponent(ExtraLabel3)
                .addGap(0, 0, 0)
                .addComponent(ExtraLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ExtraTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(QCLimitSettingsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ExtraLabel5)
                .addGap(0, 0, 0)
                .addComponent(ExtraLabel6)
                .addGap(0, 0, 0)
                .addComponent(ExtraLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TemperatureLimitLowerLabel)
                    .addComponent(TemperaureLimitLowerUnitLabel)
                    .addComponent(TemperatureLimitLowerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TemperatureLimitUpperLabel)
                    .addComponent(TemperatureLimitUpperTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TemperaureLimitUpperUnitLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MoistureLimitLowerLabel)
                    .addComponent(MoistureLimitLowerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MoistureLimitLowerUnitLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MoistureLimitUpperLabel)
                    .addComponent(MoistureLimitUpperTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MoistureLimitUpperUnitLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WindSpeedLimitLowerLabel)
                    .addComponent(WindSpeedLimitLowerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WindSpeedLimitLowerUnitLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WindSpeedLimitUpperLabel)
                    .addComponent(WindSpeedLimitUpperTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WindSpeedLimitUpperUnitLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HumidityLimitLowerLabel)
                    .addComponent(HumidityLimitLowerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HumidityLimitLowerUnitLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HumidityLimitUpperLabel)
                    .addComponent(HumidityLimitUpperTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HumidityLimitUpperUnitLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PressureLimitLowerLabel)
                    .addComponent(PressureLimitLowerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PressureLimitLowerUnitLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PressureLimitUpperLabel)
                    .addComponent(PressureLimitUpperTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PressureLimitUpperUnitLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ErrorTempLabel)
                    .addComponent(ErrorTempTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ErrorTempUnitLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ErrorWindSpeedLabel)
                    .addComponent(ErrorWindSpeedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ErrorWindSpeedUnitLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ErrorMoistureTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ErrorMoistureUnitLabel)
                    .addComponent(ErrorMoistureLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ErrorRelativeHumidityLabel)
                    .addComponent(ErrorRelativeHumidityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ErrorRelativeHumidityUnitLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ResetButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        form.wd_weight_ws = form.checkBoxFormat(WdWeightWsCheckBox);
        form.weight = WdWeightWsCheckBox.isSelected();
        form.group_stat = form.checkBoxFormat(GroupStatCheckBox);
        form.groupstat = GroupStatCheckBox.isSelected();
        form.comp = form.checkBoxFormat(CompareCheckBox);
        form.compare = CompareCheckBox.isSelected();
        form.extra = ExtraTextField.getText();
        form.qc_temp_limit_lower = form.numNullFormat(TemperatureLimitLowerTextField.getText());
        form.qc_temp_limit_upper = form.numNullFormat(TemperatureLimitUpperTextField.getText());
        form.qc_moisture_limit_lower = form.numNullFormat(MoistureLimitLowerTextField.getText());
        form.qc_moisture_limit_upper = form.numNullFormat(MoistureLimitUpperTextField.getText());
        form.qc_wind_limit_lower = form.numNullFormat(WindSpeedLimitLowerTextField.getText());
        form.qc_wind_limit_upper = form.numNullFormat(WindSpeedLimitUpperTextField.getText());
        form.qc_humidity_limit_lower = form.numNullFormat(HumidityLimitLowerTextField.getText());
        form.qc_humidity_limit_upper = form.numNullFormat(HumidityLimitUpperTextField.getText());
        form.qc_pressure_kPa_lower = form.numNullFormat(PressureLimitLowerTextField.getText());
        form.qc_pressure_kPa_upper = form.numNullFormat(PressureLimitUpperTextField.getText());
        form.qc_error_temp = form.numNullFormat(ErrorTempTextField.getText());
        form.qc_error_wind = form.numNullFormat(ErrorWindSpeedTextField.getText());
        form.qc_error_moisture = form.numNullFormat(ErrorMoistureTextField.getText());
        form.qc_error_humidity = form.numNullFormat(ErrorRelativeHumidityTextField.getText());
        System.out.println("Time Series Analysis Options Saved");
        setVisible(false);
        dispose();
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void ResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetButtonActionPerformed
        WdWeightWsCheckBox.setSelected(form.weight_reset);
        GroupStatCheckBox.setSelected(form.groupstat_reset);
        ExtraTextField.setText(form.extra_reset);
        TemperatureLimitLowerTextField.setText(form.qc_temp_limit_lower_reset);
        TemperatureLimitUpperTextField.setText(form.qc_temp_limit_upper_reset);
        MoistureLimitLowerTextField.setText(form.qc_moisture_limit_lower_reset);
        MoistureLimitUpperTextField.setText(form.qc_moisture_limit_upper_reset);
        WindSpeedLimitLowerTextField.setText(form.qc_wind_limit_lower_reset);
        WindSpeedLimitUpperTextField.setText(form.qc_wind_limit_upper_reset);
        HumidityLimitLowerTextField.setText(form.qc_humidity_limit_lower_reset);
        HumidityLimitUpperTextField.setText(form.qc_humidity_limit_upper_reset);
        PressureLimitLowerTextField.setText(form.qc_pressure_kPa_lower_reset);
        PressureLimitUpperTextField.setText(form.qc_pressure_kPa_upper_reset);
        ErrorTempTextField.setText(form.qc_error_temp_reset);
        ErrorWindSpeedTextField.setText(form.qc_error_wind_reset);
        ErrorMoistureTextField.setText(form.qc_error_moisture_reset);
        ErrorRelativeHumidityTextField.setText(form.qc_error_humidity_reset);
        System.out.println("Time Series Analysis Options Reset to Default Values");
    }//GEN-LAST:event_ResetButtonActionPerformed

    
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton;
    private javax.swing.JCheckBox CompareCheckBox;
    private javax.swing.JLabel ErrorMoistureLabel;
    private javax.swing.JTextField ErrorMoistureTextField;
    private javax.swing.JLabel ErrorMoistureUnitLabel;
    private javax.swing.JLabel ErrorRelativeHumidityLabel;
    private javax.swing.JTextField ErrorRelativeHumidityTextField;
    private javax.swing.JLabel ErrorRelativeHumidityUnitLabel;
    private javax.swing.JLabel ErrorTempLabel;
    private javax.swing.JTextField ErrorTempTextField;
    private javax.swing.JLabel ErrorTempUnitLabel;
    private javax.swing.JLabel ErrorWindSpeedLabel;
    private javax.swing.JTextField ErrorWindSpeedTextField;
    private javax.swing.JLabel ErrorWindSpeedUnitLabel;
    private javax.swing.JLabel ExtraLabel;
    private javax.swing.JLabel ExtraLabel1;
    private javax.swing.JLabel ExtraLabel2;
    private javax.swing.JLabel ExtraLabel3;
    private javax.swing.JLabel ExtraLabel4;
    private javax.swing.JLabel ExtraLabel5;
    private javax.swing.JLabel ExtraLabel6;
    private javax.swing.JLabel ExtraLabel7;
    private javax.swing.JTextField ExtraTextField;
    private javax.swing.JCheckBox GroupStatCheckBox;
    private javax.swing.JLabel HumidityLimitLowerLabel;
    private javax.swing.JTextField HumidityLimitLowerTextField;
    private javax.swing.JLabel HumidityLimitLowerUnitLabel;
    private javax.swing.JLabel HumidityLimitUpperLabel;
    private javax.swing.JTextField HumidityLimitUpperTextField;
    private javax.swing.JLabel HumidityLimitUpperUnitLabel;
    private javax.swing.JLabel MoistureLimitLowerLabel;
    private javax.swing.JTextField MoistureLimitLowerTextField;
    private javax.swing.JLabel MoistureLimitLowerUnitLabel;
    private javax.swing.JLabel MoistureLimitUpperLabel;
    private javax.swing.JTextField MoistureLimitUpperTextField;
    private javax.swing.JLabel MoistureLimitUpperUnitLabel;
    private javax.swing.JLabel PressureLimitLowerLabel;
    private javax.swing.JTextField PressureLimitLowerTextField;
    private javax.swing.JLabel PressureLimitLowerUnitLabel;
    private javax.swing.JLabel PressureLimitUpperLabel;
    private javax.swing.JTextField PressureLimitUpperTextField;
    private javax.swing.JLabel PressureLimitUpperUnitLabel;
    private javax.swing.JLabel QCLimitSettingsLabel;
    private javax.swing.JButton ResetButton;
    private javax.swing.JButton SaveButton;
    private javax.swing.JLabel TemperatureLimitLowerLabel;
    private javax.swing.JTextField TemperatureLimitLowerTextField;
    private javax.swing.JLabel TemperatureLimitUpperLabel;
    private javax.swing.JTextField TemperatureLimitUpperTextField;
    private javax.swing.JLabel TemperaureLimitLowerUnitLabel;
    private javax.swing.JLabel TemperaureLimitUpperUnitLabel;
    private javax.swing.JLabel TimeSeriesPlotOptionsLabel;
    private javax.swing.JCheckBox WdWeightWsCheckBox;
    private javax.swing.JLabel WdWeightWsLabel;
    private javax.swing.JLabel WindSpeedLimitLowerLabel;
    private javax.swing.JTextField WindSpeedLimitLowerTextField;
    private javax.swing.JLabel WindSpeedLimitLowerUnitLabel;
    private javax.swing.JLabel WindSpeedLimitUpperLabel;
    private javax.swing.JTextField WindSpeedLimitUpperTextField;
    private javax.swing.JLabel WindSpeedLimitUpperUnitLabel;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
