/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ametjavagui.METAdvancedForms;

import ametjavagui.MeteorologyForm;

/**
 *
 * @author mmorto01
 */
public class RAOBPlotOptions extends javax.swing.JFrame {

    /**
     * Creates new form RAOBPlotOptions
     */
    
    MeteorologyForm form;
    String script;
    
    public RAOBPlotOptions(MeteorologyForm form, String script) {
        this.form = form;
        this.script = script;
        initComponents();
        System.out.println("Script: " + script);
        if ("Upper-Air: Spatial, Profile, Time Series and Curtain".equals(script)){
            SpatialCheckBox.setSelected(form.spatialm);
            TimeSeriesCheckBox.setSelected(form.tseriesm);
            ProfileMCheckBox.setSelected(form.profm);
            CurtainMCheckBox.setSelected(form.curtainm);
            ProfileNCheckBox.setSelected(form.profn);
            CurtainNCheckBox.setSelected(form.curtainn);
        }
        if ("Upper-Air: Mandatory Spatial Statistics".equals(script)){
            SpatialCheckBox.setSelected(true);
            TimeSeriesCheckBox.setSelected(false);
            ProfileMCheckBox.setSelected(false);
            CurtainMCheckBox.setSelected(false);
            ProfileNCheckBox.setSelected(false);
            CurtainNCheckBox.setSelected(false);
        }
        if ("Upper-Air: Mandatory Time Series Statistics".equals(script)){
            SpatialCheckBox.setSelected(false);
            TimeSeriesCheckBox.setSelected(true);
            ProfileMCheckBox.setSelected(false);
            CurtainMCheckBox.setSelected(false);
            ProfileNCheckBox.setSelected(false);
            CurtainNCheckBox.setSelected(false);
        }
        if ("Upper-Air: Mandatory Profile Statistics".equals(script)){
            SpatialCheckBox.setSelected(false);
            TimeSeriesCheckBox.setSelected(false);
            ProfileMCheckBox.setSelected(true);
            CurtainMCheckBox.setSelected(false);
            ProfileNCheckBox.setSelected(false);
            CurtainNCheckBox.setSelected(false);
        }
        if ("Upper-Air: Mandatory Curtain".equals(script)){
            SpatialCheckBox.setSelected(false);
            TimeSeriesCheckBox.setSelected(false);
            ProfileMCheckBox.setSelected(false);
            CurtainMCheckBox.setSelected(true);
            ProfileNCheckBox.setSelected(false);
            CurtainNCheckBox.setSelected(false);
        }
        if ("Upper-Air: Native Theta / RH Profiles".equals(script)){
            SpatialCheckBox.setSelected(false);
            TimeSeriesCheckBox.setSelected(false);
            ProfileMCheckBox.setSelected(false);
            CurtainMCheckBox.setSelected(false);
            ProfileNCheckBox.setSelected(true);
            CurtainNCheckBox.setSelected(false);
        }
        if ("Upper-Air: Native Curtain".equals(script)){
            SpatialCheckBox.setSelected(false);
            TimeSeriesCheckBox.setSelected(false);
            ProfileMCheckBox.setSelected(false);
            CurtainMCheckBox.setSelected(false);
            ProfileNCheckBox.setSelected(false);
            CurtainNCheckBox.setSelected(true);
        }
        GroupStatCheckBox.setSelected(form.groupstat);
        LayerLowerTextField.setText(form.layer_lower);
        LayerUpperTextField.setText(form.layer_upper);
        ProfileLimitLowerTextField.setText(form.proflim_lower);
        ProfileLimitUpperTextField.setText(form.proflim_upper);
        SpatialThresholdTextField.setText(form.spatial_thresh);
        LevelThresholdTextField.setText(form.level_thresh);
        SoundingThresholdTextField.setText(form.sounding_thresh);
        ProfileNThresholdTextField.setText(form.profilen_thresh);
        UseUserRangeCheckBox.setSelected(form.user_range);
        TempDiffTextField.setText(form.diff_t);        
        RHDiffTextField.setText(form.diff_rh);
        StartHourComboBox.setSelectedIndex(form.hs_index);   
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        RAOBPlotOptionsLabel = new javax.swing.JLabel();
        MandatoryLabel = new javax.swing.JLabel();
        SpatialCheckBox = new javax.swing.JCheckBox();
        TimeSeriesCheckBox = new javax.swing.JCheckBox();
        ProfileMCheckBox = new javax.swing.JCheckBox();
        CurtainMCheckBox = new javax.swing.JCheckBox();
        NativeLabel = new javax.swing.JLabel();
        ProfileNCheckBox = new javax.swing.JCheckBox();
        CurtainNCheckBox = new javax.swing.JCheckBox();
        GroupStatCheckBox = new javax.swing.JCheckBox();
        RAOBPlotOptionsLabel1 = new javax.swing.JLabel();
        LayerLabel = new javax.swing.JLabel();
        LayerLowerTextField = new javax.swing.JTextField();
        LayerUnitsLabel1 = new javax.swing.JLabel();
        LayerUnitsLabel2 = new javax.swing.JLabel();
        LayerUpperTextField = new javax.swing.JTextField();
        ProfileLimitLabel = new javax.swing.JLabel();
        ProfileLimitLowerTextField = new javax.swing.JTextField();
        LayerUnitsLabel3 = new javax.swing.JLabel();
        LayerUnitsLabel4 = new javax.swing.JLabel();
        ProfileLimitUpperTextField = new javax.swing.JTextField();
        SpatialTresholdLabel = new javax.swing.JLabel();
        SpatialThresholdTextField = new javax.swing.JTextField();
        LevelThresholdLabel = new javax.swing.JLabel();
        LevelThresholdTextField = new javax.swing.JTextField();
        SoundingThresholdLabel = new javax.swing.JLabel();
        SoundingThresholdTextField = new javax.swing.JTextField();
        RAOBPlotOptionsLabel2 = new javax.swing.JLabel();
        ProfileNThresholdLabel = new javax.swing.JLabel();
        ProfileNThresholdTextField = new javax.swing.JTextField();
        UseUserRangeCheckBox = new javax.swing.JCheckBox();
        TempDiffLabel = new javax.swing.JLabel();
        TempDiffTextField = new javax.swing.JTextField();
        TempUnitsLabel = new javax.swing.JLabel();
        RHDiffLabel = new javax.swing.JLabel();
        RHDiffTextField = new javax.swing.JTextField();
        RHUnitsLabel = new javax.swing.JLabel();
        StartHourLabel = new javax.swing.JLabel();
        StartHourComboBox = new javax.swing.JComboBox<>();
        StartHourUInitLabel = new javax.swing.JLabel();
        SaveButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        ResetButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Upper-Air Analysis Options");
        setAlwaysOnTop(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        RAOBPlotOptionsLabel.setBackground(new java.awt.Color(255, 255, 255));
        RAOBPlotOptionsLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        RAOBPlotOptionsLabel.setForeground(new java.awt.Color(0, 63, 105));
        RAOBPlotOptionsLabel.setText("Upper-Air Analysis Options");

        MandatoryLabel.setBackground(new java.awt.Color(255, 255, 255));
        MandatoryLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        MandatoryLabel.setForeground(new java.awt.Color(0, 112, 185));
        MandatoryLabel.setText("Mandatory Level Data");

        SpatialCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        SpatialCheckBox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        SpatialCheckBox.setForeground(new java.awt.Color(0, 112, 185));
        SpatialCheckBox.setSelected(true);
        SpatialCheckBox.setText("Spatial Statistics");

        TimeSeriesCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        TimeSeriesCheckBox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TimeSeriesCheckBox.setForeground(new java.awt.Color(0, 112, 185));
        TimeSeriesCheckBox.setText("Time Series Statistics");

        ProfileMCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        ProfileMCheckBox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ProfileMCheckBox.setForeground(new java.awt.Color(0, 112, 185));
        ProfileMCheckBox.setSelected(true);
        ProfileMCheckBox.setText("Profile Statistics");

        CurtainMCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        CurtainMCheckBox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        CurtainMCheckBox.setForeground(new java.awt.Color(0, 112, 185));
        CurtainMCheckBox.setText("Curtain");

        NativeLabel.setBackground(new java.awt.Color(255, 255, 255));
        NativeLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        NativeLabel.setForeground(new java.awt.Color(0, 112, 185));
        NativeLabel.setText("Native Level Data");

        ProfileNCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        ProfileNCheckBox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ProfileNCheckBox.setForeground(new java.awt.Color(0, 112, 185));
        ProfileNCheckBox.setText("Theta / RH Profiles (for specified start date)");

        CurtainNCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        CurtainNCheckBox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        CurtainNCheckBox.setForeground(new java.awt.Color(0, 112, 185));
        CurtainNCheckBox.setText("Curtain");

        GroupStatCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        GroupStatCheckBox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        GroupStatCheckBox.setForeground(new java.awt.Color(0, 112, 185));
        GroupStatCheckBox.setText("Combine data from all sites to create average model-to-observation data set.");

        RAOBPlotOptionsLabel1.setBackground(new java.awt.Color(255, 255, 255));
        RAOBPlotOptionsLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        RAOBPlotOptionsLabel1.setForeground(new java.awt.Color(0, 63, 105));
        RAOBPlotOptionsLabel1.setText("Pressure Layer and Statistics Settings");

        LayerLabel.setBackground(new java.awt.Color(255, 255, 255));
        LayerLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        LayerLabel.setForeground(new java.awt.Color(0, 112, 185));
        LayerLabel.setText("Pressure layer range for Upper-Air Analysis:");

        LayerLowerTextField.setBackground(new java.awt.Color(191, 182, 172));
        LayerLowerTextField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        LayerLowerTextField.setForeground(new java.awt.Color(0, 63, 105));
        LayerLowerTextField.setText("1000");
        LayerLowerTextField.setMaximumSize(new java.awt.Dimension(65, 23));
        LayerLowerTextField.setMinimumSize(new java.awt.Dimension(65, 23));
        LayerLowerTextField.setPreferredSize(new java.awt.Dimension(65, 23));

        LayerUnitsLabel1.setBackground(new java.awt.Color(255, 255, 255));
        LayerUnitsLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        LayerUnitsLabel1.setForeground(new java.awt.Color(0, 112, 185));
        LayerUnitsLabel1.setText("mb -");

        LayerUnitsLabel2.setBackground(new java.awt.Color(255, 255, 255));
        LayerUnitsLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        LayerUnitsLabel2.setForeground(new java.awt.Color(0, 112, 185));
        LayerUnitsLabel2.setText("mb");

        LayerUpperTextField.setBackground(new java.awt.Color(191, 182, 172));
        LayerUpperTextField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        LayerUpperTextField.setForeground(new java.awt.Color(0, 63, 105));
        LayerUpperTextField.setText("200");
        LayerUpperTextField.setMaximumSize(new java.awt.Dimension(65, 23));
        LayerUpperTextField.setMinimumSize(new java.awt.Dimension(65, 23));
        LayerUpperTextField.setPreferredSize(new java.awt.Dimension(65, 23));

        ProfileLimitLabel.setBackground(new java.awt.Color(255, 255, 255));
        ProfileLimitLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ProfileLimitLabel.setForeground(new java.awt.Color(0, 112, 185));
        ProfileLimitLabel.setText("Pressure layer range for Upper-Air Plotting:");

        ProfileLimitLowerTextField.setBackground(new java.awt.Color(191, 182, 172));
        ProfileLimitLowerTextField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ProfileLimitLowerTextField.setForeground(new java.awt.Color(0, 63, 105));
        ProfileLimitLowerTextField.setText("1000");
        ProfileLimitLowerTextField.setMaximumSize(new java.awt.Dimension(65, 23));
        ProfileLimitLowerTextField.setMinimumSize(new java.awt.Dimension(65, 23));
        ProfileLimitLowerTextField.setPreferredSize(new java.awt.Dimension(65, 23));

        LayerUnitsLabel3.setBackground(new java.awt.Color(255, 255, 255));
        LayerUnitsLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        LayerUnitsLabel3.setForeground(new java.awt.Color(0, 112, 185));
        LayerUnitsLabel3.setText("mb -");

        LayerUnitsLabel4.setBackground(new java.awt.Color(255, 255, 255));
        LayerUnitsLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        LayerUnitsLabel4.setForeground(new java.awt.Color(0, 112, 185));
        LayerUnitsLabel4.setText("mb");

        ProfileLimitUpperTextField.setBackground(new java.awt.Color(191, 182, 172));
        ProfileLimitUpperTextField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ProfileLimitUpperTextField.setForeground(new java.awt.Color(0, 63, 105));
        ProfileLimitUpperTextField.setText("200");
        ProfileLimitUpperTextField.setMaximumSize(new java.awt.Dimension(65, 23));
        ProfileLimitUpperTextField.setMinimumSize(new java.awt.Dimension(65, 23));
        ProfileLimitUpperTextField.setPreferredSize(new java.awt.Dimension(65, 23));

        SpatialTresholdLabel.setBackground(new java.awt.Color(255, 255, 255));
        SpatialTresholdLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        SpatialTresholdLabel.setForeground(new java.awt.Color(0, 112, 185));
        SpatialTresholdLabel.setText("Sample size threshold for Spatial Layer average statistics:");

        SpatialThresholdTextField.setBackground(new java.awt.Color(191, 182, 172));
        SpatialThresholdTextField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        SpatialThresholdTextField.setForeground(new java.awt.Color(0, 63, 105));
        SpatialThresholdTextField.setText("5");
        SpatialThresholdTextField.setMaximumSize(new java.awt.Dimension(65, 23));
        SpatialThresholdTextField.setMinimumSize(new java.awt.Dimension(65, 23));
        SpatialThresholdTextField.setPreferredSize(new java.awt.Dimension(65, 23));

        LevelThresholdLabel.setBackground(new java.awt.Color(255, 255, 255));
        LevelThresholdLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        LevelThresholdLabel.setForeground(new java.awt.Color(0, 112, 185));
        LevelThresholdLabel.setText("Sample size threshold for Pressure Level statistics:");

        LevelThresholdTextField.setBackground(new java.awt.Color(191, 182, 172));
        LevelThresholdTextField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        LevelThresholdTextField.setForeground(new java.awt.Color(0, 63, 105));
        LevelThresholdTextField.setText("5");
        LevelThresholdTextField.setMaximumSize(new java.awt.Dimension(65, 23));
        LevelThresholdTextField.setMinimumSize(new java.awt.Dimension(65, 23));
        LevelThresholdTextField.setPreferredSize(new java.awt.Dimension(65, 23));

        SoundingThresholdLabel.setBackground(new java.awt.Color(255, 255, 255));
        SoundingThresholdLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        SoundingThresholdLabel.setForeground(new java.awt.Color(0, 112, 185));
        SoundingThresholdLabel.setText("Sample size threshold for number of Sounding:");

        SoundingThresholdTextField.setBackground(new java.awt.Color(191, 182, 172));
        SoundingThresholdTextField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        SoundingThresholdTextField.setForeground(new java.awt.Color(0, 63, 105));
        SoundingThresholdTextField.setText("5");
        SoundingThresholdTextField.setMaximumSize(new java.awt.Dimension(65, 23));
        SoundingThresholdTextField.setMinimumSize(new java.awt.Dimension(65, 23));
        SoundingThresholdTextField.setPreferredSize(new java.awt.Dimension(65, 23));

        RAOBPlotOptionsLabel2.setBackground(new java.awt.Color(255, 255, 255));
        RAOBPlotOptionsLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        RAOBPlotOptionsLabel2.setForeground(new java.awt.Color(0, 63, 105));
        RAOBPlotOptionsLabel2.setText("Native Level Plotting Options");

        ProfileNThresholdLabel.setBackground(new java.awt.Color(255, 255, 255));
        ProfileNThresholdLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ProfileNThresholdLabel.setForeground(new java.awt.Color(0, 112, 185));
        ProfileNThresholdLabel.setText("Sample size threshold for minimum levels needed for Native Profile Plot:");

        ProfileNThresholdTextField.setBackground(new java.awt.Color(191, 182, 172));
        ProfileNThresholdTextField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ProfileNThresholdTextField.setForeground(new java.awt.Color(0, 63, 105));
        ProfileNThresholdTextField.setText("5");
        ProfileNThresholdTextField.setMaximumSize(new java.awt.Dimension(65, 23));
        ProfileNThresholdTextField.setMinimumSize(new java.awt.Dimension(65, 23));
        ProfileNThresholdTextField.setPreferredSize(new java.awt.Dimension(65, 23));

        UseUserRangeCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        UseUserRangeCheckBox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        UseUserRangeCheckBox.setForeground(new java.awt.Color(0, 112, 185));
        UseUserRangeCheckBox.setSelected(true);
        UseUserRangeCheckBox.setText("Use User set differnece ranges for Native Curtain Plots.");

        TempDiffLabel.setBackground(new java.awt.Color(255, 255, 255));
        TempDiffLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TempDiffLabel.setForeground(new java.awt.Color(0, 112, 185));
        TempDiffLabel.setText("Difference range for Temperature in Native Curtain Plots:       +/-");

        TempDiffTextField.setBackground(new java.awt.Color(191, 182, 172));
        TempDiffTextField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TempDiffTextField.setForeground(new java.awt.Color(0, 63, 105));
        TempDiffTextField.setText("5");
        TempDiffTextField.setMaximumSize(new java.awt.Dimension(65, 23));
        TempDiffTextField.setMinimumSize(new java.awt.Dimension(65, 23));
        TempDiffTextField.setPreferredSize(new java.awt.Dimension(65, 23));

        TempUnitsLabel.setBackground(new java.awt.Color(255, 255, 255));
        TempUnitsLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TempUnitsLabel.setForeground(new java.awt.Color(0, 112, 185));
        TempUnitsLabel.setText("K");

        RHDiffLabel.setBackground(new java.awt.Color(255, 255, 255));
        RHDiffLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        RHDiffLabel.setForeground(new java.awt.Color(0, 112, 185));
        RHDiffLabel.setText("Differnece range for Relative Humidity in Native Curtain Plots: +/-");

        RHDiffTextField.setBackground(new java.awt.Color(191, 182, 172));
        RHDiffTextField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        RHDiffTextField.setForeground(new java.awt.Color(0, 63, 105));
        RHDiffTextField.setText("50");
        RHDiffTextField.setMaximumSize(new java.awt.Dimension(65, 23));
        RHDiffTextField.setMinimumSize(new java.awt.Dimension(65, 23));
        RHDiffTextField.setPreferredSize(new java.awt.Dimension(65, 23));

        RHUnitsLabel.setBackground(new java.awt.Color(255, 255, 255));
        RHUnitsLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        RHUnitsLabel.setForeground(new java.awt.Color(0, 112, 185));
        RHUnitsLabel.setText("%");

        StartHourLabel.setBackground(new java.awt.Color(255, 255, 255));
        StartHourLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        StartHourLabel.setForeground(new java.awt.Color(0, 112, 185));
        StartHourLabel.setText("Hour for Native Level Model-Obs Profile Plot:");

        StartHourComboBox.setBackground(new java.awt.Color(191, 182, 172));
        StartHourComboBox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        StartHourComboBox.setForeground(new java.awt.Color(0, 63, 105));
        StartHourComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "06", "12", "18", "" }));

        StartHourUInitLabel.setBackground(new java.awt.Color(255, 255, 255));
        StartHourUInitLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        StartHourUInitLabel.setForeground(new java.awt.Color(0, 112, 185));
        StartHourUInitLabel.setText("UTC");

        SaveButton.setBackground(new java.awt.Color(0, 63, 105));
        SaveButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        SaveButton.setForeground(new java.awt.Color(191, 182, 172));
        SaveButton.setText("Save");
        SaveButton.setMaximumSize(new java.awt.Dimension(100, 26));
        SaveButton.setMinimumSize(new java.awt.Dimension(75, 26));
        SaveButton.setPreferredSize(new java.awt.Dimension(75, 26));
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        CancelButton.setBackground(new java.awt.Color(0, 63, 105));
        CancelButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        CancelButton.setForeground(new java.awt.Color(191, 182, 172));
        CancelButton.setText("Cancel");
        CancelButton.setMaximumSize(new java.awt.Dimension(100, 26));
        CancelButton.setMinimumSize(new java.awt.Dimension(90, 26));
        CancelButton.setPreferredSize(new java.awt.Dimension(90, 26));
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        ResetButton.setBackground(new java.awt.Color(0, 63, 105));
        ResetButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ResetButton.setForeground(new java.awt.Color(191, 182, 172));
        ResetButton.setText("Reset");
        ResetButton.setMaximumSize(new java.awt.Dimension(100, 26));
        ResetButton.setMinimumSize(new java.awt.Dimension(100, 26));
        ResetButton.setPreferredSize(new java.awt.Dimension(80, 26));
        ResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(RAOBPlotOptionsLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(GroupStatCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(UseUserRangeCheckBox)
                                    .addComponent(TimeSeriesCheckBox)
                                    .addComponent(ProfileMCheckBox)
                                    .addComponent(CurtainMCheckBox)
                                    .addComponent(ProfileNCheckBox)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(ProfileLimitLabel)
                                        .addGap(17, 17, 17)
                                        .addComponent(ProfileLimitLowerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(LayerUnitsLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ProfileLimitUpperTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(LayerUnitsLabel4))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(ProfileNThresholdLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ProfileNThresholdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(SpatialCheckBox)
                                    .addComponent(RAOBPlotOptionsLabel)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(LayerLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(LayerLowerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(LayerUnitsLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(LayerUpperTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(LayerUnitsLabel2))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(SpatialTresholdLabel)
                                            .addComponent(LevelThresholdLabel)
                                            .addComponent(SoundingThresholdLabel))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(SoundingThresholdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(LevelThresholdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(SpatialThresholdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(StartHourLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(StartHourComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(RHDiffLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TempDiffLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(RHDiffTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(RHUnitsLabel))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(TempDiffTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(TempUnitsLabel))
                                            .addComponent(StartHourUInitLabel))))
                                .addGap(0, 117, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ResetButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(SaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(CancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NativeLabel)
                            .addComponent(MandatoryLabel)
                            .addComponent(CurtainNCheckBox)
                            .addComponent(RAOBPlotOptionsLabel1))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RAOBPlotOptionsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MandatoryLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SpatialCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TimeSeriesCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ProfileMCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CurtainMCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NativeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ProfileNCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CurtainNCheckBox)
                .addGap(18, 18, 18)
                .addComponent(RAOBPlotOptionsLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(GroupStatCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LayerLabel)
                    .addComponent(LayerLowerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LayerUnitsLabel1)
                    .addComponent(LayerUpperTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LayerUnitsLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LayerUnitsLabel3)
                        .addComponent(ProfileLimitUpperTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LayerUnitsLabel4))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ProfileLimitLabel)
                        .addComponent(ProfileLimitLowerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SpatialTresholdLabel)
                    .addComponent(SpatialThresholdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LevelThresholdLabel)
                    .addComponent(LevelThresholdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SoundingThresholdLabel)
                    .addComponent(SoundingThresholdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(RAOBPlotOptionsLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProfileNThresholdLabel)
                    .addComponent(ProfileNThresholdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(UseUserRangeCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TempDiffLabel)
                    .addComponent(TempDiffTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TempUnitsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RHDiffLabel)
                    .addComponent(RHDiffTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RHUnitsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StartHourLabel)
                    .addComponent(StartHourComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StartHourUInitLabel))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ResetButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        form.spatial_m = form.checkBoxFormat(SpatialCheckBox);
        form.spatialm = SpatialCheckBox.isSelected();
        form.t_series_m = form.checkBoxFormat(TimeSeriesCheckBox);
        form.tseriesm = TimeSeriesCheckBox.isSelected();
        form.prof_m = form.checkBoxFormat(ProfileMCheckBox);
        form.profm = ProfileMCheckBox.isSelected();
        form.curtain_m = form.checkBoxFormat(CurtainMCheckBox);
        form.curtainm = CurtainMCheckBox.isSelected();
        form.prof_n = form.checkBoxFormat(ProfileNCheckBox);
        form.profn = ProfileNCheckBox.isSelected();
        form.curtain_n = form.checkBoxFormat(CurtainNCheckBox);
        form.curtainn = CurtainNCheckBox.isSelected();
        form.group_stat = form.checkBoxFormat(GroupStatCheckBox);
        form.groupstat= GroupStatCheckBox.isSelected();
        form.layer_lower = form.numNullFormat(LayerLowerTextField.getText());
        form.layer_upper = form.numNullFormat(LayerUpperTextField.getText());
        form.proflim_lower = form.numNullFormat(ProfileLimitLowerTextField.getText());
        form.proflim_upper = form.numNullFormat(ProfileLimitUpperTextField.getText());
        form.spatial_thresh = form.numNullFormat(SpatialThresholdTextField.getText());
        form.level_thresh = form.numNullFormat(LevelThresholdTextField.getText());
        form.sounding_thresh = form.numNullFormat(SoundingThresholdTextField.getText());
        form.profilen_thresh = form.numNullFormat(ProfileNThresholdTextField.getText());
        form.use_user_range = form.checkBoxFormat(UseUserRangeCheckBox);
        form.user_range = UseUserRangeCheckBox.isSelected();
        form.diff_t = form.numNullFormat(TempDiffTextField.getText());
        form.diff_rh = form.numNullFormat(RHDiffTextField.getText());
        form.hs = form.numNullFormat(StartHourComboBox.getSelectedItem().toString());
        form.hs_index = StartHourComboBox.getSelectedIndex();
        System.out.println("Upper-Air Analysis Options Saved");
        setVisible(false);
        dispose();
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void ResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetButtonActionPerformed
        SpatialCheckBox.setSelected(form.spatialm_reset);
        TimeSeriesCheckBox.setSelected(form.tseriesm_reset);
        ProfileMCheckBox.setSelected(form.profm_reset);
        CurtainMCheckBox.setSelected(form.curtainm_reset);
        ProfileNCheckBox.setSelected(form.profn_reset);
        CurtainNCheckBox.setSelected(form.curtainn_reset);
        GroupStatCheckBox.setSelected(form.groupstat_reset);
        LayerLowerTextField.setText(form.layer_lower_reset);
        LayerUpperTextField.setText(form.layer_upper_reset);
        ProfileLimitLowerTextField.setText(form.proflim_lower_reset);
        ProfileLimitUpperTextField.setText(form.proflim_upper_reset);
        SpatialThresholdTextField.setText(form.spatial_thresh_reset);
        LevelThresholdTextField.setText(form.level_thresh_reset);
        SoundingThresholdTextField.setText(form.sounding_thresh_reset);
        ProfileNThresholdTextField.setText(form.profilen_thresh_reset);
        UseUserRangeCheckBox.setSelected(form.user_range_reset);
        TempDiffTextField.setText(form.diff_t_reset);        
        RHDiffTextField.setText(form.diff_rh_reset);
        StartHourComboBox.setSelectedIndex(0);
        System.out.println("Upper-Air Analysis Options Reset to Default Values");
    }//GEN-LAST:event_ResetButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton;
    private javax.swing.JCheckBox CurtainMCheckBox;
    private javax.swing.JCheckBox CurtainNCheckBox;
    private javax.swing.JCheckBox GroupStatCheckBox;
    private javax.swing.JLabel LayerLabel;
    private javax.swing.JTextField LayerLowerTextField;
    private javax.swing.JLabel LayerUnitsLabel1;
    private javax.swing.JLabel LayerUnitsLabel2;
    private javax.swing.JLabel LayerUnitsLabel3;
    private javax.swing.JLabel LayerUnitsLabel4;
    private javax.swing.JTextField LayerUpperTextField;
    private javax.swing.JLabel LevelThresholdLabel;
    private javax.swing.JTextField LevelThresholdTextField;
    private javax.swing.JLabel MandatoryLabel;
    private javax.swing.JLabel NativeLabel;
    private javax.swing.JLabel ProfileLimitLabel;
    private javax.swing.JTextField ProfileLimitLowerTextField;
    private javax.swing.JTextField ProfileLimitUpperTextField;
    private javax.swing.JCheckBox ProfileMCheckBox;
    private javax.swing.JCheckBox ProfileNCheckBox;
    private javax.swing.JLabel ProfileNThresholdLabel;
    private javax.swing.JTextField ProfileNThresholdTextField;
    private javax.swing.JLabel RAOBPlotOptionsLabel;
    private javax.swing.JLabel RAOBPlotOptionsLabel1;
    private javax.swing.JLabel RAOBPlotOptionsLabel2;
    private javax.swing.JLabel RHDiffLabel;
    private javax.swing.JTextField RHDiffTextField;
    private javax.swing.JLabel RHUnitsLabel;
    private javax.swing.JButton ResetButton;
    private javax.swing.JButton SaveButton;
    private javax.swing.JLabel SoundingThresholdLabel;
    private javax.swing.JTextField SoundingThresholdTextField;
    private javax.swing.JCheckBox SpatialCheckBox;
    private javax.swing.JTextField SpatialThresholdTextField;
    private javax.swing.JLabel SpatialTresholdLabel;
    private javax.swing.JComboBox<String> StartHourComboBox;
    private javax.swing.JLabel StartHourLabel;
    private javax.swing.JLabel StartHourUInitLabel;
    private javax.swing.JLabel TempDiffLabel;
    private javax.swing.JTextField TempDiffTextField;
    private javax.swing.JLabel TempUnitsLabel;
    private javax.swing.JCheckBox TimeSeriesCheckBox;
    private javax.swing.JCheckBox UseUserRangeCheckBox;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
