################################################################
### THIS FILE CONTAINS CODE TO CREATE AN OBS OVERLAY FILE FOR PAVE.
### The program requires hourly data (AQS, SEARCH, CASTNet) data in
### order to create the PAVE overlay file.  The script is given a time
### period to query the database for, and then creates a data file that
### can be used the the program bldoverlay.exe to create the overlay
### file.  
### The time period of the query should be limited to about a month for
### AQS network if querying the entire domain due to memory limits.
################################################################

## get some environmental variables and setup some directories
ametbase        <- Sys.getenv("AMETBASE")        # base directory of AMET
dbase           <- Sys.getenv("AMET_DATABASE")      # AMET database
ametR           <- paste(ametbase,"/R_analysis_code",sep="")      # R directory
ametRinput      <- Sys.getenv("AMETRINPUT")  # input file for this script
ametptype       <- Sys.getenv("AMET_PTYPE")   # Prefered output type
## Check for output directory via namelist and AMET_OUT env var, if not specified in namelist
## and not specified via AMET_OUT, then set figdir to the current directory
if(!exists("figdir") )                         { figdir <- Sys.getenv("AMET_OUT")       }
if( length(unlist(strsplit(figdir,""))) == 0 ) { figdir <- "./"                 }

## source some configuration files, AMET libs, and input
source(paste(ametbase,"/configure/amet-config.R",sep=""))
source(paste(ametR,"/AQ_Misc_Functions.R",sep=""))     # Miscellanous AMET R-functions file
source(ametRinput)                                     # Anaysis configuration/input file

## Load Required Libraries 
if(!require(RMySQL)){stop("Required Package RMySQL was not loaded")}
if(!require(date)){stop("Required Package date was not loaded")}

mysql <- list(login=root_login, passwd=root_pass, server=mysql_server, dbase=dbase, maxrec=maxrec)

################################################
## Set output names and remove existing files ##
################################################
filename_overlay 	<- paste(run_name1,"_",pid,"_overlay.ncf; export OUTFILE",sep="")

filename_out            <- paste(figdir,"ozone_overlay_input.csv",sep="/")              # input file generated by this R script to be used by bldoverlay.exe
filename_script         <- paste(figdir,"runOBS.sh",sep="/")                            # script to run that sets environmental variables and calls bldoverlay.exe
filename_overlay	<- paste(figdir,filename_overlay,sep="/")
#################################################

{
   if (overlay_opt == 1) {
      overlay_type = "HOURLY"
   }
   else if (overlay_opt == 2) {
      overlay_type = "DAILY"
   }
   else if (overlay_opt == 3) {
     overlay_type = "1HRMAX"
   }
   else {
      overlay_type = "8HRMAX"
   }
}

j <- 1							# only use first network (not coded for multiple networks)
network		<-network_names[[j]]				# set network 
run_name	<- run_name1		# Set run_name to run_name1 since only using one simulation
criteria <- paste(" WHERE d.",species,"_ob is not NULL and d.network='",network,"' ",query,sep="")          # Set part of the MYSQL query
check_POCode        <- paste("select * from information_schema.COLUMNS where TABLE_NAME = '",run_name1,"' and COLUMN_NAME = 'POCode';",sep="")
query_table_info.df <-db_Query(check_POCode,mysql)
{
   if (length(query_table_info.df$COLUMN_NAME) == 0) {        # Check to see if POCode column exists or not
      qs <- paste("SELECT d.network,d.stat_id,s.num_stat_id,d.lat,d.lon,d.ob_dates,DATE_FORMAT(d.ob_dates,'%Y%j'),d.ob_hour,d.",species,"_ob,d.",species,"_mod from ",run_name," as d, site_metadata as s",criteria," ORDER BY ob_dates,ob_hour",sep="")      # Set the rest of the MYSQL query
      aqdat.df<-db_Query(qs,mysql)
      aqdat.df$POCode <- 1
   }
   else {
      qs <- paste("SELECT d.network,d.stat_id,s.num_stat_id,d.lat,d.lon,d.ob_dates,DATE_FORMAT(d.ob_dates,'%Y%j'),d.ob_hour,d.",species,"_ob,d.",species,"_mod, d.POCode from ",run_name," as d, site_metadata as s",criteria," ORDER BY ob_dates,ob_hour",sep="")
      aqdat.df<-db_Query(qs,mysql)
   }
}
aqdat.df$stat_id <- paste(aqdat.df$stat_id,aqdat.df$POCode,sep='')      # Create unique site using site ID and PO Code

year_day <- aqdat.df$"DATE_FORMAT(d.ob_dates,'%Y%j')"

{
   if (network == "CASTNet_hourly") {
      output <- paste(year_day,aqdat.df$ob_hour,aqdat.df$lon,aqdat.df$lat,aqdat.df[,9],sep=",")	# set output to be written 
      write.table(output, file=filename_out, append=F ,sep="",col.names=F,row.names=F,quote=F)		# write data to be used by bldoverlay.exe
   }
   else {
      output <- paste(year_day,aqdat.df$ob_hour,aqdat.df$num_stat_id,aqdat.df$lon,aqdat.df$lat,aqdat.df[,9],sep=",")    # set output to be written 
      write.table(output, file=filename_out, append=F ,sep="",col.names=F,row.names=F,quote=F)             # write data to be used by bldoverlay.exe
   }
}
#################################

### Create script to be run ###
write("#!/bin/sh", file=filename_script, append=F)
write("FILETYPE=OBS; export FILETYPE", file=filename_script, append=T)
write(paste("INFILE=",filename_out,"; export INFILE",sep=""), file=filename_script, append=T)
write("SPECIES=\"O3\"; export SPECIES", file=filename_script, append=T)
write("UNITS=\"ppb\"; export UNITS", file=filename_script, append=T)
write(paste("OLAYTYPE=",overlay_type,"; export OLAYTYPE",sep=""), file=filename_script, append=T)
write(paste("OUTFILE=",filename_overlay,sep=""), file=filename_script, append=T)
write(Bldoverlay_exe, file=filename_script, append=T)
#######################

system_command <- paste("chmod +x",filename_script)
#system("chmod +x runOBS.sh")					# give execute permissions to script that is generated
system(system_command)
system_command <- paste("./",filename_script,sep="")
system(system_command)  
