header <- "
############################## OVERLAY FILE #################################
### AMET Code: AQ_Overlay_File.R
###
### THIS FILE CONTAINS CODE TO CREATE AN OBS OVERLAY FILE FOR PAVE or VERDI. The
### program  requires hourly data (AQS, SEARCH, CASTNet) data in order to create
### the overlay file.  The script is given a time period to query the database for,
### and then creates a data file that can be used the the program bldoverlay.exe 
### to create the overlay file.  
###
### The time period of the query should be limited to about a month for AQS network
### if querying the entire domain due to memory limits.
###
### Last updated by Wyat Appel: Feb 2022
################################################################
"

## get some environmental variables and setup some directories
ametbase        <- Sys.getenv("AMETBASE")        		# base directory of AMET
ametR           <- paste(ametbase,"/R_analysis_code",sep="")    # R directory

## source miscellaneous R input file 
source(paste(ametR,"/AQ_Misc_Functions.R",sep=""))     # Miscellanous AMET R-functions file

## Load Required Libraries 
#if(!require(date)){stop("Required Package date was not loaded")}

################################################
## Set output names and remove existing files ##
################################################
filename_overlay 	<- paste(run_name1,"_",pid,"_overlay.ncf; export OUTFILE",sep="")

filename_out            <- paste(figdir,"ozone_overlay_input.csv",sep="/")              # input file generated by this R script to be used by bldoverlay.exe
filename_script         <- paste(figdir,"runOBS.sh",sep="/")                            # script to run that sets environmental variables and calls bldoverlay.exe
filename_overlay	<- paste(figdir,filename_overlay,sep="/")
#################################################

{
   if (overlay_opt == 1) {
      overlay_type = "HOURLY"
   }
   else if (overlay_opt == 2) {
      overlay_type = "DAILY"
   }
   else if (overlay_opt == 3) {
     overlay_type = "1HRMAX"
   }
   else {
      overlay_type = "8HRMAX"
   }
}

j <- 1							# only use first network (not coded for multiple networks)
network		<- network_names[[j]]				# set network 
run_name	<- run_name1		# Set run_name to run_name1 since only using one simulation
query_result    <- query_dbase(run_name1,network,species,orderby=c("ob_dates","ob_hour"))
aqdat.df	<- query_result[[1]]
data_exists     <- query_result[[2]]
if (data_exists == "y") { units <- query_result[[3]] }

#print(aqdat.df$ob_dates)
tmp <- as.Date(aqdat.df$ob_dates, format = "%Y-%m-%d")
year_day <- format(tmp, "%Y%j")
#year_day <- aqdat.df$"DATE_FORMAT(ob_dates,'%Y%j')"
#print(year_day)

ob_col_name <- paste(species,"_ob",sep="")
{
   if (network == "CASTNet_hourly") {
      output <- paste(year_day,aqdat.df$ob_hour,aqdat.df$lon,aqdat.df$lat,aqdat.df[[ob_col_name]],sep=",")	# set output to be written 
      write.table(output, file=filename_out, append=F ,sep="",col.names=F,row.names=F,quote=F)		# write data to be used by bldoverlay.exe
   }
   else {
      output <- paste(year_day,aqdat.df$ob_hour,aqdat.df$num_stat_id,aqdat.df$lon,aqdat.df$lat,aqdat.df[[ob_col_name]],sep=",")    # set output to be written 
      write.table(output, file=filename_out, append=F ,sep="",col.names=F,row.names=F,quote=F)             # write data to be used by bldoverlay.exe
   }
}
#################################

### Create script to be run ###
write("#!/bin/sh", file=filename_script, append=F)
write("FILETYPE=OBS; export FILETYPE", file=filename_script, append=T)
write(paste("INFILE=",filename_out,"; export INFILE",sep=""), file=filename_script, append=T)
#write("SPECIES=\"O3\"; export SPECIES", file=filename_script, append=T)
write(paste("SPECIES=\"",species,"\"; export SPECIES",sep=""), file=filename_script, append=T)
#write("UNITS=\"ppb\"; export UNITS", file=filename_script, append=T)
write(paste("UNITS=\"",units,"\"; export UNITS",sep=""), file=filename_script, append=T)
write(paste("OLAYTYPE=",overlay_type,"; export OLAYTYPE",sep=""), file=filename_script, append=T)
write(paste("OUTFILE=",filename_overlay,sep=""), file=filename_script, append=T)
write(Bldoverlay_exe, file=filename_script, append=T)
#######################

system_command <- paste("chmod +x",filename_script)
#system("chmod +x runOBS.sh")					# give execute permissions to script that is generated
system(system_command)
system_command <- paste("./",filename_script,sep="")
system(system_command)  
