#! /bin/csh

# Main setting is AMETBASE as location of main AMET distribution
setenv AMETBASE /USERS/DESIRED/AMET/LOCATION 

###########################################################
# User's System settings for libraries required by AMET
# These are unique to US EPA Atmos supercomputer
# but provided as an example. If a user's environ.
# is set, these may not be required.
###########################################################
#module purge
# For R with Leaflets, prism, etc
module load intel/21.4
module load R/4.1.2

# for ncdf4
module load netcdf-4.8.1/intel-21
module load hdf5-1.10.8/intel-21
module load udunits-2.2.28/intel-21

# NCO setup
#module unload nco-4.7.3/intel-18.0
module load nco-5.0.4/intel-21

# for RGDAL, Leaflets raster
module load gdal-3.3.3/intel-21
module load proj-7.2.1/intel-21

module load geos/3.8.1
module load pandoc

module list
################################

echo "Finished loading AMET GUI modules"

setenv AMETGUI ${AMETBASE}/AMETGUI
cd $AMETGUI 
echo "Lauching the AMET GUI..."
/usr/bin/java -XX:+UseParallelGC -XX:ParallelGCThreads=1 -Duser.home=/home/${USER} -Xmx1000M -jar ${AMETGUI}/dist/AMETJavaGUI.jar &

