/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ametjavagui;

import java.awt.Color;
import java.awt.Desktop;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.io.File;
import java.io.IOException;

/**
 *
 * @author mmorto01
 */
public class OutputWindowAQ extends javax.swing.JFrame {
    
    int line = 0;
    javax.swing.JLabel[] labels = new javax.swing.JLabel[16];
    
    final Color COLOR_NORMAL = new Color(0,122,185);
    final Color COLOR_ACTIVE = new Color(0,63,105);
    
    AirQualityForm form;

    /**
     * Creates new form OutputWindow
     */
    public OutputWindowAQ(AirQualityForm form) {
        this.form = form;
        initComponents();
        jTextArea1.setText(form.query);
        jTextArea2.setText(form.file_path);
        jLabel2.setText("Program Output (" + form.run_program + ")");
        
        System.out.println(outLabel0.getText());
        labels[0] = outLabel0;
        labels[1] = outLabel1;
        labels[2] = outLabel2;
        labels[3] = outLabel3;
        labels[4] = outLabel4;
        labels[5] = outLabel5;
        labels[6] = outLabel6;
        labels[7] = outLabel7;
        labels[8] = outLabel8;
        labels[9] = outLabel9;
        labels[10] = outLabel10;
        labels[11] = outLabel11;
        
    }
    
    public void newFile(String link, String name) {
        //see if file was created
        File myFile = new File(link);
        if (myFile.exists()) {
            labels[line].setText(name);
            labels[line].setForeground(COLOR_NORMAL);


            labels[line].addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    evt.getComponent().setForeground(COLOR_ACTIVE);
                    outputEvent(evt, link);
                }
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    evt.getComponent().setForeground(new java.awt.Color(38,161,70));
                }
                public void mouseExited(java.awt.event.MouseEvent evt) {
                    evt.getComponent().setForeground(COLOR_NORMAL);
                }
            });
            line++;
        } else {
            System.out.println("File " + name + " not found!"); 
        }
    }
    
    public void checkIfSuccess() {
        if (outLabel0.getText().equals("-")) {
            outLabel0.setText("Error with creating the output files");
        }
    }
    
    private void outputEvent(java.awt.event.MouseEvent evt, String link) {
        System.out.println("clicked!");
        try {
            File myFile = new File(link);
            Desktop.getDesktop().open(myFile);
        } catch (IOException e) {
            System.out.println("File does not exist");
        }  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        outLabel0 = new javax.swing.JLabel();
        outLabel1 = new javax.swing.JLabel();
        outLabel2 = new javax.swing.JLabel();
        outLabel3 = new javax.swing.JLabel();
        outLabel4 = new javax.swing.JLabel();
        outLabel5 = new javax.swing.JLabel();
        outLabel6 = new javax.swing.JLabel();
        outLabel7 = new javax.swing.JLabel();
        outLabel8 = new javax.swing.JLabel();
        outLabel9 = new javax.swing.JLabel();
        outLabel10 = new javax.swing.JLabel();
        outLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextArea2 = new javax.swing.JTextArea();
        CopyButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Output");
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(600, 500));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(600, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 500));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 112, 185));
        jLabel1.setText("MySQL Query");

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(0, 112, 185));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Sample");
        jTextArea1.setWrapStyleWord(true);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 112, 185));
        jLabel2.setText("Program Output");

        outLabel0.setBackground(new java.awt.Color(255, 255, 255));
        outLabel0.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        outLabel0.setForeground(new java.awt.Color(0, 112, 185));
        outLabel0.setText("-");

        outLabel1.setBackground(new java.awt.Color(255, 255, 255));
        outLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        outLabel1.setForeground(new java.awt.Color(0, 112, 185));
        outLabel1.setText("-");

        outLabel2.setBackground(new java.awt.Color(255, 255, 255));
        outLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        outLabel2.setForeground(new java.awt.Color(0, 112, 185));
        outLabel2.setText("-");

        outLabel3.setBackground(new java.awt.Color(255, 255, 255));
        outLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        outLabel3.setForeground(new java.awt.Color(0, 112, 185));
        outLabel3.setText("-");

        outLabel4.setBackground(new java.awt.Color(255, 255, 255));
        outLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        outLabel4.setForeground(new java.awt.Color(0, 112, 185));
        outLabel4.setText("-");

        outLabel5.setBackground(new java.awt.Color(255, 255, 255));
        outLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        outLabel5.setForeground(new java.awt.Color(0, 112, 185));
        outLabel5.setText("-");

        outLabel6.setBackground(new java.awt.Color(255, 255, 255));
        outLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        outLabel6.setForeground(new java.awt.Color(0, 112, 185));
        outLabel6.setText("-");

        outLabel7.setBackground(new java.awt.Color(255, 255, 255));
        outLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        outLabel7.setForeground(new java.awt.Color(0, 112, 185));
        outLabel7.setText("-");

        outLabel8.setBackground(new java.awt.Color(255, 255, 255));
        outLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        outLabel8.setForeground(new java.awt.Color(0, 112, 185));
        outLabel8.setText("-");

        outLabel9.setBackground(new java.awt.Color(255, 255, 255));
        outLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        outLabel9.setForeground(new java.awt.Color(0, 112, 185));
        outLabel9.setText("-");

        outLabel10.setBackground(new java.awt.Color(255, 255, 255));
        outLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        outLabel10.setForeground(new java.awt.Color(0, 112, 185));
        outLabel10.setText("-");

        outLabel11.setBackground(new java.awt.Color(255, 255, 255));
        outLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        outLabel11.setForeground(new java.awt.Color(0, 112, 185));
        outLabel11.setText("-");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 112, 185));
        jLabel3.setText("File Location");

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextArea2.setForeground(new java.awt.Color(0, 112, 185));
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setText("Sample");
        jTextArea2.setWrapStyleWord(true);

        CopyButton.setBackground(new java.awt.Color(0, 63, 105));
        CopyButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        CopyButton.setForeground(new java.awt.Color(191, 182, 172));
        CopyButton.setText("Copy Directory Location");
        CopyButton.setMaximumSize(new java.awt.Dimension(100, 26));
        CopyButton.setMinimumSize(new java.awt.Dimension(100, 26));
        CopyButton.setPreferredSize(new java.awt.Dimension(100, 26));
        CopyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CopyButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(outLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(outLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(outLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(outLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(outLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(outLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(outLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(outLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(outLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(outLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(outLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jTextArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jTextArea2, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CopyButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 2, Short.MAX_VALUE))
                    .addComponent(outLabel0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextArea1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextArea2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CopyButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(outLabel0, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CopyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CopyButtonActionPerformed
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        Clipboard clipboard = toolkit.getSystemClipboard();
        StringSelection strSel = new StringSelection(form.file_path);
        clipboard.setContents(strSel, null);
        
        System.out.println("Directory Location Copied to Clipboard");
    }//GEN-LAST:event_CopyButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CopyButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel outLabel0;
    private javax.swing.JLabel outLabel1;
    private javax.swing.JLabel outLabel10;
    private javax.swing.JLabel outLabel11;
    private javax.swing.JLabel outLabel2;
    private javax.swing.JLabel outLabel3;
    private javax.swing.JLabel outLabel4;
    private javax.swing.JLabel outLabel5;
    private javax.swing.JLabel outLabel6;
    private javax.swing.JLabel outLabel7;
    private javax.swing.JLabel outLabel8;
    private javax.swing.JLabel outLabel9;
    // End of variables declaration//GEN-END:variables
}
