################################################################
### THIS FILE CONTAINS CODE TO CREATE AN OBS OVERLAY FILE FOR PAVE.
### The program requires hourly data (AQS, SEARCH, CASTNet) data in
### order to create the PAVE overlay file.  The script is given a time
### period to query the database for, and then creates a data file that
### can be used the the program bldoverlay.exe to create the overlay
### file.  
### The time period of the query should be limited to about a month for
### AQS network if querying the entire domain due to memory limits.
###
### Modified to work with combined MET/AQ mode, Alexis Zubrow (IE UNC) Nov, 2007
###
################################################################

## get some environmental variables and setup some directories
ametbase<-Sys.getenv("AMETBASE") 			# base directory of AMET
dbase<-Sys.getenv("AMET_DATABASE")      # AMET database
ametR<-paste(ametbase,"/R",sep="")                    # R directory
ametRinput <- Sys.getenv("AMETRINPUT")                # input file for this script

## Check for output directory via namelist and AMET_OUT env var, if not specified in namelist
## and not specified via AMET_OUT, then set figdir to the current directory
if(!exists("figdir") )                         { figdir <- Sys.getenv("AMET_OUT")	}
if( length(unlist(strsplit(figdir,""))) == 0 ) { figdir <- "./"			}

## source some configuration files, AMET libs, and input
source(paste(ametbase,"/configure/amet-config.R",sep=""))
source (paste(ametR,"/AQ_Misc_Functions.R",sep=""))  	# Miscellanous AMET R-functions file
source (ametRinput)	                                # Anaysis configuration/input file
source (ametNetworkInput) # Network related input

## Load Required Libraries
if(!require(RMySQL)){stop("Required Package RMySQL was not loaded")}
if(!require(ncdf)){stop("Required Package ncdf was not loaded")}
if(!require(date)){stop("Required Package date was not loaded")}
if(!require(chron)){stop("Required Package chron was not loaded")}
if(!require(RMySQL)){stop("Required Package RMySQL was not loaded")}
if(!require(DBI)){stop("Required Package DBI was not loaded")}
if(!require(maps)){stop("Required Package maps was not loaded")}
if(!require(mapdata)){stop("Required Package mapdata was not loaded")}
if(!require(akima)){stop("Required Package akima was not loaded")}

################################################
## Set output names and remove existing files ##
################################################
filename_out <- "ozone_overlay_input.csv"		# input file generated by this R script to be used by bldoverlay.exe
filename_script <- "runOBS.sh"				# script to run that sets environmental variables and calls bldoverlay.exe

## set path to bldoverlay scripts
Bldoverlay_exe <- paste(ametbase,"bin/bldoverlay",sep="")
## Create a full path to file
filename_out <- paste(figdir,filename_out,sep="/")
filename_script <- paste(figdir,filename_script,sep="/")

#################################################

{
   if (overlay_opt == 1) {
      overlay_type = "HOURLY"
   }
   else if (overlay_opt == 2) {
      overlay_type = "DAILY"
   }
   else if (overlay_opt == 3) {
     overlay_type = "1HRMAX"
   }
   else {
      overlay_type = "8HRMAX"
   }
}

mysql <- list(login=login, passwd=passwd, server=server, dbase=dbase, maxrec=maxrec)		# Set MYSQL login and query options


j <- 1							# only use first network (not coded for multiple networks)
network<-network_names[[j]]				# set network
query <- paste(" and s.stat_id=d.stat_id and d.ob_dates BETWEEN",start_date,"and",end_date,"and d.ob_datee BETWEEN",start_date,"and",end_date,"and ob_hour between",start_hour,"and",end_hour,add_query,sep=" ")

criteria <- paste(" WHERE d.",species,"_ob is not NULL and d.network='",network,"' ",query,sep="")          # Set part of the MYSQL query
qs <- paste("SELECT d.stat_id,s.num_stat_id,d.lat,d.lon,d.ob_dates,DATE_FORMAT(d.ob_dates,'%Y%j'),d.ob_hour,d.",species,"_ob,d.",species,"_mod, month from ",run_name1," as d, site_metadata as s",criteria," ORDER BY ob_dates,ob_hour",sep="")		# set rest of MYSQL query

aqdat.df<-db_Query(qs,mysql)						# query the database

## test that the query worked
if (length(aqdat.df) == 0){
  ## error the queried returned nothing
  writeLines("ERROR: Check species/network pairing and Obs start and end dates")
  stop(paste("ERROR querying db: \n",qs))
}

year_day <- aqdat.df$"DATE_FORMAT(d.ob_dates,'%Y%j')" 

{
   if (network == "CASTNet_hourly") {
      output <- paste(year_day,aqdat.df$ob_hour,aqdat.df$num_stat_id,aqdat.df$lon,aqdat.df$lat,aqdat.df[,8],sep=",")	# set output to be written 
      write.table(output, file=filename_out, append=F ,sep="",col.names=F,row.names=F,quote=F)		# write data to be used by bldoverlay.exe
   }
   else {
      output <- paste(year_day,aqdat.df$ob_hour,aqdat.df$stat_id,aqdat.df$lon,aqdat.df$lat,aqdat.df[,8],sep=",")    # set output to be written 
      write.table(output, file=filename_out, append=F ,sep="",col.names=F,row.names=F,quote=F)             # write data to be used by bldoverlay.exe
   }
}
#################################

### Create script to be run ###
write("#!/bin/sh", file=filename_script, append=F)
write("FILETYPE=OBS; export FILETYPE", file=filename_script, append=T)
write(paste("INFILE=",figdir,"/","ozone_overlay_input.csv; export INFILE",sep=""), file=filename_script, append=T)
write("SPECIES=\"O3\"; export SPECIES", file=filename_script, append=T)
write("UNITS=\"ppb\"; export UNITS", file=filename_script, append=T)
write(paste("OLAYTYPE=",overlay_type,"; export OLAYTYPE",sep=""), file=filename_script, append=T)
write(paste("OUTFILE=",figdir,"/",run_name1,"_pave_overlay.ncf; export OUTFILE",sep=""), file=filename_script, append=T)
write(Bldoverlay_exe, file=filename_script, append=T)
#######################

system(paste("chmod +x ",filename_script, sep=""))					# give execute permissions to script that is generated
  
