/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ametjavagui.AQAdvancedForms;

import ametjavagui.AirQualityForm;

/**
 *
 * @author MMORTO01
 */
public class AxisOptionsPlots extends javax.swing.JFrame {

    /**
     * Creates new form AxisOptionsPlots
     */
    
    AirQualityForm form;
    
    public AxisOptionsPlots(AirQualityForm form) {
        this.form = form;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        AxisOptionsLabel = new javax.swing.JLabel();
        XMinLabel = new javax.swing.JLabel();
        YMinLabel = new javax.swing.JLabel();
        BiasYMinLabel = new javax.swing.JLabel();
        DensityZMaxLabel = new javax.swing.JLabel();
        SkillPlotMaxLabel = new javax.swing.JLabel();
        XLabelAngleLabel = new javax.swing.JLabel();
        XMinTextField = new javax.swing.JTextField();
        YMinTextField = new javax.swing.JTextField();
        BiasYMinTextField = new javax.swing.JTextField();
        DensityZMaxTextField = new javax.swing.JTextField();
        SkillPlotMaxTextField = new javax.swing.JTextField();
        XLabelAngleTextField = new javax.swing.JTextField();
        XMaxLabel = new javax.swing.JLabel();
        YMaxLabel = new javax.swing.JLabel();
        BiasYMaxLabel = new javax.swing.JLabel();
        DensityNumBinsLabel = new javax.swing.JLabel();
        XMaxTextField = new javax.swing.JTextField();
        YMaxTextField = new javax.swing.JTextField();
        BiasYMaxTextField = new javax.swing.JTextField();
        DensityNumBinsTextField = new javax.swing.JTextField();
        AxisOptionsInfoLabel = new javax.swing.JTextArea();
        SaveButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Axis Options for Plots");
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(503, 407));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(509, 407));
        jPanel1.setMinimumSize(new java.awt.Dimension(503, 407));
        jPanel1.setPreferredSize(new java.awt.Dimension(509, 407));

        AxisOptionsLabel.setBackground(new java.awt.Color(255, 255, 255));
        AxisOptionsLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        AxisOptionsLabel.setForeground(new java.awt.Color(0, 112, 185));
        AxisOptionsLabel.setText("Axis Options for Plots");

        XMinLabel.setBackground(new java.awt.Color(255, 255, 255));
        XMinLabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        XMinLabel.setForeground(new java.awt.Color(0, 112, 185));
        XMinLabel.setText("X Axis Min:");

        YMinLabel.setBackground(new java.awt.Color(255, 255, 255));
        YMinLabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        YMinLabel.setForeground(new java.awt.Color(0, 112, 185));
        YMinLabel.setText("Y Axis Min:");

        BiasYMinLabel.setBackground(new java.awt.Color(255, 255, 255));
        BiasYMinLabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        BiasYMinLabel.setForeground(new java.awt.Color(0, 112, 185));
        BiasYMinLabel.setText("Bias Y Axis Min:");

        DensityZMaxLabel.setBackground(new java.awt.Color(255, 255, 255));
        DensityZMaxLabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        DensityZMaxLabel.setForeground(new java.awt.Color(0, 112, 185));
        DensityZMaxLabel.setText("Density Z Limit Max:");

        SkillPlotMaxLabel.setBackground(new java.awt.Color(255, 255, 255));
        SkillPlotMaxLabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        SkillPlotMaxLabel.setForeground(new java.awt.Color(0, 112, 185));
        SkillPlotMaxLabel.setText("Skill Plot Max Limit:");

        XLabelAngleLabel.setBackground(new java.awt.Color(255, 255, 255));
        XLabelAngleLabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        XLabelAngleLabel.setForeground(new java.awt.Color(0, 112, 185));
        XLabelAngleLabel.setText("X Axis Label Angle:");

        XMinTextField.setBackground(new java.awt.Color(191, 182, 172));
        XMinTextField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        XMinTextField.setForeground(new java.awt.Color(0, 63, 105));
        XMinTextField.setMinimumSize(new java.awt.Dimension(60, 23));
        XMinTextField.setPreferredSize(new java.awt.Dimension(60, 23));

        YMinTextField.setBackground(new java.awt.Color(191, 182, 172));
        YMinTextField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        YMinTextField.setForeground(new java.awt.Color(0, 63, 105));
        YMinTextField.setMinimumSize(new java.awt.Dimension(60, 23));
        YMinTextField.setPreferredSize(new java.awt.Dimension(60, 23));

        BiasYMinTextField.setBackground(new java.awt.Color(191, 182, 172));
        BiasYMinTextField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BiasYMinTextField.setForeground(new java.awt.Color(0, 63, 105));
        BiasYMinTextField.setMinimumSize(new java.awt.Dimension(60, 23));
        BiasYMinTextField.setPreferredSize(new java.awt.Dimension(60, 23));

        DensityZMaxTextField.setBackground(new java.awt.Color(191, 182, 172));
        DensityZMaxTextField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        DensityZMaxTextField.setForeground(new java.awt.Color(0, 63, 105));
        DensityZMaxTextField.setMinimumSize(new java.awt.Dimension(60, 23));
        DensityZMaxTextField.setPreferredSize(new java.awt.Dimension(60, 23));

        SkillPlotMaxTextField.setBackground(new java.awt.Color(191, 182, 172));
        SkillPlotMaxTextField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        SkillPlotMaxTextField.setForeground(new java.awt.Color(0, 63, 105));
        SkillPlotMaxTextField.setText("70");
        SkillPlotMaxTextField.setMinimumSize(new java.awt.Dimension(60, 23));
        SkillPlotMaxTextField.setPreferredSize(new java.awt.Dimension(60, 23));

        XLabelAngleTextField.setBackground(new java.awt.Color(191, 182, 172));
        XLabelAngleTextField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        XLabelAngleTextField.setForeground(new java.awt.Color(0, 63, 105));
        XLabelAngleTextField.setText("0");
        XLabelAngleTextField.setMinimumSize(new java.awt.Dimension(60, 23));
        XLabelAngleTextField.setPreferredSize(new java.awt.Dimension(60, 23));

        XMaxLabel.setBackground(new java.awt.Color(255, 255, 255));
        XMaxLabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        XMaxLabel.setForeground(new java.awt.Color(0, 112, 185));
        XMaxLabel.setText("X Axis Max:");

        YMaxLabel.setBackground(new java.awt.Color(255, 255, 255));
        YMaxLabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        YMaxLabel.setForeground(new java.awt.Color(0, 112, 185));
        YMaxLabel.setText("Y Axis Max:");

        BiasYMaxLabel.setBackground(new java.awt.Color(255, 255, 255));
        BiasYMaxLabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        BiasYMaxLabel.setForeground(new java.awt.Color(0, 112, 185));
        BiasYMaxLabel.setText("Bias Y Axis Max:");

        DensityNumBinsLabel.setBackground(new java.awt.Color(255, 255, 255));
        DensityNumBinsLabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        DensityNumBinsLabel.setForeground(new java.awt.Color(0, 112, 185));
        DensityNumBinsLabel.setText("Density Number of Bins:");

        XMaxTextField.setBackground(new java.awt.Color(191, 182, 172));
        XMaxTextField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        XMaxTextField.setForeground(new java.awt.Color(0, 63, 105));
        XMaxTextField.setMinimumSize(new java.awt.Dimension(60, 23));
        XMaxTextField.setPreferredSize(new java.awt.Dimension(60, 23));

        YMaxTextField.setBackground(new java.awt.Color(191, 182, 172));
        YMaxTextField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        YMaxTextField.setForeground(new java.awt.Color(0, 63, 105));
        YMaxTextField.setMinimumSize(new java.awt.Dimension(60, 23));
        YMaxTextField.setPreferredSize(new java.awt.Dimension(60, 23));

        BiasYMaxTextField.setBackground(new java.awt.Color(191, 182, 172));
        BiasYMaxTextField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BiasYMaxTextField.setForeground(new java.awt.Color(0, 63, 105));
        BiasYMaxTextField.setMinimumSize(new java.awt.Dimension(60, 23));
        BiasYMaxTextField.setPreferredSize(new java.awt.Dimension(60, 23));

        DensityNumBinsTextField.setBackground(new java.awt.Color(191, 182, 172));
        DensityNumBinsTextField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        DensityNumBinsTextField.setForeground(new java.awt.Color(0, 63, 105));
        DensityNumBinsTextField.setMinimumSize(new java.awt.Dimension(60, 23));
        DensityNumBinsTextField.setPreferredSize(new java.awt.Dimension(60, 23));

        AxisOptionsInfoLabel.setEditable(false);
        AxisOptionsInfoLabel.setBackground(new java.awt.Color(255, 255, 255));
        AxisOptionsInfoLabel.setColumns(20);
        AxisOptionsInfoLabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        AxisOptionsInfoLabel.setForeground(new java.awt.Color(0, 112, 185));
        AxisOptionsInfoLabel.setLineWrap(true);
        AxisOptionsInfoLabel.setRows(5);
        AxisOptionsInfoLabel.setText("Enter a value above to set the X and Y axis limits for several plots (scatter, box, stacked bar, time series, etc). The density values only apply to the density scatter plot.  The skill plot max limit only applies to the skill scatterplot. Leave the value blank to use the value calculated by the script.");
        AxisOptionsInfoLabel.setWrapStyleWord(true);
        AxisOptionsInfoLabel.setMaximumSize(new java.awt.Dimension(463, 79));
        AxisOptionsInfoLabel.setMinimumSize(new java.awt.Dimension(463, 79));
        AxisOptionsInfoLabel.setPreferredSize(new java.awt.Dimension(463, 79));

        SaveButton.setBackground(new java.awt.Color(0, 63, 105));
        SaveButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        SaveButton.setForeground(new java.awt.Color(191, 182, 172));
        SaveButton.setText("Save");
        SaveButton.setMaximumSize(new java.awt.Dimension(100, 26));
        SaveButton.setMinimumSize(new java.awt.Dimension(100, 26));
        SaveButton.setPreferredSize(new java.awt.Dimension(100, 26));
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        CancelButton.setBackground(new java.awt.Color(0, 63, 105));
        CancelButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        CancelButton.setForeground(new java.awt.Color(191, 182, 172));
        CancelButton.setText("Cancel");
        CancelButton.setMaximumSize(new java.awt.Dimension(100, 26));
        CancelButton.setMinimumSize(new java.awt.Dimension(100, 26));
        CancelButton.setPreferredSize(new java.awt.Dimension(100, 26));
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AxisOptionsLabel)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(SkillPlotMaxLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(SkillPlotMaxTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(XMinLabel)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(XMinTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(YMinLabel)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(YMinTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(BiasYMinLabel)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(BiasYMinTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(DensityZMaxLabel)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(DensityZMaxTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(XLabelAngleLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(XLabelAngleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(XMaxLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(XMaxTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(DensityNumBinsLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(DensityNumBinsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(YMaxLabel)
                                                    .addComponent(BiasYMaxLabel))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(BiasYMaxTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(YMaxTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                            .addComponent(AxisOptionsInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(SaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(CancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AxisOptionsLabel)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(XMaxLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(XMinLabel)
                        .addComponent(XMaxTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(XMinTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(YMinLabel)
                    .addComponent(YMinTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(YMaxLabel)
                    .addComponent(YMaxTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BiasYMinLabel)
                    .addComponent(BiasYMinTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BiasYMaxLabel)
                    .addComponent(BiasYMaxTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DensityZMaxLabel)
                    .addComponent(DensityZMaxTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DensityNumBinsLabel)
                    .addComponent(DensityNumBinsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SkillPlotMaxTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SkillPlotMaxLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(XLabelAngleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(XLabelAngleLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AxisOptionsInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        form.x_axis_min = form.numNullFormat(XMinTextField.getText());
        form.x_axis_max = form.numNullFormat(XMaxTextField.getText());
        form.y_axis_min = form.numNullFormat(YMinTextField.getText());
        form.y_axis_max = form.numNullFormat(YMaxTextField.getText());
        form.bias_y_axis_min = form.numNullFormat(BiasYMinTextField.getText());
        form.bias_y_axis_max = form.numNullFormat(BiasYMaxTextField.getText());
        form.density_zlim = form.numNullFormat(DensityZMaxTextField.getText());
        form.num_dens_bins = form.numNullFormat(DensityNumBinsTextField.getText());
        form.max_limit = form.numNullFormat(SkillPlotMaxTextField.getText());
        form.x_label_angle = form.numNullFormat(XLabelAngleTextField.getText());
        System.out.println("Axis Options for Plots Saved");
        setVisible(false);
        dispose();
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_CancelButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AxisOptionsInfoLabel;
    private javax.swing.JLabel AxisOptionsLabel;
    private javax.swing.JLabel BiasYMaxLabel;
    private javax.swing.JTextField BiasYMaxTextField;
    private javax.swing.JLabel BiasYMinLabel;
    private javax.swing.JTextField BiasYMinTextField;
    private javax.swing.JButton CancelButton;
    private javax.swing.JLabel DensityNumBinsLabel;
    private javax.swing.JTextField DensityNumBinsTextField;
    private javax.swing.JLabel DensityZMaxLabel;
    private javax.swing.JTextField DensityZMaxTextField;
    private javax.swing.JButton SaveButton;
    private javax.swing.JLabel SkillPlotMaxLabel;
    private javax.swing.JTextField SkillPlotMaxTextField;
    private javax.swing.JLabel XLabelAngleLabel;
    private javax.swing.JTextField XLabelAngleTextField;
    private javax.swing.JLabel XMaxLabel;
    private javax.swing.JTextField XMaxTextField;
    private javax.swing.JLabel XMinLabel;
    private javax.swing.JTextField XMinTextField;
    private javax.swing.JLabel YMaxLabel;
    private javax.swing.JTextField YMaxTextField;
    private javax.swing.JLabel YMinLabel;
    private javax.swing.JTextField YMinTextField;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
