/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ametjavagui.AQAdvancedForms;

import ametjavagui.AirQualityForm;

/**
 *
 * @author MMORTO01
 */
public class SoccergoalBuglePlotOptions extends javax.swing.JFrame {

    /**
     * Creates new form SoccergoalBuglePlotSettings
     */
    
    AirQualityForm form;
    
    public SoccergoalBuglePlotOptions(AirQualityForm form) {
        this.form = form;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        SoccergoalBuglePlotLabel = new javax.swing.JLabel();
        StatisticsLabel = new javax.swing.JLabel();
        StatisticsComboBox = new javax.swing.JComboBox<>();
        KellyPlotLabel = new javax.swing.JLabel();
        NMBMinMaxLabel = new javax.swing.JLabel();
        NMBMinMaxTextField = new javax.swing.JTextField();
        NMEMaxLabel = new javax.swing.JLabel();
        NMEMaxTextField = new javax.swing.JTextField();
        MEMinLabel = new javax.swing.JLabel();
        MEMinTextField = new javax.swing.JTextField();
        RMSEMinLabel = new javax.swing.JLabel();
        RMSEMinTextField = new javax.swing.JTextField();
        MBMinMaxLabel = new javax.swing.JLabel();
        MBMinMaxTextField = new javax.swing.JTextField();
        NMBIntervalLabel = new javax.swing.JLabel();
        NMBIntervalTextField = new javax.swing.JTextField();
        NMEIntervalLabel = new javax.swing.JLabel();
        NMEIntervalTextField = new javax.swing.JTextField();
        MEMaxLabel = new javax.swing.JLabel();
        MEMaxTextField = new javax.swing.JTextField();
        RMSEMaxLabel = new javax.swing.JLabel();
        RMSEMaxTextField = new javax.swing.JTextField();
        SaveButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Soccergoal / Bugle / Kelly Plot Options");
        setMinimumSize(new java.awt.Dimension(405, 370));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(405, 370));
        jPanel1.setMinimumSize(new java.awt.Dimension(405, 370));
        jPanel1.setPreferredSize(new java.awt.Dimension(405, 370));

        SoccergoalBuglePlotLabel.setBackground(new java.awt.Color(255, 255, 255));
        SoccergoalBuglePlotLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        SoccergoalBuglePlotLabel.setForeground(new java.awt.Color(0, 112, 185));
        SoccergoalBuglePlotLabel.setText("Soccergoal Plot / Bugle Plot Options");

        StatisticsLabel.setBackground(new java.awt.Color(255, 255, 255));
        StatisticsLabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        StatisticsLabel.setForeground(new java.awt.Color(0, 112, 185));
        StatisticsLabel.setText("Select statistics to plot:");

        StatisticsComboBox.setBackground(new java.awt.Color(191, 182, 172));
        StatisticsComboBox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        StatisticsComboBox.setForeground(new java.awt.Color(0, 63, 105));
        StatisticsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NMB vs. NME", "FB vs. FE", "NMdnB vs. NMdnE" }));

        KellyPlotLabel.setBackground(new java.awt.Color(255, 255, 255));
        KellyPlotLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        KellyPlotLabel.setForeground(new java.awt.Color(0, 112, 185));
        KellyPlotLabel.setText("Kelly Plot Options");

        NMBMinMaxLabel.setBackground(new java.awt.Color(255, 255, 255));
        NMBMinMaxLabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        NMBMinMaxLabel.setForeground(new java.awt.Color(0, 112, 185));
        NMBMinMaxLabel.setText("NMB Min / Max:");

        NMBMinMaxTextField.setBackground(new java.awt.Color(191, 182, 172));
        NMBMinMaxTextField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        NMBMinMaxTextField.setForeground(new java.awt.Color(0, 63, 105));
        NMBMinMaxTextField.setMinimumSize(new java.awt.Dimension(60, 23));
        NMBMinMaxTextField.setPreferredSize(new java.awt.Dimension(60, 23));

        NMEMaxLabel.setBackground(new java.awt.Color(255, 255, 255));
        NMEMaxLabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        NMEMaxLabel.setForeground(new java.awt.Color(0, 112, 185));
        NMEMaxLabel.setText("NME Max:");

        NMEMaxTextField.setBackground(new java.awt.Color(191, 182, 172));
        NMEMaxTextField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        NMEMaxTextField.setForeground(new java.awt.Color(0, 63, 105));
        NMEMaxTextField.setMinimumSize(new java.awt.Dimension(60, 23));
        NMEMaxTextField.setPreferredSize(new java.awt.Dimension(60, 23));

        MEMinLabel.setBackground(new java.awt.Color(255, 255, 255));
        MEMinLabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        MEMinLabel.setForeground(new java.awt.Color(0, 112, 185));
        MEMinLabel.setText("ME Min:");

        MEMinTextField.setBackground(new java.awt.Color(191, 182, 172));
        MEMinTextField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        MEMinTextField.setForeground(new java.awt.Color(0, 63, 105));
        MEMinTextField.setMinimumSize(new java.awt.Dimension(60, 23));
        MEMinTextField.setPreferredSize(new java.awt.Dimension(60, 23));

        RMSEMinLabel.setBackground(new java.awt.Color(255, 255, 255));
        RMSEMinLabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        RMSEMinLabel.setForeground(new java.awt.Color(0, 112, 185));
        RMSEMinLabel.setText("RMSE Min:");

        RMSEMinTextField.setBackground(new java.awt.Color(191, 182, 172));
        RMSEMinTextField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        RMSEMinTextField.setForeground(new java.awt.Color(0, 63, 105));
        RMSEMinTextField.setMinimumSize(new java.awt.Dimension(60, 23));
        RMSEMinTextField.setPreferredSize(new java.awt.Dimension(60, 23));

        MBMinMaxLabel.setBackground(new java.awt.Color(255, 255, 255));
        MBMinMaxLabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        MBMinMaxLabel.setForeground(new java.awt.Color(0, 112, 185));
        MBMinMaxLabel.setText("MB Min/ Max:");

        MBMinMaxTextField.setBackground(new java.awt.Color(191, 182, 172));
        MBMinMaxTextField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        MBMinMaxTextField.setForeground(new java.awt.Color(0, 63, 105));
        MBMinMaxTextField.setMinimumSize(new java.awt.Dimension(60, 23));
        MBMinMaxTextField.setPreferredSize(new java.awt.Dimension(60, 23));

        NMBIntervalLabel.setBackground(new java.awt.Color(255, 255, 255));
        NMBIntervalLabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        NMBIntervalLabel.setForeground(new java.awt.Color(0, 112, 185));
        NMBIntervalLabel.setText("NMB Interval:");

        NMBIntervalTextField.setBackground(new java.awt.Color(191, 182, 172));
        NMBIntervalTextField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        NMBIntervalTextField.setForeground(new java.awt.Color(0, 63, 105));
        NMBIntervalTextField.setMinimumSize(new java.awt.Dimension(60, 23));
        NMBIntervalTextField.setPreferredSize(new java.awt.Dimension(60, 23));

        NMEIntervalLabel.setBackground(new java.awt.Color(255, 255, 255));
        NMEIntervalLabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        NMEIntervalLabel.setForeground(new java.awt.Color(0, 112, 185));
        NMEIntervalLabel.setText("NME Interval:");

        NMEIntervalTextField.setBackground(new java.awt.Color(191, 182, 172));
        NMEIntervalTextField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        NMEIntervalTextField.setForeground(new java.awt.Color(0, 63, 105));
        NMEIntervalTextField.setMinimumSize(new java.awt.Dimension(60, 23));
        NMEIntervalTextField.setPreferredSize(new java.awt.Dimension(60, 23));

        MEMaxLabel.setBackground(new java.awt.Color(255, 255, 255));
        MEMaxLabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        MEMaxLabel.setForeground(new java.awt.Color(0, 112, 185));
        MEMaxLabel.setText("ME Max:");

        MEMaxTextField.setBackground(new java.awt.Color(191, 182, 172));
        MEMaxTextField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        MEMaxTextField.setForeground(new java.awt.Color(0, 63, 105));
        MEMaxTextField.setMinimumSize(new java.awt.Dimension(60, 23));
        MEMaxTextField.setPreferredSize(new java.awt.Dimension(60, 23));

        RMSEMaxLabel.setBackground(new java.awt.Color(255, 255, 255));
        RMSEMaxLabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        RMSEMaxLabel.setForeground(new java.awt.Color(0, 112, 185));
        RMSEMaxLabel.setText("RMSE Max:");

        RMSEMaxTextField.setBackground(new java.awt.Color(191, 182, 172));
        RMSEMaxTextField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        RMSEMaxTextField.setForeground(new java.awt.Color(0, 63, 105));
        RMSEMaxTextField.setMinimumSize(new java.awt.Dimension(60, 23));
        RMSEMaxTextField.setPreferredSize(new java.awt.Dimension(60, 23));

        SaveButton.setBackground(new java.awt.Color(0, 63, 105));
        SaveButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        SaveButton.setForeground(new java.awt.Color(191, 182, 172));
        SaveButton.setText("Save");
        SaveButton.setMaximumSize(new java.awt.Dimension(100, 26));
        SaveButton.setMinimumSize(new java.awt.Dimension(100, 26));
        SaveButton.setPreferredSize(new java.awt.Dimension(100, 26));
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        CancelButton.setBackground(new java.awt.Color(0, 63, 105));
        CancelButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        CancelButton.setForeground(new java.awt.Color(191, 182, 172));
        CancelButton.setText("Cancel");
        CancelButton.setMaximumSize(new java.awt.Dimension(100, 26));
        CancelButton.setMinimumSize(new java.awt.Dimension(100, 26));
        CancelButton.setPreferredSize(new java.awt.Dimension(100, 26));
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SoccergoalBuglePlotLabel)
                    .addComponent(StatisticsLabel)
                    .addComponent(StatisticsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(KellyPlotLabel)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(MBMinMaxLabel)
                            .addComponent(NMBMinMaxLabel)
                            .addComponent(NMEMaxLabel)
                            .addComponent(MEMinLabel)
                            .addComponent(RMSEMinLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(NMBMinMaxTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(NMBIntervalLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NMBIntervalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(RMSEMinTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(RMSEMaxLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(RMSEMaxTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(MEMinTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(MEMaxLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(MEMaxTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(NMEMaxTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(NMEIntervalLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(NMEIntervalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(MBMinMaxTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(SaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(CancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SoccergoalBuglePlotLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(StatisticsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StatisticsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(KellyPlotLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NMBMinMaxLabel)
                    .addComponent(NMBMinMaxTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NMBIntervalLabel)
                    .addComponent(NMBIntervalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NMEMaxLabel)
                    .addComponent(NMEMaxTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NMEIntervalLabel)
                    .addComponent(NMEIntervalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MEMinLabel)
                    .addComponent(MEMinTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MEMaxLabel)
                    .addComponent(MEMaxTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RMSEMinLabel)
                    .addComponent(RMSEMinTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RMSEMaxLabel)
                    .addComponent(RMSEMaxTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MBMinMaxLabel)
                    .addComponent(MBMinMaxTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        form.soccerplot_opt = plotOptionFormat(StatisticsComboBox.getSelectedItem().toString());
        form.nmb_max = form.numNullFormat(NMBMinMaxTextField.getText());
        form.nmb_int = form.numNullFormat(NMBIntervalTextField.getText());
        form.nme_max = form.numNullFormat(NMEMaxTextField.getText());
        form.nme_int = form.numNullFormat(NMEIntervalTextField.getText());
        form.mb_max = form.numNullFormat(MBMinMaxTextField.getText());
        form.me_min = form.numNullFormat(MEMinTextField.getText());
        form.me_max = form.numNullFormat(MEMaxTextField.getText());
        form.rmse_min = form.numNullFormat(RMSEMinTextField.getText());
        form.rmse_max = form.numNullFormat(RMSEMaxTextField.getText());
        System.out.println("Soccergoal / Bugle Plot Options Saved");
        setVisible(false);
        dispose();
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_CancelButtonActionPerformed

    private String plotOptionFormat(String str) {
        switch(str) {
            case "NMB vs. NME":
                return "1";
            case "FB vs. FE":
                return "2";
            case "NMdnB vs. NMdnE":
                return "3";
            default:
                return "";
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton;
    private javax.swing.JLabel KellyPlotLabel;
    private javax.swing.JLabel MBMinMaxLabel;
    private javax.swing.JTextField MBMinMaxTextField;
    private javax.swing.JLabel MEMaxLabel;
    private javax.swing.JTextField MEMaxTextField;
    private javax.swing.JLabel MEMinLabel;
    private javax.swing.JTextField MEMinTextField;
    private javax.swing.JLabel NMBIntervalLabel;
    private javax.swing.JTextField NMBIntervalTextField;
    private javax.swing.JLabel NMBMinMaxLabel;
    private javax.swing.JTextField NMBMinMaxTextField;
    private javax.swing.JLabel NMEIntervalLabel;
    private javax.swing.JTextField NMEIntervalTextField;
    private javax.swing.JLabel NMEMaxLabel;
    private javax.swing.JTextField NMEMaxTextField;
    private javax.swing.JLabel RMSEMaxLabel;
    private javax.swing.JTextField RMSEMaxTextField;
    private javax.swing.JLabel RMSEMinLabel;
    private javax.swing.JTextField RMSEMinTextField;
    private javax.swing.JButton SaveButton;
    private javax.swing.JLabel SoccergoalBuglePlotLabel;
    private javax.swing.JComboBox<String> StatisticsComboBox;
    private javax.swing.JLabel StatisticsLabel;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
